/* All writes require a user-visible review and the server capability allowlist. */
(function(g){'use strict';
 const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const uid=()=>g.crypto?.randomUUID?.()||'review_'+Date.now()+'_'+Math.random().toString(36).slice(2);
 const label=s=>s.replaceAll('_',' ').replaceAll('-',' ').replace(/\b\w/g,c=>c.toUpperCase());
 const moduleNames={finance:'Finance',gym:'Gym',todos:'General To-Do',calendar:'Timetable',reminders:'Reminders',notes:'Notes',subjects:'Subjects',topics:'Topics',questions:'Quiz questions',quizzes:'Quizzes',flashcards:'Flashcards',quick:'Quick Review Cards',social:'Socialise',market:'Marketplace',settings:'Settings',navigate:'Navigation'};
 async function request(url,body){const r=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const x=await r.json();if(!r.ok||x.ok===false)throw Error(x.error||'Could not complete this request.');return x}
 function create(o){let catalog;
  const capabilities=async()=>catalog||(catalog=await request('/api/assistant/capabilities'));
  function showDialog(title,body){const host=document.getElementById('modalRoot');host.innerHTML=`<div class="modal-backdrop"><form class="modal wide assistant-review" role="dialog" aria-modal="true" aria-label="${E(title)}"><div class="modal-head"><h2>${E(title)}</h2><button type="button" data-close class="modal-close" aria-label="Close">×</button></div>${body}</form></div>`;return {host,form:host.querySelector('form')}}
  async function review(proposal,state){const c=await capabilities(),m=c.operations[proposal.operation];if(!m)throw Error('This action is not supported. Nothing was saved.');const values=proposal.data||{},fields=[...new Set([...Object.keys(values),...Object.keys(m.fields)])],required=proposal.id?[]:m.required,risky=['shared','destructive'].includes(m.risk);
   return new Promise(resolve=>{const {host,form}=showDialog('Review · '+moduleNames[m.module],`<p><b>${E(label(m.action))}</b> · ${E(m.description)}</p><p class="assistant-review-warning">${m.risk==='shared'?'This can share content or notify other people. Check the recipient, workspace and audience.':m.risk==='destructive'?'This removes saved data. Check the exact target; deletion may not be recoverable.':'Nothing is saved until you confirm. Check every amount, date and unit.'}</p>${proposal.id?`<label>Selected record: ${E(proposal.references?.[String(proposal.id)]||'check ID below')}<input name="record_id" value="${E(proposal.id)}" readonly><small>Exact ID from your account. If this is not the right record, cancel and clarify your request.</small></label>`:''}<div class="assistant-field-grid">${fields.map(k=>{const present=Object.hasOwn(values,k),v=present?values[k]:'',example=m.fields[k],json=example!==null&&typeof example==='object',boolean=typeof example==='boolean',type=/date$/.test(k)?'date':/_time$/.test(k)?'time':typeof example==='number'?'number':'text',req=required.includes(k),long=json||['content','text','body','description','notes','explain','routine','bio'].includes(k);return `<label class="${long?'full':''}">${E(label(k))}${typeof v==='string'&&proposal.references?.[v]?' · '+E(proposal.references[v]):''}${req?' *':' (optional)'}${boolean?`<input data-field="${E(k)}" type="checkbox" ${v===true&&k!=='adult_confirmation'?'checked':''}>`:long?`<textarea data-field="${E(k)}" rows="${json?5:3}" ${req?'required':''} data-json="${json}">${E(json&&present?JSON.stringify(v,null,2):v)}</textarea>`:`<input data-field="${E(k)}" type="${type}" step="any" value="${E(v)}" ${req?'required':''}>`}${json?'<small>Structured details (JSON). Review each entry.</small>':''}${m.module==='finance'&&['amount','target','starting','weekly','monthly','opening_amount'].includes(k)?'<small>Amount in your Finance base currency—not cents.</small>':''}${m.module==='gym'&&['protein','carbs','fat'].includes(k)?'<small>Grams. Blank means unknown, not zero.</small>':''}</label>`}).join('')}</div>${risky?'<label class="assistant-ack"><input id="assistantAcknowledge" type="checkbox" required> I checked the target and understand this will '+(m.risk==='shared'?'share/update information visible to other people.':'delete the selected data.')+'</label>':''}<p class="assistant-action-error" role="alert"></p><footer><button type="button" data-close class="btn secondary">Cancel</button><button type="submit" class="btn primary">${m.module==='navigate'?'Open page':m.risk==='destructive'?'Confirm deletion':m.risk==='shared'?'Confirm shared action':'Confirm & save'}</button></footer>`);
    let busy=false;const changed=new Set();form.querySelectorAll('[data-field]').forEach(el=>el.oninput=()=>changed.add(el.dataset.field));const close=v=>{if(busy)return;host.replaceChildren();resolve(v)};form.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>close(false));
    form.onkeydown=ev=>{if(ev.key==='Escape'){ev.preventDefault();ev.stopPropagation();close(false)}if(ev.key==='Tab'){const els=[...form.querySelectorAll('button,input,textarea')].filter(e=>!e.disabled);if(ev.shiftKey&&document.activeElement===els[0]){ev.preventDefault();els.at(-1).focus()}else if(!ev.shiftKey&&document.activeElement===els.at(-1)){ev.preventDefault();els[0].focus()}}};
    form.onsubmit=async ev=>{ev.preventDefault();if(busy)return;busy=true;form.querySelectorAll('button').forEach(b=>b.disabled=true);const error=form.querySelector('[role=alert]');error.textContent='';try{const d={};for(const el of form.querySelectorAll('[data-field]')){const k=el.dataset.field;if(!Object.hasOwn(values,k)&&!changed.has(k)&&!required.includes(k))continue;if(el.type==='checkbox'){d[k]=el.checked;continue}if(el.value===''&&!required.includes(k)){if(changed.has(k)||Object.hasOwn(values,k))d[k]='';continue}if(el.dataset.json==='true'){try{d[k]=JSON.parse(el.value)}catch{throw Error(label(k)+' must contain valid JSON. No changes were sent.')}}else d[k]=el.type==='number'?(el.value===''?null:Number(el.value)):el.value}
      const edited={operation:proposal.operation,id:proposal.id||null,data:d},signature=JSON.stringify(edited);if(state.signature!==signature){state.id=uid();state.signature=signature}await o.beforeSave?.();await request('/api/assistant/prepare',{request_id:state.id,proposal:edited});const result=await request('/api/assistant/execute',{request_id:state.id,confirmed:true,acknowledged:risky?form.querySelector('#assistantAcknowledge').checked:false});
      busy=false;close(result);
     }catch(err){error.textContent=err.message;error.scrollIntoView({block:'nearest'});busy=false;form.querySelectorAll('button').forEach(b=>b.disabled=false)}};
    form.querySelector('[data-field],button').focus();
   })
  }
  function append(proposal){const card=document.createElement('section');card.className='chat-proposal assistant-app-proposal';const [module,action]=proposal.operation.split('.'),state={id:uid()};const details=Object.entries(proposal.data||{}).filter(([,v])=>v!==''&&v!==null).slice(0,7);
   card.innerHTML=`<div class="proposal-heading"><b>${E(moduleNames[module]||module)} · ${E(label(action))}</b><span data-state>Not saved</span></div>${proposal.id?`<small>Target: ${E(proposal.references?.[String(proposal.id)]||proposal.id)}</small>`:''}<dl>${details.map(([k,v])=>`<div><dt>${E(label(k))}</dt><dd>${E(typeof v==='object'?JSON.stringify(v).slice(0,300):v)}</dd></div>`).join('')}</dl><p>Review the details before applying this action.</p><div class="assistant-proposal-buttons"><button type="button" class="proposal-review" data-review>Review ${E(moduleNames[module]||module)} →</button><button type="button" class="proposal-review" data-dismiss>Dismiss</button></div><p data-error role="alert"></p>`;
   const reviewButton=card.querySelector('[data-review]'),dismiss=card.querySelector('[data-dismiss]');dismiss.onclick=()=>{card.querySelector('[data-state]').textContent='Dismissed · No changes';reviewButton.disabled=true;dismiss.disabled=true};reviewButton.onclick=async()=>{reviewButton.disabled=true;try{const result=await review(proposal,state);if(!result){reviewButton.disabled=false;return}card.classList.add('saved');card.querySelector('[data-state]').textContent=result.view?'Opened':'Saved';reviewButton.textContent='✓ Applied';dismiss.disabled=true;o.saved?.(proposal,result);try{await o.refresh?.(proposal.operation)}catch{card.querySelector('[data-error]').textContent='Saved successfully. Refresh the page to update other views.'}if(result.view)g.showView(result.view)}catch(err){reviewButton.disabled=false;card.querySelector('[data-error]').textContent=err.message}};o.chat.append(card);
  }
  async function browse(){try{const c=await capabilities(),{host,form}=showDialog('What your assistant can do',`<p>Ask naturally. Every data change requires your confirmation. Lists shared with the local AI are limited to recent, visible records.</p><label>Find a capability<input id="assistantCapabilitySearch" placeholder="Try finance, food, notes, project…"></label><div class="assistant-capabilities">${Object.entries(c.operations).map(([op,m])=>`<article data-capability="${E(op+' '+m.description)}"><b>${E(moduleNames[m.module])} · ${E(label(m.action))}</b><p>${E(m.description)}</p><small>${E(m.risk)} action · ${E(op)}</small></article>`).join('')}</div><p class="assistant-review-warning">${E(c.manual)}</p><button type="button" data-close class="btn secondary">Close</button>`);form.onsubmit=e=>e.preventDefault();form.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>host.replaceChildren());form.onkeydown=e=>{if(e.key==='Escape'){e.stopPropagation();host.replaceChildren()}};form.querySelector('input').oninput=e=>form.querySelectorAll('[data-capability]').forEach(a=>a.hidden=!a.dataset.capability.toLowerCase().includes(e.target.value.toLowerCase()));form.querySelector('input').focus()}catch(err){o.error(err.message)}}
  return {append,browse};
 }
 g.AssistantActions={create};
})(window);
