/* Local chat client. All proposed writes pass through an editable review. */
(function(global){
 'use strict';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 const icons={plus:'M12 5v14M5 12h14',send:'m12 19 0-14m-6 6 6-6 6 6',image:'M3 3h18v18H3Zm0 13 6-6 6 7 3-3 3 3M16 7h.01',spark:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z',calendar:'M5 3v4m14-4v4M3 10h18M4 5h16v16H4Zm4 9h1m3 0h1m3 0h1',note:'M5 3h10l4 4v14H5Zm9 0v5h5M8 12h8m-8 4h6',close:'m6 6 12 12M6 18 18 6',stop:'M6 6h12v12H6Z'};
 const icon=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[n]||icons.spark}"/></svg>`;
 const MAX_IMAGE=12*1024*1024;
 function validateImage(file){if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('Please attach a PNG, JPG or WebP image.');if(file.size>MAX_IMAGE)throw Error('This image is too large. Please choose one under 12 MB.');}
 async function readStream(response,onProgress=()=>{}){
   if(!response.ok){const data=await response.json().catch(()=>({}));throw Error(data.error||(response.status===404?'Restart the portal server to load the updated chat.':'The portal could not start this request.'))}
   const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',result=null;
   const consume=line=>{if(!line.trim())return;const event=JSON.parse(line);if(event.type==='error')throw Error(event.error);if(event.type==='progress')onProgress(event);if(event.type==='result')result=event};
   try{while(true){const part=await reader.read();if(part.done)break;buffer+=decoder.decode(part.value,{stream:true});let end;while((end=buffer.indexOf('\n'))>=0){consume(buffer.slice(0,end));buffer=buffer.slice(end+1)}}buffer+=decoder.decode();if(buffer.trim())consume(buffer);if(!result)throw Error('The connection ended before the answer finished. Your draft is kept for retry.');return result}finally{reader.releaseLock()}
 }
 function create(options){
   const root=document.getElementById('view-tutor');
   let messages=[],imageData=null,imageFile=null,busy=false,reading=false,attachmentVersion=0,controller=null,checking=false,noteContext=null;
   const prompts=[['spark','Track my spending','I received work pay, paid rent and bought groceries. Help me record them in Finance. Ask for the amounts if needed.'],['spark','Log my meal','Help me log breakfast in Gym nutrition. Ask for the nutrients I have not provided.'],['calendar','Plan my week','Help me plan study sessions around my classes this week. Ask me about my priorities first.'],['note','Add a deadline','Remind me to submit my assignment tomorrow at 5 PM.'],['image','Read a timetable','Fill my timetable from this picture. Flag anything you cannot read clearly.'],['spark','Make study notes','Create a study note explaining a topic. Ask me which topic and level first.']];
   root.innerHTML=`<div class="tutor-shell"><header class="chat-header"><div class="chat-brand"><span class="chat-logo">${icon('spark')}</span><div><h2>Study assistant</h2><p>Your whole portal, in one conversation.</p></div></div><div class="chat-header-actions"><button id="tutorStatus" class="chat-status" type="button">Checking Ollama…</button><button id="tutorCapabilities" class="chat-new" type="button">Capabilities</button><button id="tutorNew" class="chat-new" type="button">${icon('plus')} New chat</button></div></header><div id="tutorChat" class="tutor-chat" role="log" aria-label="Conversation"><div class="chat-welcome"><span class="welcome-spark">${icon('spark')}</span><span class="chat-eyebrow">YOUR LOCAL STUDY COMPANION</span><h3>A little help. A clearer head.</h3><p>Plan your studies, track money and meals, manage projects,<br>and review changes across your portal.</p><div class="chat-starters">${prompts.map(([n,title,prompt],i)=>`<button data-prompt="${i}">${icon(n)}<b>${title}</b><span>${i===0?'Make time for what matters':i===1?'Never miss a submission':i===2?'Attach a screenshot to get started':'Break a topic into clear steps'}</span></button>`).join('')}</div><small>Local AI · You review every change before it is saved.</small></div></div><div class="chat-composer-wrap"><div id="tutorImagePreview" class="chat-attachment" hidden></div><form id="tutorComposer" class="chat-composer"><label class="sr-only" for="tutorInput">Message your study assistant</label><textarea id="tutorInput" rows="3" maxlength="16000" placeholder="Tell me what to organise, record, change or find…"></textarea><div class="composer-toolbar"><div><button id="tutorAttach" type="button" class="chat-attach">${icon('plus')} Attach image</button><input id="tutorImage" type="file" accept="image/png,image/jpeg,image/webp" hidden><span class="composer-types">PNG, JPG, WebP</span></div><button id="tutorSend" type="submit" class="chat-send" aria-label="Send message" disabled>${icon('send')}</button><button id="tutorStop" type="button" class="chat-send" aria-label="Stop waiting for response" hidden>${icon('stop')}</button></div></form><p id="tutorComposerError" class="chat-error" role="alert"></p><div class="composer-footer"><span>AI can make mistakes. Check dates and details before saving.</span><span class="keyboard-hint">Enter to send · Shift + Enter for a new line</span></div><p id="tutorLive" class="sr-only" role="status" aria-live="polite"></p></div></div>`;
   const $=id=>document.getElementById(id),chat=$('tutorChat'),input=$('tutorInput'),send=$('tutorSend'),fileInput=$('tutorImage'),preview=$('tutorImagePreview'),error=$('tutorComposerError');
   const appActions=AssistantActions.create({chat,error:message=>error.textContent=message,beforeSave:options.beforeSave,refresh:options.refreshActions,saved:(proposal,result)=>{const message='Applied '+proposal.operation+'. '+(result.id?'Saved record ID: '+result.id:'')+(result.ids?' Saved IDs: '+JSON.stringify(result.ids):'');add('assistant',message);messages.push({role:'assistant',content:message})}});
   $('tutorCapabilities').onclick=()=>appActions.browse();
   const nearBottom=()=>chat.scrollHeight-chat.scrollTop-chat.clientHeight<100;
   const scroll=()=>{chat.scrollTop=chat.scrollHeight};
   function resize(){input.style.height='auto';input.style.height=Math.min(210,Math.max(82,input.scrollHeight))+'px'}
   function controls(){send.disabled=busy||reading||(!input.value.trim()&&!imageData);send.hidden=busy;$('tutorStop').hidden=!busy;input.disabled=busy;fileInput.disabled=busy;$('tutorAttach').disabled=busy||reading;$('tutorNew').disabled=busy;preview.querySelector('button')?.toggleAttribute('disabled',busy);}
   function clearAttachment(){attachmentVersion++;imageData=null;imageFile=null;reading=false;fileInput.value='';preview.hidden=true;preview.replaceChildren();controls()}
   async function attach(file){
     if(!file||busy)return;error.textContent='';
     try{validateImage(file)}catch(err){error.textContent=err.message;fileInput.value='';return}
     const version=++attachmentVersion;reading=true;controls();
     try{const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('Could not read this image. Please try again.'));reader.readAsDataURL(file)});if(version!==attachmentVersion)return;
       imageData=data;imageFile=file;preview.innerHTML=`<img src="${data}" alt="Attached image preview"><div><b>${esc(file.name)}</b><small>${Math.max(1,Math.round(file.size/1024))} KB · Image attached</small></div><button type="button" aria-label="Remove attached image">${icon('close')}</button>`;preview.hidden=false;preview.querySelector('button').onclick=clearAttachment;
     }catch(err){error.textContent=err.message}finally{if(version===attachmentVersion){reading=false;controls()}}
   }
   function add(role,text,image=null){
     chat.querySelector('.chat-welcome')?.remove();
     const row=document.createElement('article');row.className='chat-message '+role;
     row.innerHTML=`<div class="message-avatar">${role==='assistant'?icon('spark'):'You'}</div><div class="message-body"><div class="message-label">${role==='assistant'?'Study assistant':'You'}</div><div class="message-text"></div></div>`;
     row.querySelector('.message-text').textContent=text;
     if(image){const img=document.createElement('img');img.src=image;img.alt='Image attached to your message';img.className='message-image';row.querySelector('.message-body').prepend(img)}
     chat.append(row);scroll();return row;
   }
   function notesReview(notes){
     const modal=document.getElementById('modalRoot');return new Promise(resolve=>{
       const ids=notes.map(()=>global.crypto?.randomUUID?.()||'note_'+Date.now()+Math.random());
       modal.innerHTML=`<div class="modal-backdrop"><form class="modal wide calendar-form" role="dialog" aria-modal="true" aria-label="Review study notes"><div class="modal-head"><h2>Review study notes</h2><button class="modal-close" type="button" aria-label="Close">×</button></div><p>Review and edit these notes. Nothing is saved until you confirm.</p>${notes.map((n,i)=>`<fieldset data-note="${i}"><legend>Note ${i+1}</legend><label class="form-row">Title<input name="title" required value="${esc(n.title)}"></label><label class="form-row">Content<textarea name="content" rows="8" required>${esc(n.content)}</textarea></label><label class="form-row">Subject<select name="subject_id" required><option value="">Choose a subject (required)</option>${options.subjects().map(s=>`<option value="${esc(s.id)}" ${(s.name.toLowerCase()===String(n.subject||'').toLowerCase()||(!n.subject&&s.id===options.currentSubject?.()))?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label><label class="form-row">Week (required for subject notes)<input name="week" type="number" min="1" max="100" required placeholder="Choose week"></label></fieldset>`).join('')}<p class="calendar-error" role="alert"></p><div class="modal-actions"><button type="button" data-cancel class="btn secondary">Cancel</button><button class="btn primary" type="submit">Confirm & save notes</button></div></form></div>`;
       const form=modal.querySelector('form');let saving=false;
       const close=value=>{if(saving)return;modal.replaceChildren();input.focus();resolve(value)};
       form.querySelectorAll('.modal-close,[data-cancel]').forEach(b=>b.onclick=()=>close(false));
       form.onkeydown=ev=>{if(ev.key==='Escape'){ev.preventDefault();ev.stopPropagation();close(false)}if(ev.key==='Tab'){const els=[...form.querySelectorAll('button,input,textarea,select')].filter(e=>!e.disabled);if(ev.shiftKey&&document.activeElement===els[0]){ev.preventDefault();els.at(-1).focus()}else if(!ev.shiftKey&&document.activeElement===els.at(-1)){ev.preventDefault();els[0].focus()}}};
       form.onsubmit=async ev=>{ev.preventDefault();if(saving)return;saving=true;form.querySelectorAll('button').forEach(b=>b.disabled=true);try{const drafts=[...form.querySelectorAll('[data-note]')].map((row,i)=>({id:ids[i],title:row.querySelector('[name=title]').value,content:row.querySelector('[name=content]').value,subject_id:row.querySelector('[name=subject_id]').value||null,week:row.querySelector('[name=week]').value}));await options.saveNotes(drafts);saving=false;close(true)}catch(err){form.querySelector('[role=alert]').textContent=err.message;saving=false;form.querySelectorAll('button').forEach(b=>b.disabled=false)}};
       form.querySelector('input').focus();
     });
   }
   function actions(items){
     const valid=items.filter(a=>a&&(['reminders_create','timetable_import','notes_create','app_action'].includes(a.type)));
     valid.forEach(action=>{
       if(action.type==='app_action'){appActions.append(action);return}
       const reminder=action.type==='reminders_create',note=action.type==='notes_create',drafts=reminder?action.reminders:note?action.notes:action.events;
       if(!Array.isArray(drafts)||!drafts.length)return;
       const card=document.createElement('section');card.className='chat-proposal';
       const title=reminder?'Reminder proposal':note?'Study notes proposal':'Timetable proposal';
       card.innerHTML=`<div class="proposal-heading">${icon(note?'note':'calendar')}<b>${title}</b><span>Not saved yet</span></div><ul>${drafts.slice(0,5).map(x=>`<li><b>${esc(x.title||'Untitled')}</b><span>${esc(note?(x.content||'').slice(0,100):reminder?[x.due_date,x.due_time||'All day',x.recurrence==='weekly'?'Weekly until '+(x.repeat_until||'choose a date'):''].filter(Boolean).join(' · '):[x.event_date||['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][x.day]||'Choose a date',x.start_time,x.end_time].filter(Boolean).join(' · '))}</span></li>`).join('')}</ul>${drafts.length>5?`<small>And ${drafts.length-5} more to review</small>`:''}<p>Check the details, make any changes, then confirm.</p><button class="proposal-review" type="button">${reminder?'Review reminders':note?'Review notes':'Review timetable'} →</button>`;
       const button=card.querySelector('button');button.onclick=async()=>{button.disabled=true;try{const saved=reminder?await options.reminders.review(drafts):note?await notesReview(drafts):await options.calendar.importEvents(drafts);if(saved){card.classList.add('saved');card.querySelector('.proposal-heading span').textContent='Saved';button.textContent='✓ Saved';const message=note?'Your study notes have been saved.':reminder?'Reminders saved. Dated reminders appear in red on your calendar.':'Your calendar events have been saved.';add('assistant',message);messages.push({role:'assistant',content:message})}else button.disabled=false}catch(err){button.disabled=false;add('assistant',err.message)}};
       chat.append(card);if(reminder&&valid.length===1)setTimeout(()=>button.click(),0);
     });scroll();
   }
   async function status(){if(checking)return;checking=true;const badge=$('tutorStatus');try{const r=await fetch('/api/ai/status',{cache:'no-store'});if(!r.ok)throw Error();const x=await r.json(),ok=x.online&&x.model_available;badge.className='chat-status '+(ok?'online':'offline');badge.textContent=ok?'● '+(busy||x.busy?'Working':x.last_response_at?'Response tested':'Connected')+' · '+x.model:'● Ollama unavailable';badge.title=(ok?'Ollama is reachable and the model is installed.':x.error||'Open Ollama on the host PC.')+' Click to recheck.'}catch{badge.className='chat-status offline';badge.textContent='● Portal unavailable';badge.title='Check the portal server. Click to recheck.'}finally{checking=false}}
   async function submit(ev){
     ev?.preventDefault();if(busy||reading||(!input.value.trim()&&!imageData))return;
     const text=input.value.trim()||'Please describe this image and how you can help me with it.',attachment=imageData,attachedFile=imageFile;
     busy=true;controls();error.textContent='';controller=new AbortController();
     const user={role:'user',content:text},requestMessages=[...messages,user];add('user',text,attachment);const responseRow=add('assistant','Getting ready…'),body=responseRow.querySelector('.message-text');responseRow.classList.add('is-thinking');
     const outcome=document.createElement('p');outcome.className='chat-action-status';outcome.setAttribute('role','status');outcome.textContent='Working · Nothing saved yet';responseRow.querySelector('.message-body').append(outcome);
     const started=Date.now();let generated=0;
     const progress=()=>{const follow=nearBottom(),seconds=Math.floor((Date.now()-started)/1000);body.textContent=(generated?'Preparing your response':'Reading your '+(attachment?'image':'message'))+' · '+seconds+'s'+(seconds>30?'\nLocal AI can take a few minutes. You can stop waiting without saving anything.':'');if(follow)scroll()};
     const timer=setInterval(progress,1000);status();$('tutorLive').textContent='The assistant is working.';
     try{const response=await fetch('/api/ai/chat/stream',{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({messages:requestMessages,image:attachment,context:{...options.context(),...(noteContext?{study_note:noteContext}:{})}})});const result=await readStream(response,event=>{generated=event.characters||0;if(event.stage==='repairing_actions')outcome.textContent='Generating missing action drafts · Automatic retry (1 of 1) · Nothing saved';progress()});body.textContent=result.reply;messages=[...requestMessages,{role:'assistant',content:result.reply+(result.actions?.length?'\nProposed drafts (not yet saved): '+JSON.stringify(result.actions).slice(0,10000):'')}];
       const state=result.action_status||(result.actions?.length?'review_ready':'answer_only');
       outcome.dataset.state=state;outcome.textContent={review_ready:'Ready to review · Use the review buttons below · Nothing saved yet',needs_input:'Needs your input · Reply with the missing details · Nothing saved',missing_actions:'No actions generated · Nothing saved · Not working in the background',answer_only:'Response complete · No changes made'}[state]||'Response complete · No changes made';
       if(state==='missing_actions'){
         // Keep the original request and image ready to retry without reconstructing them.
         const retry=document.createElement('button');retry.type='button';retry.className='proposal-review';retry.textContent='Retry generating drafts';retry.onclick=async()=>{if(busy||reading)return;input.value=text;clearAttachment();if(attachedFile)await attach(attachedFile);resize();controls();submit()};outcome.append(document.createElement('br'),retry);
       }else{input.value='';clearAttachment()}
       resize();actions(result.actions||[]);if(result.action_issues?.length)add('assistant','Some requested actions could not be prepared: '+result.action_issues.join(' ')+' No changes were made for those actions.');$('tutorLive').textContent=outcome.textContent;
     }catch(err){responseRow.classList.add('message-error');body.textContent=err.name==='AbortError'?'Stopped waiting. Nothing was saved. Your draft is kept below. Ollama may need a moment to finish stopping.':err.message+'\nNothing was saved. Your draft and image are kept below—send again to retry.';$('tutorLive').textContent='Request stopped. Your draft is kept.';
     }finally{if(responseRow.classList.contains('message-error')){outcome.dataset.state='missing_actions';outcome.textContent='Request stopped · Nothing saved · Your draft is kept for retry'}clearInterval(timer);responseRow.classList.remove('is-thinking');busy=false;controller=null;controls();status();scroll();if(!document.querySelector('#modalRoot form'))input.focus()}
   }
   $('tutorComposer').onsubmit=submit;$('tutorStop').onclick=()=>controller?.abort();
   input.oninput=()=>{resize();controls()};input.onkeydown=ev=>{if(ev.key==='Enter'&&!ev.shiftKey&&!ev.isComposing){ev.preventDefault();submit()}};
   $('tutorAttach').onclick=()=>fileInput.click();fileInput.onchange=()=>attach(fileInput.files[0]);
   input.addEventListener('paste',ev=>{const file=[...ev.clipboardData.items].find(i=>i.kind==='file')?.getAsFile();if(file){ev.preventDefault();attach(file)}});
   root.addEventListener('dragover',ev=>{if(ev.dataTransfer.types.includes('Files')){ev.preventDefault();root.classList.add('is-dragging')}});root.addEventListener('dragleave',ev=>{if(!root.contains(ev.relatedTarget))root.classList.remove('is-dragging')});root.addEventListener('drop',ev=>{ev.preventDefault();root.classList.remove('is-dragging');if(ev.dataTransfer.files.length>1){error.textContent='Attach one image at a time.';return}attach(ev.dataTransfer.files[0])});
   root.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{input.value=prompts[+b.dataset.prompt][2];resize();controls();input.focus();if(+b.dataset.prompt===2)fileInput.click()});
   $('tutorStatus').onclick=status;$('tutorNew').onclick=()=>{if((messages.length||input.value||imageData)&&!confirm('Start a new chat? This clears this conversation and draft, but does not delete saved reminders, events or notes.'))return;messages=[];noteContext=null;$('tutorNoteContext')?.remove();chat.replaceChildren();add('assistant','What would you like to work on? I can help with reminders, deadlines, calendar events, study notes, and explaining topics.');input.value='';clearAttachment();resize();input.focus()};
   status();setInterval(()=>{if(!document.hidden&&root.classList.contains('active'))status()},15000);resize();controls();
   return {attach,setNoteContext(context){if(busy){alert('Wait for the current AI response before opening another note.');return}if(input.value&&!confirm('Replace your current chat draft with a question about this note?'))return;noteContext=context;let chip=$('tutorNoteContext');if(!chip){chip=document.createElement('div');chip.id='tutorNoteContext';chip.className='chat-note-context';document.querySelector('.chat-composer-wrap').prepend(chip)}chip.innerHTML=`<div><b>▤ ${esc(context.subject)} · ${esc(context.title)}</b><small>${esc(context.topic||'No topic')} · Note content included with your next questions</small></div><button type="button" aria-label="Remove note context">×</button>`;chip.querySelector('button').onclick=()=>{noteContext=null;chip.remove()};input.value='Help me understand this note: ';resize();controls();input.focus()}};
 }
 global.StudentTutor={create,readStream,validateImage};
})(typeof window==='undefined'?globalThis:window);
