/* Optional social workspace. All data and permissions come from the shared API. */
(function(g){'use strict';
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pages={home:'Home',messages:'Messages',people:'Find People',clubs:'Clubs',groups:'Study Groups',projects:'Projects & Assignments',events:'Events'};
const B=(l,a,id='',cls='')=>`<button type="button" class="soc-button ${cls}" data-social="${a}" data-id="${E(id)}">${l}</button>`;
const F=(label,name,value='',type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${E(value)}" ${extra}></label>`;
const T=(label,name,value='')=>`<label>${label}<textarea name="${name}" rows="3">${E(value)}</textarea></label>`;
const S=(label,name,options,value='')=>`<label>${label}<select name="${name}">${options.map(x=>{const [v,l]=Array.isArray(x)?x:[x,x];return `<option value="${E(v)}" ${String(v)===String(value)?'selected':''}>${E(l)}</option>`}).join('')}</select></label>`;
const C=(label,name,on)=>`<label class="soc-check"><input name="${name}" type="checkbox" ${on?'checked':''}>${label}</label>`;
const card=(title,body,action='',cls='')=>`<section class="soc-card ${cls}"><header><h3>${title}</h3>${action}</header>${body}</section>`;
const empty=(title,body='',action='')=>`<div class="soc-empty"><span aria-hidden="true">✧</span><h3>${title}</h3><p>${body}</p>${action}</div>`;
const when=d=>d?new Date(d).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'}):'No date set';
const avatars={graduate:'🎓',owl:'🦉',fox:'🦊',cat:'🐱',panda:'🐼',robot:'🤖',astronaut:'🧑‍🚀',leaf:'🌱'};
function create(o){
 let data=null,page='home',selected='',conversation='',tab='overview',feed='all',search='',sameUni=false,subject='',projectFilter='all',expanded=localStorage.getItem('portal.socialExpanded')!=='false',busy=false,dirty=false,notice='';
 const dialog=document.createElement('dialog');dialog.className='soc-dialog';document.body.append(dialog);dialog.oninput=()=>dirty=true;dialog.addEventListener('cancel',ev=>{if(dirty&&!confirm('Discard unsaved Socialise changes?'))ev.preventDefault();else dirty=false});
 for(const p in pages){const el=document.createElement('section');el.id='view-social-'+p;el.className='view social-view';document.querySelector('.main').append(el)}
 const root=()=>document.getElementById('view-social-'+page),me=()=>data?.me?.id,profile=()=>data?.profile||{},rooms=()=>data?.spaces||[],people=()=>data?.people||[],user=id=>[data?.me,...(data?.users||[]),...people()].find(x=>x?.id===id)||{id,name:'Member',avatar:'graduate'};
 const avatar=u=>`<span class="soc-avatar">${u.photo&&/^data:image\/(jpeg|png|webp);base64,/.test(u.photo)?`<img src="${E(u.photo)}" alt="">`:E(avatars[u.avatar]||u.name?.slice(0,2).toUpperCase()||'S')}</span>`;
 const link=v=>(data?.links||[]).find(x=>x.sender===v||x.recipient===v),isFriend=v=>link(v)?.state==='accepted';
 const go=p=>o.show('social-'+p);
 async function api(url='/api/social',payload){const r=await fetch(url,payload?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}:{}),j=await r.json();if(!r.ok)throw Error(j.error||'Unable to load Socialise.');return j}
 async function refresh(){data=await api();nav();settings()}
 async function write(action,values={},id){if(busy)throw Error('Please wait for your current save.');busy=true;try{const result=await api('/api/social',{action,data:values,id});await refresh();return result}finally{busy=false}}
 function feedback(s){notice=s;document.querySelectorAll('[data-social-status]').forEach(n=>n.textContent=s)}
 function close(){if(dirty&&!confirm('Discard unsaved changes?'))return;dirty=false;dialog.close()}
 function modal(title,body,save){dirty=false;dialog.innerHTML=`<header><h2>${E(title)}</h2>${B('×','close','','soc-close')}</header><form>${body}<p role="alert" class="soc-error"></p><footer>${save?'<button class="soc-button soc-primary" type="submit">Save</button>':''}${B('Close','close')}</footer></form>`;bind(dialog);dialog.querySelector('form').onsubmit=async ev=>{ev.preventDefault();if(!save||busy)return;const b=ev.submitter||ev.target.querySelector('[type=submit]');b.disabled=true;try{await save(Object.fromEntries(new FormData(ev.target)),ev.target);dirty=false;dialog.close();render()}catch(e){dialog.querySelector('.soc-error').textContent=e.message}finally{b.disabled=false}};if(!dialog.open)dialog.showModal()}
 function nav(){let n=document.getElementById('socialNav');if(!n){n=document.createElement('div');n.id='socialNav';n.className='social-nav';document.querySelector('.nav [data-view=tutor]').before(n)}n.hidden=!profile().enabled;n.innerHTML=`<button id="socialToggle" aria-expanded="${expanded}" aria-controls="socialSubnav"><span>♧</span><span>Socialise</span><span class="soc-chevron">${expanded?'⌃':'›'}</span></button><div id="socialSubnav" ${expanded?'':'hidden'}>${Object.entries(pages).map(([k,v])=>`<button data-view="social-${k}" class="${document.getElementById('view-social-'+k).classList.contains('active')?'active':''}">• &nbsp; ${v}</button>`).join('')}</div>`;n.querySelector('#socialToggle').onclick=()=>{expanded=!expanded;localStorage.setItem('portal.socialExpanded',expanded);nav()};n.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>o.show(b.dataset.view))}
 function settings(){const host=document.getElementById('portalSettings');if(!host)return;host.querySelector('.social-settings')?.remove();const el=document.createElement('section');el.className='gym-card social-settings';const p=profile();el.innerHTML=`<h3>Modules / Features</h3><div class="gym-module-row"><div><h4>Socialise</h4><p>Connect with classmates, join clubs, create study groups and manage group projects.</p></div><label class="gym-switch"><input id="socialEnabled" type="checkbox" ${p.enabled?'checked':''} ${!data?'disabled':''}><span>${p.enabled?'Enabled':'Enable Socialise'}</span></label></div><p>Disabling hides Socialise without deleting your connections, messages or projects. Other students must use this same portal server.</p>${data?B('Social profile & privacy','privacy'):B('Retry connection','refresh')}<p data-social-status role="status">${E(notice)}</p>`;host.append(el);el.querySelector('#socialEnabled').onchange=async e=>{e.target.disabled=true;try{await write('profile',{enabled:e.target.checked});feedback('Socialise preference saved.')}catch(err){feedback(err.message);settings()}};bind(el)}
 function privacy(){const p=profile();modal('Your social profile & privacy',`<p>Your name and avatar come from your account profile. Nothing from your private notes, quiz results, Finance or Gym is shared.</p>${F('University (self-declared, not email-inferred)','university',p.university)}${F('Degree / program','degree',p.degree)}${F('Year level','year',p.year)}${T('Bio','bio',p.bio)}${F('Interests','interests',p.interests)}${F('Subjects to publish (comma-separated labels)','subjects',(p.subjects||[]).join(', '))}<small>Choose only subjects you intend to share. Your private enrolments are never copied automatically.</small><div class="soc-form-grid">${C('Discoverable in People Search','discoverable',p.discoverable)}${C('Show my university','show_university',p.show_university)}${C('Show my chosen subjects','show_subjects',p.show_subjects)}${C('Allow discovery by my chosen subjects','subject_discovery',p.subject_discovery)}${C('Allow friend requests','friend_requests',p.friend_requests)}${C('Social notifications','notifications',p.notifications)}</div>${S('Allow direct messages from','dm',[['friends','Friends only'],['members','Friends or shared group/project members'],['nobody','Nobody']],p.dm)}<details><summary>Social notification categories</summary>${['friend_request','friend_accepted','message','club','study','project','task','event'].map(k=>C(k.replaceAll('_',' '),'notify_'+k,p['notify_'+k]!==false)).join('')}</details><p>No live presence is broadcast. Social notifications remain separate from academic reminders.</p>${(data.blocks||[]).map(id=>B('Unblock account '+E(id.slice(0,8)),'unblock',id)).join('')}`,async(v,f)=>{for(const x of f.querySelectorAll('[type=checkbox]'))v[x.name]=x.checked;v.subjects=v.subjects.split(',').map(x=>x.trim()).filter(Boolean);await write('profile',v)})}
 function person(u){const l=link(u.id),buttons=l?.state==='accepted'?B('Message','dm',u.id):l?.sender===me()?B('Requested · Cancel','friend-cancel',u.id):l?B('Accept','friend-accept',u.id)+B('Decline','friend-decline',u.id):B('＋ Add','friend-request',u.id);return `<div class="soc-person">${avatar(u)}<button class="soc-person-name" data-social="person" data-id="${E(u.id)}"><b>${E(u.name)}</b><small>${E(u.subjects?.join(' · ')||u.university||u.interests||'Student')}</small></button>${buttons}</div>`}
 function personModal(id){const u=user(id);modal(u.name,`${avatar(u)}<p>${E(u.bio||'No bio shared yet.')}</p><p>${E([u.university,u.degree,u.year].filter(Boolean).join(' · '))}</p><p>${E(u.subjects?.join(' · '))}</p><p>${E(u.interests)}</p>${isFriend(id)?B('Remove friend','friend-remove',id):''}${B('Block account','block',id)}`)}
 function matches(s){return !search||JSON.stringify(s).toLowerCase().includes(search.toLowerCase())}
 function visiblePeople(){return people().filter(u=>matches([u.name,u.university,u.degree,u.year,u.interests,u.subject_discovery?u.subjects:[]])&&(!sameUni||(profile().university&&u.university===profile().university))&&(!subject||(u.subject_discovery&&u.subjects.includes(subject))))}
 function score(u){return (u.university&&u.university===profile().university?2:0)+(u.subject_discovery?(u.subjects||[]).filter(s=>profile().subjects?.includes(s)).length*3:0)}
 function spaceCard(s){return `<article class="soc-space"><div class="soc-space-icon">${E(s.data.icon||({club:'♧',study:'▣',project:'▰',chat:'☏'}[s.kind]||'☏'))}</div><div><h3>${E(s.name)}</h3><p>${E(s.data.subject||s.data.category||s.kind)} · ${s.count} members · ${s.data.private?'Private':'Public'}</p><p>${E(s.data.description||'A space to connect and collaborate.')}</p></div>${s.joined?B('Open','open-space',s.id):s.membership.state==='invited'?B('Accept invitation','member-accept_invite',s.id)+B('Decline','member-leave',s.id):s.membership.state==='requested'?B('Requested · Cancel','member-leave',s.id):B(s.data.private?'Request to join':'Join','member-join',s.id)}</article>`}
 function stats(){const active=rooms().filter(s=>s.joined);return [['Friends',(data.links||[]).filter(l=>l.state==='accepted').length],['Club memberships',active.filter(s=>s.kind==='club').length],['Study groups',active.filter(s=>s.kind==='study').length],['Ongoing projects',active.filter(s=>s.kind==='project'&&s.data.status!=='completed').length],['Events attending',(data.events||[]).filter(e=>e.attending).length]].map(([l,n])=>`<div class="soc-stat-row"><span>${l}</span><b>${n}</b></div>`).join('')}
 function eventCard(e){return `<article class="soc-event"><div class="soc-date">${E(new Date(e.data.start).toLocaleDateString(undefined,{month:'short'}))}<b>${new Date(e.data.start).getDate()}</b></div><div><b>${E(e.title)}</b><small>${E(when(e.data.start))}</small><small>${E(e.data.location||'Location to be confirmed')}</small><span>${e.count} attending</span></div>${B(e.attending?'Attending ✓':'Attend','attend',e.id)}${e.author===me()?B('Edit','edit-event',e.id):''}</article>`}
 function upcoming(){return (data.events||[]).filter(e=>e.data.start>=new Date().toISOString().slice(0,16)).sort((a,b)=>a.data.start.localeCompare(b.data.start))}
 function post(p){return `<article class="soc-card soc-post"><header>${avatar(user(p.author))}<div><b>${E(user(p.author).name)}</b><small>${E(when(p.created_at))} · ${E(p.subject||p.audience)}</small></div>${p.author===me()?B('Delete','delete-post',p.id):''}</header><p class="soc-prose">${E(p.body)}</p><footer>${B((p.liked?'♥':'♡')+' '+p.likes,'like',p.id)}${B('Comment · '+p.comments.length,'comment',p.id)}</footer>${p.comments.length?`<details><summary>Comments</summary>${p.comments.map(c=>`<p><b>${E(user(c.author).name)}</b> ${E(c.body)}</p>`).join('')}</details>`:''}</article>`}
 function feedPosts(){return (data.posts||[]).filter(p=>matches([p.body,p.subject,user(p.author).name])&&(feed==='all'||feed==='friends'&&isFriend(p.author)||feed==='subjects'&&profile().subjects?.includes(p.subject)||feed==='clubs'&&rooms().some(s=>s.id===p.space_id&&s.kind==='club')))}
 function home(){const recommended=people().filter(u=>!link(u.id)).sort((a,b)=>score(b)-score(a)).slice(0,4),clubs=rooms().filter(s=>s.kind==='club'&&!s.joined).slice(0,3);const subjects=[...new Set(people().filter(u=>u.subject_discovery).flatMap(u=>u.subjects||[]))];return `<div class="soc-features">${[['people','♧','Find People','Connect with classmates'],['clubs','♜','Join Clubs','Find your community'],['groups','▣','Study Groups','Learn better together'],['projects','▰','Projects & Assignments','Make group work work']].map(([p,i,t,d])=>`<button data-social="go-${p}"><span>${i}</span><b>${t}</b><small>${d} →</small></button>`).join('')}</div><div class="soc-home-grid"><aside>${card('Recommended Clubs',clubs.map(spaceCard).join('')||empty('Your community starts here','Create a club or check back as students join.',B('Explore Clubs','go-clubs')))}${card('People You May Know',recommended.map(person).join('')||empty('Make your first connection','Publish your profile to help classmates find you.',B('Find People','go-people')))}</aside><div class="soc-feed">${card('Share an update',`<form id="socialPostForm"><textarea name="body" aria-label="Post text" placeholder="What’s on your mind? Share a study update…" required maxlength="5000"></textarea><div class="soc-composer-options">${F('Tag subject','subject')}${S('Audience','audience',[['friends','Friends'],['public','All Socialise users']])}${S('Group (optional)','space_id',[['','No group'],...rooms().filter(s=>s.joined&&s.kind!=='dm').map(s=>[s.id,s.name])])}<button class="soc-button soc-primary" type="submit">Post</button></div></form>`)}<nav class="soc-tabs">${[['all','For You'],['friends','Friends'],['subjects','My Subjects'],['clubs','Clubs']].map(([k,l])=>B(l,'feed-'+k,'',feed===k?'active':'')).join('')}${B('Events','go-events')}</nav>${feedPosts().map(post).join('')||empty('A fresh start for your feed','Updates from people and communities will appear here.')}</div><aside>${card('Upcoming Events',upcoming().slice(0,4).map(eventCard).join('')||empty('No upcoming events','Create a study session or community event.'),B('View all','go-events'))}${card('Quick Stats',stats())}${card('Find People by Subject',subjects.map(s=>B(E(s)+' · '+people().filter(u=>u.subject_discovery&&u.subjects.includes(s)).length,'subject',s)).join('')||'<p>Subjects appear only when students opt in to sharing and discovery.</p>')}</aside></div>`}
 function directory(kind){return `<div class="soc-section-heading"><h2>${kind==='club'?'Find your community':'Learn together'}</h2>${B('＋ Create '+(kind==='club'?'Club':'Study Group'),'new-'+kind)}</div><div class="soc-directory">${rooms().filter(s=>s.kind===kind&&matches([s.name,s.data.subject,s.data.university,s.data.category,s.data.description])).map(spaceCard).join('')||empty('No '+(kind==='club'?'clubs':'study groups')+' yet','Create a welcoming space for classmates.')}</div>`}
 function newSpace(kind,s){modal(s?'Workspace settings':'Create '+(kind==='project'?'project':kind==='study'?'study group':kind),`${F('Name','name',s?.name||'','text','required maxlength="120"')}${T('Description / brief','description',s?.data.description||'')}${F('Subject (optional, explicitly shared label)','subject',s?.data.subject||'')}${F('Topic (optional)','topic',s?.data.topic||'')}${kind==='project'?S('Project type','type',[['assignment','Group Assignment'],['group','Group Project'],['club','Club Project'],['general','General Project']],s?.data.type||'general')+F('Due date','due',s?.data.due||'','datetime-local')+S('Status','status',[['planning','Planning'],['in_progress','In Progress'],['review','Review'],['completed','Completed']],s?.data.status||'planning')+C('Enable task review stage','review',s?.data.review!==false):F('University','university',s?.data.university||profile().university||'')+F('Category','category',s?.data.category||'')+F('Icon / emoji','icon',s?.data.icon||'')+T('Community rules','rules',s?.data.rules||'')+C('Private · approve join requests','private',s?.data.private)}<p>Invite accepted friends from Members after creating the workspace.</p>`,async(v,f)=>{v.kind=kind;v.private=!!f.elements.private?.checked;v.review=f.elements.review?f.elements.review.checked:true;const r=await write('space',v,s?.id);selected=r.id})}
 function memberList(s){return s.members.map(m=>`<div class="soc-member">${avatar(user(m.user_id))}<div><b>${E(user(m.user_id).name)}</b><small>${E(m.role)} · ${E(m.state)}</small></div>${s.owner===me()&&m.user_id!==me()?(m.state==='requested'?B('Approve','approve',m.user_id)+B('Decline','decline',m.user_id):m.state==='active'?B('Role','role',m.user_id)+B('Transfer ownership','transfer',m.user_id)+B('Remove','remove-member',m.user_id):B('Cancel invite','remove-member',m.user_id)):''}</div>`).join('')+ (s.owner===me()?B('＋ Invite friend','invite',s.id):B('Leave workspace','member-leave',s.id))}
 function openSpace(id){const s=rooms().find(x=>x.id===id);selected=id;if(s.kind==='project'){tab='overview';go('projects')}else modal(s.name,`<p>${E(s.data.description)}</p><p>${E(s.data.rules||'')}</p>${B('Open chat','chat',s.id)}${B('Create event','space-event',s.id)}${s.owner===me()?B('Settings','edit-space',s.id):''}<h3>Members</h3>${memberList(s)}`)}
 function nameOf(s){return s.kind==='dm'?s.members.filter(m=>m.user_id!==me()).map(m=>user(m.user_id).name).join(', ')||'Direct conversation':s.name}
 function chatLayout(s){return `<section class="soc-chat"><header><h3>${E(nameOf(s))}</h3>${B('← Conversations','conversations')}</header><div id="socialMessages" role="log" aria-live="polite"><p>Loading messages…</p></div><form id="socialMessageForm"><textarea name="body" aria-label="Message" placeholder="Write a message…" required maxlength="5000"></textarea><button class="soc-button soc-primary" type="submit">Send</button></form></section>`}
 async function loadMessages(){const host=document.getElementById('socialMessages');if(!host||!conversation||!profile().enabled)return;const s=conversation;try{const r=await api('/api/social/messages?space='+encodeURIComponent(s));if(s!==conversation||!host.isConnected)return;const near=host.scrollHeight-host.scrollTop-host.clientHeight<70;const html=r.messages.map(m=>`<article class="soc-message ${m.author===me()?'mine':''}"><b>${E(user(m.author).name)}</b><p>${E(m.body)}</p><small>${E(when(m.created_at))}</small>${m.author===me()?B('Delete','delete-message',m.id):''}</article>`).join('')||empty('Start a conversation','Messages are visible only to current members.');if(host.innerHTML!==html){host.innerHTML=html;bind(host);if(near)host.scrollTop=host.scrollHeight}}catch(e){host.innerHTML=`<p role="alert">${E(e.message)}</p>`}}
 function messages(){const list=rooms().filter(s=>s.joined&&matches(nameOf(s)));const selectedRoom=rooms().find(s=>s.id===conversation&&s.joined);return `<div class="soc-message-layout ${selectedRoom?'chat-selected':''}"><aside>${card('Conversations',list.map(s=>B(E(nameOf(s))+((data.notifications||[]).some(n=>n.kind==='message'&&!n.read&&n.target===s.id)?' · New':''),'chat',s.id,s.id===conversation?'active':'')).join('')||empty('No conversations','Message a friend or create a group.'),B('＋ Group','new-chat'))}</aside>${selectedRoom?chatLayout(selectedRoom):empty('Stay in touch','Select a conversation. Direct messages respect the recipient’s privacy settings.',B('Find People','go-people'))}</div>`}
 const progress=s=>s.tasks.length?Math.round(s.tasks.filter(t=>t.data.status==='done').length/s.tasks.length*100):0;
 const overdue=t=>t.data.status!=='done'&&t.data.due&&new Date(t.data.due)<new Date();
 function taskCard(t){return `<article class="soc-task ${overdue(t)?'overdue':''}"><button class="soc-task-title" data-social="edit-task" data-id="${t.id}">${E(t.title)}</button><p>${t.data.checklist.filter(x=>x.done).length} / ${t.data.checklist.length} checklist items</p><small>${E(t.data.assigned.map(v=>user(v).name).join(', ')||'Unassigned')}</small><small>${E(t.data.due?when(t.data.due):'No due date')} ${overdue(t)?'· Overdue':''}</small><span class="soc-priority ${t.data.priority}">${E(t.data.priority)}</span><select aria-label="Status for ${E(t.title)}" data-task-status="${t.id}">${[['todo','To Do'],['in_progress','In Progress'],['review','Review'],['done','Done']].map(([v,l])=>`<option value="${v}" ${t.data.status===v?'selected':''}>${l}</option>`).join('')}</select></article>`}
 function board(s){return `<div class="soc-board">${[['todo','To Do'],['in_progress','In Progress'],['review','Review'],['done','Done']].filter(([k])=>k!=='review'||s.data.review!==false).map(([k,l])=>`<section class="soc-lane"><h4><i class="${k}"></i>${l} <small>${s.tasks.filter(t=>t.data.status===k).length}</small></h4>${s.tasks.filter(t=>t.data.status===k&&(projectFilter!=='mine'||t.data.assigned.includes(me()))).map(taskCard).join('')}</section>`).join('')}</div>`}
 function projects(){const all=rooms().filter(s=>s.kind==='project'),filtered=all.filter(s=>matches([s.name,s.data.subject,s.data.description])&&(projectFilter!=='owned'||s.owner===me())&&(projectFilter!=='completed'||s.data.status==='completed'));let s=all.find(s=>s.id===selected&&s.joined)||filtered.find(s=>s.joined);if(s)selected=s.id;const summary=[['Active Projects',all.filter(s=>s.joined&&s.data.status!=='completed').length],['Tasks Completed',all.flatMap(s=>s.tasks).filter(t=>t.data.status==='done').length],['My Active Tasks',all.flatMap(s=>s.tasks).filter(t=>t.data.assigned.includes(me())&&t.data.status!=='done').length],['Team Members',new Set(all.flatMap(s=>s.members.filter(m=>m.state==='active').map(m=>m.user_id))).size]];return `<div class="soc-project-stats">${summary.map(([l,n])=>card(l,`<strong>${n}</strong>`)).join('')}</div>${projectFilter==='mine'?card('My Tasks · across all projects',all.flatMap(p=>p.tasks.filter(t=>t.data.assigned.includes(me())).map(t=>`<div class="soc-my-task"><small>${E(p.name)}</small>${taskCard(t)}</div>`)).join('')||'<p>No tasks assigned to you yet.</p>'):''}<div class="soc-project-layout"><aside>${card('My Projects',S('Filter','projectFilter',[['all','All projects'],['mine','My Tasks'],['owned','Projects I Own'],['completed','Completed']],projectFilter)+filtered.map(v=>v.joined?`<button class="soc-project-choice ${v.id===s?.id?'active':''}" data-social="project" data-id="${v.id}"><b>${E(v.name)}</b><small>${E(v.data.subject||v.data.type)} · ${E(v.data.status.replaceAll('_',' '))}</small><progress value="${progress(v)}" max="100"></progress><span>${progress(v)}%</span></button>`:spaceCard(v)).join(''),B('＋ New Project','new-project'))}</aside>${s?projectDetail(s):empty('No group projects yet','Create a project or accept an invitation.',B('＋ New Project','new-project'))}${s?projectAside(s):''}</div>`}
 function projectDetail(s){const tabs=['overview','tasks','files','chat','members','settings'];let body='';if(tab==='chat'){conversation=s.id;body=chatLayout(s)}else if(tab==='members')body=memberList(s);else if(tab==='settings')body=s.owner===me()?`<p>Only the owner can change workspace settings or transfer ownership.</p>${B('Edit project','edit-space',s.id)}${memberList(s)}`:'Only the project owner can change these settings.';else if(tab==='files')body=`<p>Private to current members. Downloads are attachments, never executed inline. 2 MB per file; 50 MB per project.</p>${B('＋ Upload file','upload',s.id)}${s.files.map(f=>`<div class="soc-file"><a href="/api/social/files/${f.id}">${E(f.name)}</a><small>${E(user(f.author).name)} · ${E(when(f.created_at))}</small><p>${E(f.description)}</p></div>`).join('')||empty('No files yet','Share project materials explicitly.')}`;else body=`${tab==='overview'?`<div class="soc-project-overview">${card('Project Details',`<p>${E(s.data.subject||'General project')}</p><b>Due ${E(when(s.data.due))}</b><p class="soc-prose">${E(s.data.description||'Add your project brief in Settings.')}</p>`)}${card('Overall Progress',`<strong>${progress(s)}%</strong><progress value="${progress(s)}" max="100"></progress><p>${s.tasks.filter(t=>t.data.status==='done').length} / ${s.tasks.length} tasks completed. Equal task weighting.</p>${s.members.filter(m=>m.state==='active').map(m=>avatar(user(m.user_id))).join('')}`)}</div>`:''}<div class="soc-section-heading"><h3>Task Board</h3>${B('＋ Add Task','new-task',s.id)}</div>${board(s)}${tab==='overview'?`<div class="soc-project-overview">${card('Recorded Activity Contribution',contributions(s))}${card('Recent Activity',s.activity.slice(0,10).map(a=>`<p><b>${E(user(a.actor).name)}</b> ${E(a.body)}<small>${E(when(a.created_at))}</small></p>`).join('')||'<p>No recorded project activity yet.</p>')}</div>`:''}`;return `<section class="soc-card soc-project-detail"><header><div><h2>${E(s.name)}</h2><p>${E(s.data.subject||'General project')} · ${E(s.data.status.replaceAll('_',' '))}</p></div></header><nav class="soc-tabs">${tabs.map(t=>B(t[0].toUpperCase()+t.slice(1),'tab-'+t,'',tab===t?'active':'')).join('')}</nav>${body}</section>`}
 function contributions(s){const total=(s.contributions||[]).reduce((n,c)=>n+c.actions,0);return (s.contributions||[]).map(c=>`<button class="soc-contribution" data-social="contribution" data-id="${c.actor}">${E(user(c.actor).name)}<progress value="${c.actions}" max="${total||1}"></progress><b>${Math.round(c.actions/(total||1)*100)}%</b></button>`).join('')+`<small>Share of recorded task changes and file uploads (one point per recorded action). Messages do not count. Not a measure of effort or an academic grade; work outside the app is not captured.</small>`}
 function projectAside(s){const events=(data.events||[]).filter(e=>e.space_id===s.id).sort((a,b)=>a.data.start.localeCompare(b.data.start)),meetings=events.filter(e=>e.data.kind==='meeting'&&new Date(e.data.start)>=new Date());return `<aside>${card('Upcoming Milestones',events.filter(e=>e.data.kind==='milestone'&&new Date(e.data.start)>=new Date()).map(eventCard).join('')||'<p>No milestones yet.</p>',B('＋ Add','space-milestone',s.id))}${card('Next Meeting',meetings.slice(0,1).map(e=>eventCard(e)+`<p class="soc-prose">${E(e.data.description)}</p>`).join('')||'<p>Plan a time to catch up.</p>',B('＋ Meeting','space-meeting',s.id))}${card('Group Directory',s.members.filter(m=>m.state==='active').map(m=>`<div class="soc-person">${avatar(user(m.user_id))}<div><b>${E(user(m.user_id).name)}</b><small>${E(m.role)}</small></div></div>`).join(''))}${card('Project Insights',`<div class="soc-stat-row">Completion <b>${progress(s)}%</b></div><div class="soc-stat-row">Overdue tasks <b>${s.tasks.filter(overdue).length}</b></div><div class="soc-stat-row">Pending review <b>${s.tasks.filter(t=>t.data.status==='review').length}</b></div>`)}</aside>`}
 function taskModal(s,t){modal(t?'Edit Task':'Add Task',`${F('Task title','title',t?.title||'','text','required maxlength="160"')}${T('Description','description',t?.data.description||'')}${S('Status','status',[['todo','To Do'],['in_progress','In Progress'],...(s.data.review!==false?[['review','Review']]:[]),['done','Done']],t?.data.status||'todo')}${S('Priority','priority',['low','medium','high','urgent'],t?.data.priority||'medium')}${F('Due date / time','due',t?.data.due||'','datetime-local')}<fieldset><legend>Assign members</legend>${s.members.filter(m=>m.state==='active').map(m=>C(E(user(m.user_id).name),'assigned-'+m.user_id,t?.data.assigned.includes(m.user_id))).join('')}</fieldset>${T('Checklist · one item per line; prefix completed items with [x]','checklist',(t?.data.checklist||[]).map(x=>(x.done?'[x] ':'')+x.text).join('\n'))}<p>Task status is changed explicitly; completing a checklist does not automatically mark the task Done.</p>`,async(v,f)=>{v.space_id=s.id;v.updated_at=t?.updated_at;v.assigned=[...f.querySelectorAll('[name^=assigned-]:checked')].map(x=>x.name.slice(9));v.checklist=v.checklist.split('\n').filter(x=>x.trim()).map(x=>({text:x.replace(/^\[x\]\s*/i,'').trim(),done:/^\[x\]/i.test(x)}));await write('task',v,t?.id)})}
 function eventModal(s,kind='event',e){modal(e?'Edit event':'Create '+kind,`${F('Title','title',e?.title||'','text','required maxlength="160"')}${S('Workspace','space_id',[['','Public Socialise event'],...rooms().filter(s=>s.joined&&s.kind!=='dm').map(s=>[s.id,s.name])],e?.space_id||s||'')}${S('Type','kind',['event','meeting','milestone'],e?.data.kind||kind)}${F('Start','start',e?.data.start||'','datetime-local','required')}${F('End','end',e?.data.end||'','datetime-local')}${F('Location / online link','location',e?.data.location||'')}${T('Description / agenda','description',e?.data.description||'')}<p>This stays in Socialise. It will not be added to anyone’s personal timetable automatically.</p>${e?B('Cancel / delete event','delete-event',e.id):''}`,v=>write('event',v,e?.id))}
 function render(){if(!data||!profile().enabled)return;const title=page==='home'?'Socialise':pages[page];root().innerHTML=`<header class="soc-hero"><span class="soc-hero-icon">♧</span><div><h1>${title}</h1><p>${page==='projects'?'Track group work, manage tasks, and stay in sync with your teammates.':'Meet people, join clubs, find study buddies and make the most of your uni experience.'}</p></div><blockquote>Better connections.<br>Brighter university days.</blockquote></header><div class="soc-topline"><input id="socialSearch" value="${E(search)}" placeholder="Search people, clubs, subjects or posts…" aria-label="Search Socialise">${B('Messages','go-messages')}${B('Connections','requests')}${B('Social updates <span id="socialUnread">'+(data.notifications||[]).filter(n=>!n.read).length+'</span>','notifications')}${B('↻','refresh','','soc-refresh')}</div><p role="status" data-social-status>${E(notice)}</p><div id="socialContent"></div>`;renderContent();root().querySelector('#socialSearch').oninput=e=>{search=e.target.value;renderContent()};bind(root());nav()}
 function renderContent(){const content=root().querySelector('#socialContent');if(!content)return;content.innerHTML=page==='home'?home():page==='people'?`${card('Find classmates',`${C('Same university only','sameUniversity',sameUni)}${S('Shared subject','subjectFilter',[['','All published subjects'],...[...new Set(people().filter(u=>u.subject_discovery).flatMap(u=>u.subjects))]],subject)}<p>University and subject filters use only information people chose to publish.</p>${B('My profile & privacy','privacy')}`)}<div class="soc-directory">${visiblePeople().map(person).join('')||empty('No matching people yet','Ask classmates to enable Socialise and opt in to discovery on this server.')}</div>`:page==='clubs'?directory('club'):page==='groups'?directory('study'):page==='projects'?projects():page==='messages'?messages():`<div class="soc-section-heading"><h2>Events & gatherings</h2>${B('＋ Create Event','new-event')}</div>${(data.events||[]).filter(e=>matches([e.title,e.data.description,e.data.location])).sort((a,b)=>a.data.start.localeCompare(b.data.start)).map(eventCard).join('')||empty('No events yet','Create a study session, club meeting or social gathering.')}`;bind(content);content.querySelector('[name=sameUniversity]')?.addEventListener('change',e=>{sameUni=e.target.checked;renderContent()});content.querySelector('[name=subjectFilter]')?.addEventListener('change',e=>{subject=e.target.value;renderContent()});content.querySelector('[name=projectFilter]')?.addEventListener('change',e=>{projectFilter=e.target.value;renderContent()});content.querySelectorAll('[data-task-status]').forEach(el=>el.onchange=async()=>{const s=rooms().find(s=>s.tasks.some(t=>t.id===el.dataset.taskStatus)),t=s.tasks.find(t=>t.id===el.dataset.taskStatus);el.disabled=true;try{await write('task',{...t.data,title:t.title,status:el.value,updated_at:t.updated_at},t.id);renderContent()}catch(e){feedback(e.message);el.value=t.data.status;el.disabled=false}});const postForm=content.querySelector('#socialPostForm');if(postForm)postForm.onsubmit=async e=>{e.preventDefault();try{await write('post',Object.fromEntries(new FormData(postForm)));renderContent()}catch(err){feedback(err.message)}};const chat=content.querySelector('#socialMessageForm');if(chat){loadMessages();chat.onsubmit=async e=>{e.preventDefault();const text=chat.elements.body.value;try{await write('message',{body:text},conversation);chat.elements.body.value='';await loadMessages()}catch(err){feedback(err.message)}}}}
 function bind(host){host.querySelectorAll('[data-social]').forEach(b=>b.onclick=async()=>{try{await action(b.dataset.social,b.dataset.id)}catch(e){if(dialog.open)dialog.querySelector('.soc-error').textContent=e.message;else feedback(e.message)}})}
 async function action(a,id){if(a.startsWith('go-')){search='';go(a.slice(3));return}if(a==='close'){close();return}if(a==='privacy'){privacy();return}if(a==='refresh'){await refresh();render();return}if(a==='person'){personModal(id);return}if(a==='subject'){subject=id;go('people');return}if(a.startsWith('feed-')){feed=a.slice(5);renderContent();return}if(a==='requests'){modal('Connections',(data.links||[]).map(l=>person(user(l.sender===me()?l.recipient:l.sender))).join('')||empty('No requests yet','Find classmates to make your first connection.'));return}if(a==='notifications'){modal('Social notifications',B('Mark all read','read')+(data.notifications||[]).map(n=>`<article class="soc-notification ${n.read?'':'unread'}"><b>${E(n.kind.replaceAll('_',' '))}</b><p>${E(n.body)}</p><small>${E(when(n.created_at))}</small>${B('Mark read','read',n.id)}</article>`).join(''));return}if(a==='read'){await write('read',{},id);if(dialog.open)action('notifications');return}
 if(a.startsWith('friend-')){if(a==='friend-remove'&&!confirm('Remove this connection?'))return;await write('friend',{user_id:id,operation:a.slice(7)});dialog.close();render();return}if(a==='block'||a==='unblock'){if(!confirm(a==='block'?'Block this account? Direct messages and requests will be blocked.':'Unblock this account?'))return;await write('block',{user_id:id,remove:a==='unblock'});dialog.close();render();return}
 if(a==='dm'){const r=await write('dm',{user_id:id});conversation=r.id;dialog.close();go('messages');return}if(a==='chat'){conversation=id;dialog.close();go('messages');await write('read',{},id);return}if(a==='conversations'){conversation='';renderContent();return}if(a==='delete-message'){if(confirm('Delete your message?')){await write('message_delete',{},id);loadMessages()}return}
 if(['new-club','new-study','new-project','new-chat'].includes(a)){newSpace(a.slice(4));return}if(a==='edit-space'){newSpace(rooms().find(s=>s.id===id).kind,rooms().find(s=>s.id===id));return}if(a==='open-space'){openSpace(id);return}if(a.startsWith('member-')){await write('membership',{operation:a.slice(7)},id);dialog.close();render();return}if(a==='project'){selected=id;tab='overview';renderContent();return}if(a.startsWith('tab-')){tab=a.slice(4);renderContent();return}
 if(a==='invite'){selected=id;modal('Invite a friend',S('Friend','user_id',(data.links||[]).filter(l=>l.state==='accepted').map(l=>{const u=user(l.sender===me()?l.recipient:l.sender);return [u.id,u.name]})),v=>write('membership',{...v,operation:'invite'},id));return}if(['approve','decline','remove-member','transfer'].includes(a)){if((a==='transfer'||a==='remove-member')&&!confirm(a==='transfer'?'Transfer ownership to this member? You will lose owner controls.':'Remove this member’s workspace access?'))return;await write('membership',{operation:a==='remove-member'?'remove':a,user_id:id},selected);dialog.close();render();return}if(a==='role'){modal('Project role',F('Role','role'),v=>write('membership',{...v,operation:'role',user_id:id},selected));return}
 if(a==='new-task'){taskModal(rooms().find(s=>s.id===id));return}if(a==='edit-task'){const s=rooms().find(s=>s.tasks.some(t=>t.id===id));taskModal(s,s.tasks.find(t=>t.id===id));return}if(a==='contribution'){const s=rooms().find(s=>s.id===selected);modal(user(id).name+' · recorded contribution',`<p>Tasks assigned: ${s.tasks.filter(t=>t.data.assigned.includes(id)).length}</p><p>Assigned tasks completed: ${s.tasks.filter(t=>t.data.assigned.includes(id)&&t.data.status==='done').length}</p>${s.activity.filter(x=>x.actor===id).map(x=>`<p>${E(x.body)}<small>${E(when(x.created_at))}</small></p>`).join('')}<p>Based on activity recorded inside Student Helper Portal and may not reflect work completed outside the app.</p>`);return}
 if(a==='new-event'||a.startsWith('space-')){eventModal(id,a==='space-meeting'?'meeting':a==='space-milestone'?'milestone':'event');return}if(a==='edit-event'){eventModal('',null,data.events.find(e=>e.id===id));return}if(a==='delete-event'){if(confirm('Cancel and delete this event?')){await write('event_delete',{},id);dialog.close();render()}return}if(a==='attend'){await write('attend',{},id);renderContent();return}
 if(a==='like'){await write('like',{},id);renderContent();return}if(a==='comment'){modal('Add a comment',T('Comment','body'),v=>write('comment',v,id));return}if(a==='delete-post'){if(confirm('Delete this post and its comments?')){await write('post_delete',{},id);renderContent()}return}
 if(a==='upload'){modal('Upload a private project file',F('File','file','','file','required')+T('Description','description')+'<p>Up to 2 MB. Files are downloaded as attachments. Only active project members can download them.</p>',async(v,f)=>{const file=f.elements.file.files[0];if(!file||file.size>2097152)throw Error('Choose a file up to 2 MB.');const encoded=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file)});await write('file',{name:file.name,description:v.description,base64:encoded},id)});return}}
 async function onShow(name){document.body.classList.toggle('social-open',name.startsWith('social-'));if(name==='settings')settings();if(!name.startsWith('social-'))return;page=name.slice(7);if(!pages[page])return;root().innerHTML='<p role="status">Loading your social workspace…</p>';try{await refresh();if(!profile().enabled){root().innerHTML=empty('Socialise is switched off','Enable it in Settings. Your social data is retained.');return}render()}catch(e){root().innerHTML=`<p role="alert">${E(e.message)}</p>${B('Retry','refresh')}`;bind(root())}}
 async function init(){try{await refresh()}catch(e){notice=e.message;settings()}}
 setInterval(async()=>{if(!document.hidden&&document.body.classList.contains('social-open')&&profile().enabled){await loadMessages();try{const latest=await api();data=latest;const badge=document.getElementById('socialUnread');if(badge)badge.textContent=(data.notifications||[]).filter(n=>!n.read).length}catch{}}},6000);
 return {init,onShow,renderSettings:settings,canLeave:()=>{if(dialog.open&&dirty&&!confirm('Discard unsaved Socialise changes?'))return false;dialog.close();dirty=false;return true}};
}
g.StudentSocial={create};
})(window);
