/* Marketplace uses the shared authenticated repository; no sample listings or people. */
(function(g){'use strict';
const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const B=(label,action,id='',cls='')=>`<button type="button" class="mk-button ${cls}" data-mk="${action}" data-id="${E(id)}">${label}</button>`;
const F=(label,name,value='',type='text',attrs='')=>`<label>${label}<input name="${name}" type="${type}" value="${E(value)}" ${attrs}></label>`;
const T=(label,name,value='',attrs='')=>`<label>${label}<textarea name="${name}" rows="4" ${attrs}>${E(value)}</textarea></label>`;
const S=(label,name,items,value='')=>`<label>${label}<select name="${name}">${items.map(x=>{const [v,l]=Array.isArray(x)?x:[x,x];return `<option value="${E(v)}" ${String(v)===String(value)?'selected':''}>${E(l)}</option>`}).join('')}</select></label>`;
const C=(label,name,on)=>`<label class="mk-check"><input type="checkbox" name="${name}" ${on?'checked':''}>${label}</label>`;
const empty=(title,description)=>`<div class="mk-empty"><span aria-hidden="true">✧</span><h3>${title}</h3><p>${description}</p></div>`;
const stamp=s=>new Date(s).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'});
const types=['Lecture Notes','Tutorial Notes','Lab Notes','Summary Notes','Exam Notes','Practice Questions','Study Guide','Cheat Sheet','Other'];
const weekdays=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
const split=s=>String(s||'').split(',').map(s=>s.trim()).filter(Boolean);
const avatar=p=>`<span class="mk-avatar">${/^data:image\/(jpeg|png|webp);base64,/.test(p?.photo||'')?`<img alt="" src="${E(p.photo)}">`:E(p?.name?.slice(0,2).toUpperCase()||'S')}</span>`;
const stars=rs=>rs?.length?`${(rs.reduce((n,r)=>n+r.rating,0)/rs.length).toFixed(1)} ★ (${rs.length} verified reviews)`:'No reviews yet';
function create(o){
 let data=null,page='notes',pane='browse',selected='',filters={},expanded=true,busy=false,notice='',conversation='',messageSignature='',dirty=false;
 const dialog=document.createElement('dialog');dialog.className='mk-dialog';document.body.append(dialog);
 dialog.addEventListener('input',()=>dirty=true);dialog.addEventListener('cancel',e=>{if(dirty&&!confirm('Discard unsaved Marketplace changes?'))e.preventDefault();else dirty=false});
 for(const p of ['notes','tutors']){const el=document.createElement('section');el.id='view-marketplace-'+p;el.className='view marketplace-view';document.querySelector('.main').append(el)}
 const root=()=>document.getElementById('view-marketplace-'+page),me=()=>data?.me?.id,listing=id=>data.listings.find(n=>n.id===id),tutor=id=>data.tutors.find(t=>t.user_id===id);
 const money=n=>new Intl.NumberFormat(undefined,{style:'currency',currency:data?.settings?.currency||'AUD'}).format(n/100);
 async function api(url='/api/marketplace',body){const r=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const j=await r.json();if(!r.ok)throw Error(j.error||'Unable to complete Marketplace request.');return j}
 async function refresh(){data=await api();nav()}
 async function write(action,values={},id){if(busy)throw Error('Please wait for your current save.');busy=true;try{const result=await api('/api/marketplace',{action,data:values,id});await refresh();return result}finally{busy=false}}
 function feedback(s){notice=s;root()?.querySelector('[data-mk-status]')?.replaceChildren(document.createTextNode(s))}
 function nav(){let n=document.getElementById('marketplaceNav');if(!n){n=document.createElement('div');n.id='marketplaceNav';n.className='marketplace-nav';document.querySelector('.nav [data-view=tutor]').before(n)}n.innerHTML=`<button id="marketplaceToggle" aria-expanded="${expanded}" aria-controls="marketplaceSubnav"><span aria-hidden="true">🛒</span><span>Marketplace</span><span>${expanded?'⌄':'›'}</span></button><div id="marketplaceSubnav" ${expanded?'':'hidden'}>${B('Notes','go-notes','',page==='notes'&&document.body.classList.contains('marketplace-open')?'active':'')}${B('Tutoring Program','go-tutors','',page==='tutors'&&document.body.classList.contains('marketplace-open')?'active':'')}</div>`;n.querySelector('#marketplaceToggle').onclick=()=>{expanded=!expanded;nav()};bind(n)}
 function modal(title,html,submit){dirty=false;dialog.innerHTML=`<header><h2>${E(title)}</h2>${B('✕','close','','mk-close')}</header><form class="mk-form">${html}<p class="mk-error" role="alert"></p>${submit?'<footer><button class="mk-button mk-primary" type="submit">Save</button></footer>':''}</form>`;bind(dialog);if(!dialog.open)dialog.showModal();const f=dialog.querySelector('form');f.onsubmit=async e=>{e.preventDefault();if(!submit)return;const button=f.querySelector('[type=submit]');button.disabled=true;try{await submit(Object.fromEntries(new FormData(f)),f);dirty=false;dialog.close();render()}catch(err){f.querySelector('.mk-error').textContent=err.message;button.disabled=false}}}
 function reviewList(rows){return rows.map(r=>`<article class="mk-review"><b>${E(r.reviewer.name)} · ${r.rating}/5 ★</b><small>Verified ${r.kind==='note'?'acquisition':'session'} · ${E(stamp(r.created_at))}</small><p>${E(r.body)}</p>${B('Report review','report-review',r.id)}</article>`).join('')||'<p>No reviews yet. Reviews require an acquisition or a completed session.</p>'}
 function saved(kind,id){return data.saved.some(s=>s.kind===kind&&s.target===id)}
 function matches(values){return values.join(' ').toLowerCase().includes((filters.q||'').toLowerCase())}
 function filteredNotes(){return data.listings.filter(n=>n.status==='published'&&matches([n.metadata.title,n.metadata.subject,n.metadata.topic,n.metadata.description,n.metadata.tags.join(' '),n.seller_profile.name,n.metadata.resource_type])&&(!filters.subject||n.metadata.subject.toLowerCase().includes(filters.subject.toLowerCase()))&&(!filters.topic||n.metadata.topic.toLowerCase().includes(filters.topic.toLowerCase()))&&(!filters.resource||n.metadata.resource_type===filters.resource)&&(!filters.format||n.format===filters.format)&&(!filters.price|| (filters.price==='free'?n.metadata.price_minor===0:n.metadata.price_minor>0))&&(!filters.min||n.metadata.price_minor>=Number(filters.min)*100)&&(!filters.max||n.metadata.price_minor<=Number(filters.max)*100)&&(!filters.rating||n.rating>=Number(filters.rating))&&(!filters.uni||data.me.university&&n.seller_profile.university.toLowerCase()===data.me.university.toLowerCase())).sort((a,b)=>filters.sort==='price'?a.metadata.price_minor-b.metadata.price_minor:filters.sort==='rating'?b.rating-a.rating:b.updated_at.localeCompare(a.updated_at))}
 function filteredTutors(){return data.tutors.filter(t=>matches([t.profile.name,t.data.bio,t.data.tagline,t.data.subjects.join(' ')])&&(!filters.subject||t.data.subjects.some(s=>s.toLowerCase().includes(filters.subject.toLowerCase())))&&(!filters.min||t.data.price_minor>=Number(filters.min)*100)&&(!filters.max||t.data.price_minor<=Number(filters.max)*100)&&(!filters.rating||t.reviews.length&&t.reviews.reduce((n,r)=>n+r.rating,0)/t.reviews.length>=Number(filters.rating))&&(!filters.method||t.data.methods.includes(filters.method))&&(!filters.language||t.data.languages.join(' ').toLowerCase().includes(filters.language.toLowerCase()))&&(!filters.year||t.data.year===filters.year)&&(!filters.day||t.data.availability.some(s=>String(s.day)===filters.day||(filters.day==='weekend'&&s.day>=5)))&&(!filters.period||t.data.availability.some(s=>s.start<({morning:'12:00',afternoon:'17:00',evening:'23:59'}[filters.period])&&s.end>({morning:'06:00',afternoon:'12:00',evening:'17:00'}[filters.period])))&&(!filters.uni||data.me.university&&t.profile.university.toLowerCase()===data.me.university.toLowerCase())).sort((a,b)=>filters.sort==='price'?a.data.price_minor-b.data.price_minor:filters.sort==='rating'?(b.reviews.length?b.reviews.reduce((n,r)=>n+r.rating,0)/b.reviews.length:0)-(a.reviews.length?a.reviews.reduce((n,r)=>n+r.rating,0)/a.reviews.length:0):b.updated_at.localeCompare(a.updated_at))}
 function filterForm(){return `<form id="mkFilters"><h3>Filters ${B('Reset','reset')}</h3>${F('Subject / course','subject',filters.subject)}${page==='notes'?F('Topic','topic',filters.topic)+S('Resource type','resource',[['','All resources'],...types],filters.resource)+S('Price','price',[['','All prices'],['free','Free'],['paid','Paid']],filters.price)+S('File type','format',[['','All formats'],['pdf','PDF'],['markdown','Markdown'],['html','Portal Note']],filters.format):S('Day','day',[['','Any day'],...weekdays.map((s,i)=>[String(i),s]),['weekend','Weekend']],filters.day)+S('Time of day','period',[['','Any time'],['morning','Morning'],['afternoon','Afternoon'],['evening','Evening']],filters.period)+S('Session type','method',[['','All types'],'Online','In-person','Group','1-to-1'],filters.method)+F('Language','language',filters.language)+F('Year level','year',filters.year)}<div class="mk-two">${F('Min price','min',filters.min,'number','min="0" step="0.01"')}${F(page==='tutors'?'Max / hour':'Max price','max',filters.max,'number','min="0" step="0.01"')}</div>${S('Minimum rating','rating',[['','Any rating'],['5','5 stars'],['4','4+ stars'],['3','3+ stars']],filters.rating)}${C('Same university only','uni',filters.uni)}<small>Uses your account university and publicly shared profile universities. Not an institutional verification.</small><button type="submit" class="mk-button mk-primary">Apply filters</button></form>`}
 function noteCard(n){const d=n.metadata;return `<article class="mk-listing ${selected===n.id?'selected':''}"><button class="mk-cover" data-mk="detail" data-id="${n.id}" aria-label="Preview ${E(d.title)}"><b>${E(d.subject)}</b><span>${E(d.resource_type)}</span><i aria-hidden="true">▤</i></button><div class="mk-card-copy"><button class="mk-title" data-mk="detail" data-id="${n.id}">${E(d.title)}</button><p>${E(d.description||'Student-created study resource.')}</p><div class="mk-tags">${[d.subject,d.resource_type,n.format.toUpperCase()].map(s=>`<span>${E(s)}</span>`).join('')}</div><button class="mk-seller" data-mk="seller" data-id="${n.seller}">${avatar(n.seller_profile)}<span>${E(n.seller_profile.name)}<small>${E(stars(n.reviews))}</small></span></button></div><div class="mk-card-price"><b>${d.price_minor?money(d.price_minor):'Free'}</b><small>${d.pages} pages</small>${B(saved('note',n.id)?'♥ Saved':'♡ Save','save-note',n.id)}${B(n.owned?'My copy':d.price_minor?'Add to cart':'Get Notes',n.owned?'acquired':d.price_minor?'cart-add':'acquire',n.id,'mk-primary')}</div></article>`}
 function tutorCard(t){const d=t.data;return `<article class="mk-listing mk-tutor-card ${selected===t.user_id?'selected':''}">${avatar(t.profile)}<div class="mk-card-copy"><button class="mk-title" data-mk="detail" data-id="${t.user_id}">${E(t.profile.name)}</button><div class="mk-tags">${d.subjects.map(s=>`<span>${E(s)}</span>`).join('')}</div><p>${E(d.tagline||d.bio.slice(0,130))}</p><small>${E(stars(t.reviews))}</small>${t.profile.university&&t.profile.university===data.me.university?'<span class="mk-pill">Same university</span>':''}</div><div class="mk-card-price"><b>${money(d.price_minor)}/hr</b><small>${E(d.methods.join(' · '))}</small><small>${E(d.status)}</small>${B(saved('tutor',t.user_id)?'♥ Saved':'♡ Save','save-tutor',t.user_id)}${B('View Profile','detail',t.user_id)}${B('Book','book',t.user_id,'mk-primary')}</div></article>`}
 function availabilityTable(t){return `<p>Weekly availability · ${E(t.data.timezone)}</p><div class="mk-availability">${weekdays.map((s,i)=>`<div><b>${s}</b>${t.data.availability.filter(a=>a.day===i).map(a=>`<small>${E(a.start)}–${E(a.end)}</small>`).join('')||'<small>—</small>'}</div>`).join('')}</div><small>Exceptions and existing reservations are excluded when you choose a booking slot.</small>`}
 function detail(){if(page==='notes'){const n=listing(selected);if(!n)return empty('A closer look','Select a resource to read its preview.');const d=n.metadata;return `<div class="mk-preview"><header><span>Public excerpt · not the full document</span>${B('⛶','preview',n.id)}</header><div class="mk-paper"><h2>${E(d.title)}</h2><p>${E(n.preview)}</p></div></div><h2>${E(d.title)}</h2><button class="mk-seller" data-mk="seller" data-id="${n.seller}">${avatar(n.seller_profile)}${E(n.seller_profile.name)}</button><p>${E(stars(n.reviews))}</p><div class="mk-pricebar"><strong>${d.price_minor?money(d.price_minor):'Free'}</strong>${B(n.owned?'Open acquired copy':d.price_minor?'Add to Cart':'Get Notes',n.owned?'acquired':d.price_minor?'cart-add':'acquire',n.id,'mk-primary')}</div><small>${d.pages} pages · ${E(n.format)} · Updated ${E(stamp(n.updated_at))} · v${n.version}</small><h3>Description</h3><p class="mk-prose">${E(d.description)}</p><div class="mk-tags">${d.tags.map(s=>`<span>${E(s)}</span>`).join('')}</div>${B('Message Seller','message-note',n.id)}${B('Report listing','report-note',n.id)}<h3>Verified reviews</h3>${reviewList(n.reviews)}`}const t=tutor(selected);if(!t)return empty('Find your study partner','Select a tutor to see their profile and availability.');return `<div class="mk-tutor-heading">${avatar(t.profile)}<div><h2>${E(t.profile.name)}</h2><p>${E(stars(t.reviews))}</p><small>${E(t.profile.university||'University not shared')}</small></div></div><div class="mk-tags">${t.data.subjects.map(s=>`<span>${E(s)}</span>`).join('')}</div><p class="mk-prose">${E(t.data.bio)}</p><p>${E(t.data.experience)}</p><p>${E(t.data.languages.join(' · '))} · ${E(t.data.methods.join(' · '))}</p><strong>${money(t.data.price_minor)} / hour · ${E(t.data.status)}</strong>${availabilityTable(t)}<div class="mk-actions">${B('Book Session','book',t.user_id,'mk-primary')}${B('Message Tutor','message-tutor',t.user_id)}</div>${B('Report profile','report-tutor',t.user_id)}<h3>Verified session reviews</h3>${reviewList(t.reviews)}`}
 function render(){if(!data)return;root().innerHTML=`<header class="mk-hero"><span class="mk-hero-icon" aria-hidden="true">▤</span><div><h1>Marketplace</h1><p>${page==='notes'?'Good notes. Shared knowledge. A brighter semester.':'Find student tutors and learning support from your community.'}</p></div><div class="mk-share"><span>Share your knowledge.<br>Help other students.</span>${B(page==='notes'?'Sell Your Notes':'Sign Up / Edit Tutor Profile',page==='notes'?'sell':'onboard','','mk-primary')}</div></header><nav class="mk-tabs" aria-label="Marketplace sections">${B('Notes','go-notes','',page==='notes'?'active':'')}${B('Tutoring Program','go-tutors','',page==='tutors'?'active':'')}<div class="mk-controls">${B('Cart · '+data.cart.length,'cart')}${B('Messages <span id="mkMessageCount">'+data.conversations.reduce((n,c)=>n+c.unread,0)+'</span>','messages')}${B('Marketplace Updates <span id="mkNoticeCount">'+data.notifications.filter(n=>!n.read).length+'</span>','notifications')}</div></nav><div class="mk-toolbar"><input id="mkSearch" aria-label="Search Marketplace" placeholder="Search ${page==='notes'?'notes, subjects, topics or sellers':'tutors, subjects or keywords'}…" value="${E(filters.q||'')}">${B('Browse','pane-browse')}${B('My Marketplace','pane-account')}${B(page==='notes'?'Seller dashboard':'Tutor dashboard','pane-dashboard')}${B('Profile','profile')}${B('↻ Refresh','refresh')}</div><p role="status" data-mk-status>${E(notice)}</p><div id="mkBody"></div>`;content();bind(root());root().querySelector('#mkSearch').oninput=e=>{filters.q=e.target.value;pane='browse';content()};nav()}
 function content(){const body=root().querySelector('#mkBody');if(pane==='browse'){const rows=page==='notes'?filteredNotes():filteredTutors();if(!rows.some(r=>(r.id||r.user_id)===selected))selected=rows[0]?.id||rows[0]?.user_id||'';body.innerHTML=`<div class="mk-layout"><aside class="mk-filters">${filterForm()}</aside><section class="mk-results"><header><b>${rows.length} ${page==='notes'?'notes':'tutors'} found</b>${B('Filters','filters','','mk-mobile-filter')}${S('Sort by','sort',[['new','Recently updated'],['price','Price: low to high'],['rating','Highest rated']],filters.sort)}</header>${rows.map(page==='notes'?noteCard:tutorCard).join('')||empty(page==='notes'?'No notes found':'No matching tutors','Try another filter, or be the first to share your knowledge on this server.')}</section><aside class="mk-detail">${detail()}</aside></div>`;const f=body.querySelector('#mkFilters');f.onsubmit=e=>{e.preventDefault();applyFilters(f)};body.querySelector('[name=sort]').onchange=e=>{filters.sort=e.target.value;content()}}else body.innerHTML=pane==='account'?account():dashboard();bind(body)}
 function applyFilters(f){filters={...filters,...Object.fromEntries(new FormData(f)),uni:f.elements.uni.checked};content()}
 function account(){const mine=data.listings.filter(n=>n.owned),savedNotes=data.listings.filter(n=>saved('note',n.id)),savedTutors=data.tutors.filter(t=>saved('tutor',t.user_id));return `<div class="mk-account-grid"><section class="mk-panel"><h2>My Library</h2><p>Acquisitions remain available here. Your copy is pinned to its acquired version.</p>${mine.map(n=>`<article class="mk-owned"><h3>${E(n.metadata.title)}</h3><small>Acquired ${E(stamp(data.library.find(l=>l.listing===n.id).acquired_at))} · ${E(n.seller_profile.name)}</small><div class="mk-actions">${B('Download / Add to Subject','acquired',n.id)}${B('Write a review','review-note',n.id)}</div></article>`).join('')||empty('Your library starts here','Claim a free resource or acquire paid notes when payments are available.')}</section><section class="mk-panel"><h2>My Tutoring Bookings</h2>${bookings(data.bookings.filter(b=>b.student===me()))}</section><section class="mk-panel"><h2>Saved Notes</h2>${savedNotes.map(noteCard).join('')||'<p>No saved notes yet.</p>'}</section><section class="mk-panel"><h2>Saved Tutors</h2>${savedTutors.map(tutorCard).join('')||'<p>No saved tutors yet.</p>'}</section></div>`}
 function bookings(rows){return rows.map(b=>`<article class="mk-booking"><header><b>${E(b.data.subject)} · ${E(b.student===me()?b.tutor_profile.name:b.student_profile.name)}</b><span class="mk-pill">${E(b.status)}</span></header><p>${E(stamp(b.start_at))} · ${b.data.duration} minutes · ${E(b.data.method)}</p><small>${money(b.data.amount_minor)} · ${E(b.data.payment_status==='free'?'Free session':'Payment not collected — payments unconfigured')}</small><p>${E(b.data.note)}</p><div class="mk-actions">${b.status==='pending'&&b.tutor===me()?B('Accept','confirm-booking',b.id)+B('Decline','decline-booking',b.id):''}${['pending','confirmed'].includes(b.status)?B('Cancel','cancel-booking',b.id):''}${b.status==='confirmed'?B('Add to my timetable','calendar',b.id):''}${b.status==='confirmed'&&b.tutor===me()&&new Date(b.end_at)<=new Date()?B('Mark completed','complete-booking',b.id):''}${b.status==='completed'&&b.student===me()?B('Review tutor','review-tutor',b.id):''}${B('Marketplace chat','booking-chat',b.id)}</div></article>`).join('')||empty('No bookings yet','Your requests and upcoming sessions will appear here.')}
 function dashboard(){if(page==='notes'){const own=data.listings.filter(n=>n.seller===me());return `<div class="mk-stats">${[['Listings',own.length],['Acquisitions',data.sales.length],['Downloads',data.sales.reduce((n,s)=>n+s.downloads,0)],['Recorded earnings',money(data.ledger.filter(l=>l.kind==='seller_earning'&&l.status==='settled').reduce((n,l)=>n+l.amount_minor,0))]].map(([s,n])=>`<section class="mk-panel"><small>${s}</small><strong>${n}</strong></section>`).join('')}</div><section class="mk-panel"><header><h2>My Listings</h2>${B('＋ Sell Your Notes','sell','','mk-primary')}</header><p>Payments and payouts are not configured. Free acquisitions are not sales revenue.</p>${own.map(n=>`<article class="mk-owned"><h3>${E(n.metadata.title)}</h3><p>${E(n.status)} · v${n.version} · ${money(n.metadata.price_minor)} · ${E(stars(n.reviews))}</p><div class="mk-actions">${B('Edit / New version','edit-listing',n.id)}${B(n.status==='published'?'Unpublish':'Publish',n.status==='published'?'unpublish':'publish',n.id)}${B('Reviews','listing-reviews',n.id)}</div></article>`).join('')||empty('You haven’t listed notes yet','Share your own study materials with the community.')}</section>${moderation()}`}
 const own=tutor(me());if(!own)return `<section class="mk-panel">${empty('Become a tutor','Share what you know. Set subjects, pricing and availability.')}${B('Sign Up as Tutor','onboard','','mk-primary')}</section>`;const bs=data.bookings.filter(b=>b.tutor===me());return `<div class="mk-stats">${[['Upcoming',bs.filter(b=>b.status==='confirmed'&&new Date(b.start_at)>new Date()).length],['Requests',bs.filter(b=>b.status==='pending').length],['Completed',bs.filter(b=>b.status==='completed').length],['Recorded earnings',money(data.ledger.filter(l=>l.kind==='seller_earning'&&l.status==='settled'&&l.booking_id).reduce((n,l)=>n+l.amount_minor,0))]].map(([s,n])=>`<section class="mk-panel"><small>${s}</small><strong>${n}</strong></section>`).join('')}</div><div class="mk-account-grid"><section class="mk-panel"><header><h2>Subjects, pricing & availability</h2>${B('Edit profile','onboard')}</header><p>${E(own.data.subjects.join(' · '))} · ${money(own.data.price_minor)}/hour</p>${availabilityTable(own)}<p>Blocked dates: ${E(own.data.exceptions.join(', ')||'None')}</p><p>Payments and payouts are not configured. Session quotes are not earnings.</p></section><section class="mk-panel"><h2>Students</h2>${[...new Map(bs.map(b=>[b.student,b.student_profile])).values()].map(p=>`<p>${E(p.name)} · ${bs.filter(b=>b.student===p.id&&b.status==='completed').length} completed sessions</p>`).join('')||'<p>No students have booked yet.</p>'}</section><section class="mk-panel"><h2>Bookings & past sessions</h2>${bookings(bs)}</section><section class="mk-panel"><h2>Verified reviews</h2>${reviewList(own.reviews)}</section></div>${moderation()}`}
 function moderation(){return data.is_admin?`<section class="mk-panel"><h2>Marketplace moderation</h2>${B('Platform fee settings','fees')}${data.reports.filter(r=>r.status==='open').map(r=>`<article><b>${E(r.kind)}</b><p>${E(r.reason)}</p><small>Target ${E(r.target)}</small>${r.kind==='note'?B('Remove listing','takedown',r.id):''}${B('Resolve report','resolve-report',r.id)}</article>`).join('')||'<p>No open reports.</p>'}</section>`:''}
 async function sellerForm(id){const n=id?listing(id):null,d=n?.metadata||{},opts=await api('/api/marketplace/options');modal(n?'Edit listing / publish new version':'Sell Your Notes',`<p>Share only material you created or have permission to distribute. Account profile images are reused; private note images are omitted from snapshots.</p>${F('Title','title',d.title,'text','required maxlength="200"')}<div class="mk-two">${F('Subject','subject',d.subject,'text','required maxlength="120"')}${F('Topic (optional)','topic',d.topic)}</div>${S('Resource type','resource_type',types,d.resource_type||'Lecture Notes')}${T('Description','description',d.description)}${F('Tags (comma separated)','tags',(d.tags||[]).join(', '))}<div class="mk-two">${F('Price ('+(data.settings.currency||'AUD')+') · 0 for free','price',(d.price_minor||0)/100,'number','min="0" step="0.01" required')}${F('Page count','pages',d.pages||1,'number','min="1" max="10000" required')}</div>${F('Semester / term','term',d.term)}${S('Visibility','status',['draft','published','unlisted'],n?.status||'draft')}${S('Resource source','source',[...(n?[['keep','Keep existing protected file']]:[]),['portal','Existing Portal Note'],['markdown','Upload Markdown'],['pdf','Upload PDF']])}${S('Choose your note','source_note',[['','Select a note'],...opts.notes.map(n=>[n.id,n.title])])}<label>Upload PDF or Markdown (PDF 8 MB max; Markdown 100 KB)<input name="file" type="file" accept=".pdf,.md,.markdown"></label>${T('Public preview excerpt · visible before purchase, text only','preview',n?.preview||'','maxlength="6000"')}<small>Only this excerpt is public. Full PDF/Markdown is served after acquisition. Never put private information in your excerpt.</small>${C('I created this material or have the right to share/sell it.','rights',false)}`,async(v,f)=>{v.tags=split(v.tags);v.rights=f.elements.rights.checked;if(v.source==='keep'){delete v.source_note;delete v.format}else if(v.source==='portal'){if(!v.source_note)throw Error('Select your own note to snapshot.')}else{delete v.source_note;const file=f.elements.file.files[0];if(!file)throw Error('Choose a file.');if(v.source==='pdf'){if(file.size>8*1024*1024)throw Error('PDF exceeds 8 MB.');v.format='pdf';v.base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file)})}else{if(file.size>100000)throw Error('Markdown exceeds 100 KB.');v.format='markdown';v.content=await file.text()}}await write('listing',v,id);notice='Listing saved. Your private source note was not modified.'})}
 async function importNote(id){const n=listing(id),opts=await api('/api/marketplace/options');if(!opts.subjects.length)throw Error('Create a subject in Subjects first, then return to import this note.');modal('Add to Student Helper Portal',`${S('Subject','subject_id',opts.subjects.map(s=>[s.id,s.name]))}${S('Topic','topic_name',[['','No Topic']])}${F('Week (required if no topic)','week',1,'number','min="1" max="100"')}<p>This creates your own editable Notes copy, tagged Marketplace. It will never change the seller’s original. Use Subjects to create a new subject/topic first if needed.</p>`,async v=>{await api('/api/marketplace/import',{...v,listing:id});notice='Imported successfully. Open Subjects → your subject → Notes to edit your copy.'});const f=dialog.querySelector('form');const update=()=>{f.elements.topic_name.innerHTML='<option value="">No Topic</option>'+opts.topics.filter(t=>t.subject_id===f.elements.subject_id.value).map(t=>`<option value="${E(t.topic_name)}">${E(t.topic_name)}</option>`).join('')};f.elements.subject_id.onchange=update;update()}
 function acquired(id){const n=listing(id);modal('Notes acquired successfully',`<h3>${E(n.metadata.title)}</h3><p>Your acquired version stays in My Library.</p><div class="mk-actions"><a class="mk-button mk-primary" href="/api/marketplace/download/${id}">Download original ${E(n.format.toUpperCase())}</a>${n.format!=='pdf'?B('Add to Student Helper Portal','import',id):''}</div><p>${n.format==='pdf'?'PDF-only resource. Download the PDF; this is not an editable Portal Note.':'You can do both: download the original and import an editable copy.'}</p>`)}
 function onboard(){const t=tutor(me()),d=t?.data||{};modal('Tutor profile & availability',`<p>Your existing account name and avatar are used. Change your photo in Settings. Publish university through Marketplace Profile. No institutional verification is claimed.</p>${F('Short introduction','tagline',d.tagline,'text','maxlength="180"')}${T('Bio / teaching style','bio',d.bio)}${T('Teaching experience','experience',d.experience)}${F('Subjects (comma separated)','subjects',(d.subjects||[]).join(', '),'text','required')}${F('Default hourly price · '+data.settings.currency,'price',(d.price_minor||0)/100,'number','min="0" step="0.01" required')}${F('Languages (comma separated)','languages',(d.languages||[]).join(', '))}${F('Year level','year',d.year)}<fieldset><legend>Session types</legend>${['Online','In-person','Group','1-to-1'].map(s=>C(s,'method-'+s,d.methods?.includes(s)||(!t&&s==='Online'))).join('')}</fieldset>${S('Status','status',[['accepting','Accepting students'],['unavailable','Temporarily unavailable'],['paused','Paused']],d.status||'accepting')}${C('Approval required (otherwise instant confirmation)','approval',d.approval!==false)}${F('Availability timezone (IANA)','timezone',d.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone,'text','required')}<fieldset><legend>Weekly availability</legend><p>One window per day in this editor. Leave both times empty for unavailable.</p>${weekdays.map((s,i)=>{const slot=(d.availability||[]).find(a=>a.day===i);return `<div class="mk-two">${F(s+' start','start-'+i,slot?.start||'','time')}${F(s+' end','end-'+i,slot?.end||'','time')}</div>`}).join('')}</fieldset>${T('Blocked dates · one YYYY-MM-DD per line','exceptions',(d.exceptions||[]).join('\n'))}${C('I agree to provide legitimate tutoring and communicate responsibly.','terms',false)}<p>Paid sessions may be requested, but no money is collected until a payment provider is configured.</p>`,async(v,f)=>{v.subjects=split(v.subjects);v.languages=split(v.languages);v.methods=['Online','In-person','Group','1-to-1'].filter(s=>f.elements['method-'+s].checked);v.approval=f.elements.approval.checked;v.terms=f.elements.terms.checked;v.exceptions=v.exceptions.split(/\s+/).filter(Boolean);v.availability=weekdays.flatMap((s,i)=>v['start-'+i]||v['end-'+i]?[{day:i,start:v['start-'+i],end:v['end-'+i]}]:[]);await write('tutor',v);notice='Tutor profile saved.'})}
 function book(id){const t=tutor(id);if(id===me())throw Error('You cannot book yourself.');if(t.data.status!=='accepting')throw Error('This tutor is not accepting students right now.');modal('Book a session with '+t.profile.name,`${S('Subject','subject',t.data.subjects)}${S('Session type','method',t.data.methods)}${F('Date in '+E(t.data.timezone),'date','','date','required')}${S('Duration','duration',[['30','30 minutes'],['60','60 minutes'],['90','90 minutes'],['120','120 minutes']],'60')}${B('Find available times','find-slots',id)}<div id="mkSlotChoices">${S('Available time','start',[['','Choose a date and find times']])}</div><p id="mkQuote"></p>${T('Question / note for your tutor','note')}<p>Times use the tutor’s timezone. ${t.data.approval?'Tutor approval is required.':'This tutor offers instant confirmation.'} No payment will be collected. ${t.data.price_minor?'Payments are not configured yet.':''}</p>`,async v=>{const r=await write('book',v,id);notice='Booking '+(t.data.approval?'requested':'confirmed')+'. '+(!t.data.approval?'Use My Marketplace → Add to my timetable if you want it on your calendar.':'You will receive a Marketplace update when the tutor responds.');pane='account'});const f=dialog.querySelector('form');const quote=()=>{dialog.querySelector('#mkQuote').textContent='Session quote: '+money(Math.round(t.data.price_minor*Number(f.elements.duration.value)/60));f.elements.start.innerHTML='<option value="">Find available times again</option>'};for(const name of ['subject','method','date','duration'])f.elements[name].onchange=quote;quote()}
 async function findSlots(id){const f=dialog.querySelector('form');if(!f.elements.date.value)throw Error('Choose a date first.');const values=Object.fromEntries(new FormData(f));const r=await api('/api/marketplace/slots?'+new URLSearchParams({tutor:id,date:values.date,duration:values.duration,subject:values.subject,method:values.method}));dialog.querySelector('#mkSlotChoices').innerHTML=S('Available time ('+E(r.timezone)+')','start',r.slots.length?r.slots.map(s=>[s.start,s.label]):[['','No available slots — choose another date']]);dialog.querySelector('[name=start]').required=true}
 async function loadMessages(){const host=dialog.querySelector('#mkMessages');if(!host||!conversation||!dialog.open)return;const id=conversation,r=await api('/api/marketplace/messages?conversation='+encodeURIComponent(id));if(conversation!==id||!host.isConnected)return;const signature=JSON.stringify(r.messages);if(signature===messageSignature)return;messageSignature=signature;host.innerHTML=r.messages.map(m=>`<article class="mk-chat-message ${m.author===me()?'mine':''}"><b>${m.author===me()?'You':'Marketplace contact'}</b><p>${E(m.body)}</p><small>${E(stamp(m.created_at))}</small></article>`).join('')||empty('Start a conversation','Ask about the resource or arrange your tutoring session.');host.scrollTop=host.scrollHeight}
 async function chat(id){conversation=id;messageSignature='';modal('Marketplace Messages',`<div id="mkMessages" role="log" aria-live="polite"></div>${T('Message','body','','required maxlength="5000"')}`,async v=>{await write('message',{body:v.body},id)});const f=dialog.querySelector('form');f.querySelector('[type=submit]').textContent='Send';f.onsubmit=async e=>{e.preventDefault();const button=f.querySelector('[type=submit]');button.disabled=true;try{await write('message',{body:f.elements.body.value},id);f.elements.body.value='';dirty=false;await loadMessages()}catch(err){f.querySelector('.mk-error').textContent=err.message}finally{button.disabled=false}};await loadMessages()}
 function bind(host){host.querySelectorAll('[data-mk]').forEach(b=>b.onclick=async()=>{try{await action(b.dataset.mk,b.dataset.id)}catch(e){if(dialog.open)dialog.querySelector('.mk-error').textContent=e.message;else feedback(e.message)}})}
 async function action(a,id){
 if(a.startsWith('go-')){pane='browse';selected='';filters={};o.show('marketplace-'+a.slice(3));return}
 if(a.startsWith('pane-')){pane=a.slice(5);render();return}
 if(a==='close'){if(!dirty||confirm('Discard unsaved changes?')){dirty=false;dialog.close()}return}
 if(a==='refresh'){await refresh();render();return}
 if(a==='reset'){filters={};content();return}
 if(a==='filters'){modal('Marketplace filters',filterForm().replace('<form id="mkFilters">','<div id="mkFilters">').replace('</form>','</div>'));const f=dialog.querySelector('form');f.onsubmit=e=>{e.preventDefault();applyFilters(f);dirty=false;dialog.close()};return}
 if(a==='detail'){selected=id;if(innerWidth<1180)modal(page==='notes'?'Resource preview':'Tutor profile',detail());else content();return}
 if(a==='preview'){const n=listing(id);modal('Public preview',`<div class="mk-paper"><h2>${E(n.metadata.title)}</h2><p>${E(n.preview)}</p></div>`);return}
 if(a==='sell'||a==='edit-listing'){await sellerForm(id);return}
 if(a==='publish'||a==='unpublish'){await write('listing_status',{status:a==='publish'?'published':'unlisted'},id);render();return}
 if(a==='acquire'){await write('acquire',{},id);render();acquired(id);return}
 if(a==='acquired'){acquired(id);return}
 if(a==='import'){await importNote(id);return}
 if(a==='cart-add'){await write('cart',{},id);feedback('Added to cart. Payments are not configured yet.');render();return}
 if(a==='cart'){const rows=data.cart.map(listing).filter(Boolean);modal('Your cart',rows.map(n=>`<article class="mk-owned"><b>${E(n.metadata.title)}</b> ${money(n.metadata.price_minor)} ${B('Remove','cart-remove',n.id)}</article>`).join('')+`<h3>Subtotal ${money(rows.reduce((n,r)=>n+r.metadata.price_minor,0))}</h3><p>Payments are not configured yet. No charge will be made.</p>${rows.length?B('Checkout','checkout','','mk-primary'):empty('Your cart is empty','Paid resources can be saved here for later.')}`);return}
 if(a==='cart-remove'){await write('cart',{remove:true},id);await action('cart');render();return}
 if(a==='checkout'){await write('checkout');return}
 if(a.startsWith('save-')){const kind=a.slice(5);await write('saved',{kind,remove:saved(kind,id)},id);render();return}
 if(a==='profile'){modal('Marketplace public profile',`${T('Public seller bio','bio',data.me.bio)}${C('Show my account university publicly in Marketplace','show_university',data.me.show_university)}<p>Change your name, university or avatar in Settings. We do not claim institutional verification. Sharing university enables same-university matching.</p>`,(v,f)=>write('profile',{bio:v.bio,show_university:f.elements.show_university.checked}));return}
 if(a==='seller'){const rows=data.listings.filter(n=>n.seller===id&&n.status==='published'),p=rows[0]?.seller_profile||data.me;modal('Seller profile',`${avatar(p)}<h3>${E(p.name)}</h3><p>${E(p.university)}</p><p>${E(p.bio)}</p>${rows.map(n=>`<article><h3>${E(n.metadata.title)}</h3><small>${E(stars(n.reviews))}</small>${B('Message seller','message-note',n.id)}</article>`).join('')}`);return}
 if(a.startsWith('message-')){const r=await write('conversation',{kind:a.slice(8)},id);await chat(r.id);return}
 if(a==='messages'){modal('Marketplace conversations',data.conversations.map(c=>B(E(c.other.name)+' · '+E(c.kind)+(c.unread?' · '+c.unread+' unread':''),'chat',c.id)).join('')||empty('No Marketplace conversations','Message a seller or tutor to start. These chats are separate from Socialise.'));return}
 if(a==='chat'){await chat(id);return}
 if(a==='notifications'){modal('Marketplace updates',B('Mark all read','read')+data.notifications.map(n=>`<article class="mk-owned ${n.read?'':'mk-unread'}"><b>${E(n.kind.replaceAll('_',' '))}</b><p>${E(n.body)}</p><small>${E(stamp(n.created_at))}</small></article>`).join('')||empty('No Marketplace updates yet','Purchases, bookings and messages appear here.'));return}
 if(a==='read'){await write('read');action('notifications');render();return}
 if(a==='onboard'){onboard();return}
 if(a==='book'){book(id);return}
 if(a==='find-slots'){await findSlots(id);return}
 if(['confirm-booking','decline-booking','cancel-booking','complete-booking'].includes(a)){const status={'confirm-booking':'confirmed','decline-booking':'declined','cancel-booking':'cancelled','complete-booking':'completed'}[a];if(!confirm('Mark this booking '+status+'?'))return;await write('booking_status',{status},id);notice='Booking '+status+'. Any previously added personal calendar copy must be updated manually.';render();return}
 if(a==='calendar'){if(!confirm('Add this confirmed session to your personal timetable?'))return;await api('/api/marketplace/calendar',{booking:id,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone});feedback('Added to your timetable. Changes to this booking do not edit your personal calendar copy.');return}
 if(a==='booking-chat'){const r=await write('booking_conversation',{},id);await chat(r.id);return}
 if(a.startsWith('review-')){modal('Verified review',`${S('Rating','rating',[[5,'5 — Excellent'],[4,'4 — Good'],[3,'3 — Okay'],[2,'2 — Needs improvement'],[1,'1 — Poor']])}${T('Your review','body','','maxlength="2000"')}<p>One review per acquired note or completed booking.</p>`,v=>write('review',{...v,kind:a.slice(7)},id));return}
 if(a==='listing-reviews'){modal('Listing reviews',reviewList(listing(id).reviews));return}
 if(a.startsWith('report-')&&a!=='report-resolve'){modal('Report Marketplace content',T('Describe the issue','reason','','required maxlength="2000"'),v=>write('report',{...v,kind:a.slice(7)},id));return}
 if(a==='takedown'||a==='resolve-report'){const r=data.reports.find(r=>r.id===id);if(!confirm(a==='takedown'?'Remove this listing from public search? Existing acquisitions remain accessible.':'Resolve this report?'))return;await write('moderate',{listing:a==='takedown'?r.target:null},id);render();return}
 if(a==='fees'){modal('Marketplace platform fee',F('Fee % (no charges until provider configured)','fee',Number(data.settings.fee_basis_points)/100,'number','min="0" max="100" step="0.01"'),v=>write('settings',{fee_basis_points:Math.round(Number(v.fee)*100)}));return}
 }
 async function onShow(name){document.body.classList.toggle('marketplace-open',name.startsWith('marketplace-'));if(!name.startsWith('marketplace-'))return;page=name.slice(12);if(!['notes','tutors'].includes(page))return;root().innerHTML='<p role="status">Loading Marketplace…</p>';try{await refresh();render()}catch(e){root().innerHTML=`<p role="alert">${E(e.message)}</p>`}}
 function init(){nav()}
 setInterval(async()=>{if(document.hidden||!document.body.classList.contains('marketplace-open')||busy)return;try{if(dialog.open&&dialog.querySelector('#mkMessages'))await loadMessages();const latest=await api();data=latest;const n=document.getElementById('mkNoticeCount'),m=document.getElementById('mkMessageCount');if(n)n.textContent=data.notifications.filter(n=>!n.read).length;if(m)m.textContent=data.conversations.reduce((n,c)=>n+c.unread,0)}catch{}},10000);
 return {init,onShow,canLeave:()=>{if(dialog.open&&dirty&&!confirm('Discard unsaved Marketplace changes?'))return false;dirty=false;dialog.close();return true}};
}
g.StudentMarketplace={create};
})(window);
