const assert=require('node:assert/strict'),fetch=require('../support/authenticated_fetch.js');
(async()=>{
 const base='http://127.0.0.1:'+process.argv[2],debug='http://127.0.0.1:'+process.argv[3];
 const pages=await global.fetch(debug+'/json/list').then(r=>r.json()),ws=new WebSocket(pages.find(p=>p.type==='page').webSocketDebuggerUrl);
 await new Promise(r=>ws.onopen=r);let id=0;const pending=new Map();
 ws.onmessage=({data})=>{const m=JSON.parse(data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(m.error.message)):p.resolve(m.result)}};
 const call=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}))});
 const js=async expression=>{const r=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};
 const wait=async q=>{for(let i=0;i<100;i++){if(await js(q))return;await new Promise(r=>setTimeout(r,100))}throw Error('Timeout: '+q+'; '+await js("document.querySelector('.qr-dialog [data-qr-error]')?.textContent"))};
 await fetch.browser(base,call);await call('Page.enable');await call('Page.navigate',{url:base});

 await wait("!!window.portalQuickReview && !!document.querySelector('#portalDashboard .week-hour')");
 await js("window.confirm=()=>true;parseAndAddFlashcards('Front: Original prompt\\nBack: Original answer\\nExplain: Keep this','Networks','flashcardImportMessage','flashcardInput');saveQueue");
 assert.equal(await js("state.flashcards.Networks[0].front"),'Original prompt');
 await js("startFlashcards('Networks')");
 assert.equal(await js("document.getElementById('flashcardFrontText').textContent"),'Original prompt');
 await js("portalQuickReview.open('Networks')");
 await wait("!!document.querySelector('.qr-library [data-qr=import]')");
 const click=async a=>js("document.querySelector('.qr-dialog[open] [data-qr="+JSON.stringify(a)+"]').click()");
 await js("document.querySelector('.qr-library [data-qr=import]').click()");
 await wait("!!document.querySelector('#qrImportText')");
 const fill=async text=>js("document.querySelector('#qrImportText').value="+JSON.stringify(text)+";document.querySelector('#qrImportText').dispatchEvent(new Event('input'))");
 await fill('Points:\n- Broken');await click('preview');await wait("!!document.querySelector('.qr-error-box')");
 await click('jump');assert.equal(await js("document.activeElement.id"),'qrImportText');
 const source='Title: Network essentials\nPoints:\n'+Array.from({length:13},(_,i)=>'- **Fact '+(i+1)+'**: use `command` safely.').join('\n');
 await fill(source);await click('preview');await wait("document.querySelector('#qrPreview').children.length===4");
 assert.equal(await js("document.querySelector('#qrConfirmImport').disabled"),false);
 await click('confirm-import');await wait("!!document.querySelector('.qr-reader')");
 await wait("(async()=> (await fetch('/api/quick-review').then(r=>r.json())).decks[0].pages[0].viewed_at!==null)()");
 assert.equal(await js("document.querySelectorAll('.qr-page>ol>li').length"),5);
 const screenshot=async name=>{const r=await call('Page.captureScreenshot',{format:'png'});require('node:fs').writeFileSync(require('node:path').join(require('node:os').tmpdir(),name),Buffer.from(r.data,'base64'))};
 await screenshot('quick-review-desktop.png');
 await click('memorise');await wait("document.querySelector('[data-qr=memorise]').getAttribute('aria-pressed')==='true'");
 await click('next');await wait("document.querySelector('.qr-reader-meta b').textContent==='Page 2 of 3'");
 await click('close');await wait("!document.querySelector('.qr-dialog[open]')");
 await js("window.beforeQuickReload=true");await call('Page.reload');await wait("!window.beforeQuickReload && !!window.portalQuickReview && !!document.querySelector('#portalDashboard .week-hour')");
 await js("window.confirm=()=>true;portalQuickReview.open('Networks')");
 await wait("!!document.querySelector('.qr-library [data-qr=read]')");await js("document.querySelector('.qr-library [data-qr=read]').click()");
 await wait("document.querySelector('.qr-reader-meta')?.textContent.includes('Page 2 of 3')");
 await js("document.querySelector('.qr-dialog').dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}))");
 await wait("document.querySelector('.qr-reader-meta b').textContent==='Page 3 of 3'");
 await click('finish');await wait("!!document.querySelector('.qr-finished')");
 await click('restart');await wait("document.querySelector('.qr-reader-meta')?.textContent.includes('Page 1 of 3')");
 for(const dark of [false,true]){
  await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  await js("document.body.classList.toggle('dark',"+dark+")");
  assert(await js("(()=>{const d=document.querySelector('.qr-dialog'),n=document.querySelector('.qr-reader-nav').getBoundingClientRect();return d.scrollWidth<=d.clientWidth+1&&n.bottom<innerHeight&&n.top>0})()"));
  await screenshot(dark?'quick-review-mobile-dark.png':'quick-review-mobile-light.png');
 }
 await click('close');await wait("!document.querySelector('.qr-dialog[open]')");
 await js("document.querySelector('.qr-library [data-qr=manage]').click()");await wait("!!document.querySelector('#qrEditName')");
 await js("document.querySelector('#qrEditName').value='Renamed deck';document.querySelector('[data-qr-point]').value='Edited important point'");
 await click('page-down');await click('save-deck');await wait("!document.querySelector('.qr-dialog[open]')");
 const data=await fetch(base+'/api/quick-review').then(r=>r.json()),deck=data.decks[0];
 assert.equal(deck.title,'Renamed deck');assert.equal(deck.pages[1].points[0].content,'Edited important point');assert.equal(deck.pages[1].memorised,0);assert.equal(deck.progress.sessions,1);
 const progress=await fetch(base+'/api/study-progress?subject=computing&topic=Networks').then(r=>r.json());assert.equal(progress.quick_review.pages,3);
 const math=await fetch(base+'/api/study-progress?subject=math').then(r=>r.json());assert.equal(math.quick_review.pages,0);
 await js("portalNotes.open('computing','n0')");await wait("!!document.querySelector('#notebookDocument')");
 await js("document.querySelector('[data-action=tab-study]').click()");
 await wait("!!document.querySelector('[data-study-tool=quick-review]')");
 await js("document.querySelector('[data-study-tool=quick-review]').click()");
 await wait("!!document.querySelector('.qr-source')");
 assert(await js("document.querySelector('.qr-source').textContent.length>0"));
 assert.equal(await js("!!document.querySelector('#qrPreview')"),true);
 await click('close');await wait("!document.querySelector('.qr-dialog[open]')");
 await js("document.querySelector('.qr-tabs [data-qr=flip]').click()");
 const preserved=await fetch(base+'/api/state').then(r=>r.json());
 const notesBefore=await fetch(base+'/api/portal').then(r=>r.json());
 await js("window.confirm=()=>false;openManageFlashcardsModal('Networks');document.querySelector('#deleteFlashcardTopicBtn').click()");
 assert.equal(await js("state.flashcards.Networks.length"),1);
 await js("window.confirm=()=>true;document.querySelector('#deleteFlashcardTopicBtn').click();saveQueue");
 assert.equal(await js("document.querySelectorAll('#flashcardTopics [data-manage-flashcards]').length"),0);
 assert.equal(await js("state.flashcardStudy.topic"),null);
 const afterDelete=await fetch(base+'/api/state').then(r=>r.json());
 assert.equal(afterDelete.flashcards.Networks.length,0);
 assert.deepEqual(afterDelete.topics,preserved.topics);assert.deepEqual(afterDelete.subjects,preserved.subjects);
 assert.deepEqual((await fetch(base+'/api/portal').then(r=>r.json())).notes,notesBefore.notes);
 assert.deepEqual((await fetch(base+'/api/quick-review').then(r=>r.json())).decks,data.decks);
 await js("window.beforeDeleteReload=true");await call('Page.reload');
 await wait("!window.beforeDeleteReload && !!window.portalQuickReview && !!document.querySelector('#portalDashboard .week-hour')");
 await js("showView('flashcards')");
 assert.equal(await js("document.querySelectorAll('#flashcardTopics [data-manage-flashcards]').length"),0);
 await js("parseAndAddFlashcards('Front: New card\\nBack: New answer','Networks','flashcardImportMessage','flashcardInput');saveQueue");
 assert.equal(await js("document.querySelectorAll('#flashcardTopics [data-manage-flashcards]').length"),1);
 console.log('PASS flashcard topic deletion: cancel, remove from list, persistence after reload, study reset, preserve quizzes/notes/Quick Review, restore by adding cards.');
 await js("parseAndAddFlashcards('Front: Algebra prompt\\nBack: Algebra answer','Algebra','flashcardImportMessage','flashcardInput');saveQueue");
 await fetch(base+'/api/quick-review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'import',data:{topic_name:'Algebra',text:'Title: Math only\nPoints:\n- Algebra fact'}})});
 await js("openSubject('computing');document.querySelector('#view-subject [data-subject-tab=flashcards]').click()");
 await wait("!!document.querySelector('#subjectFlashcards #flashcardTopics')");
 assert.equal(await js("currentView"),'subject');
 assert.equal(await js("document.querySelector('#view-subject [data-subject-tab=flashcards]').classList.contains('active')"),true);
 assert.deepEqual(await js("[...document.querySelectorAll('#subjectFlashcards [data-manage-flashcards]')].map(b=>b.dataset.manageFlashcards)"),['Networks']);
 await js("document.querySelector('#subjectFlashcards [data-study-flashcards]').click();document.querySelector('#flashcardBackBtn').click()");
 await wait("currentView==='subject' && !document.querySelector('#subjectFlashcards').hidden");
 await js("document.querySelector('#subjectFlashcards [data-qr=quick]').click()");
 await wait("document.querySelector('#qrSubject')?.disabled && document.querySelectorAll('#subjectFlashcards .qr-deck').length===1");
 assert(!await js("document.querySelector('#subjectFlashcards .qr-decks').textContent.includes('Math only')"));
 await js("document.querySelector('#subjectFlashcards [data-qr=import]').click()");await wait("!!document.querySelector('#qrImportTopic')");
 assert.deepEqual(await js("[...document.querySelector('#qrImportTopic').options].map(o=>o.value)"),['Networks']);await click('close');
 await js("document.querySelector('#view-subject [data-subject-tab=notes]').click()");
 await wait("currentView==='notes' && !!document.querySelector('#portalNotes [data-subject-tab=flashcards]')");
 await js("document.querySelector('#portalNotes [data-subject-tab=flashcards]').click()");
 await wait("currentView==='subject' && !document.querySelector('#subjectFlashcards').hidden");
 await js("openSubject('math');document.querySelector('#view-subject [data-subject-tab=flashcards]').click()");
 await wait("document.querySelector('#subjectFlashcards h2')?.textContent.includes('Math')");
 assert.deepEqual(await js("[...document.querySelectorAll('#subjectFlashcards [data-manage-flashcards]')].map(b=>b.dataset.manageFlashcards)"),['Algebra']);
 await js("document.querySelector('#subjectFlashcards [data-qr=quick]').click()");
 await wait("document.querySelector('#subjectFlashcards .qr-decks')?.textContent.includes('Math only')");
 assert.equal(await js("document.querySelectorAll('#subjectFlashcards .qr-deck').length"),1);
 await js("document.querySelector('.nav [data-view=flashcards]').click()");
 await wait("currentView==='flashcards' && !!document.querySelector('#view-flashcards #flashcardTopics')");
 assert.equal(await js("document.querySelectorAll('#flashcardTopics [data-manage-flashcards]').length"),2);
 await js("document.querySelector('#view-flashcards [data-qr=quick]').click()");
 await wait("document.querySelectorAll('#view-flashcards .qr-deck').length===2");
 assert.equal(await js("document.querySelector('#qrSubject').disabled"),false);
 console.log('PASS subject flashcards: inline subject tabs, scoped flip/Quick Review decks/import, study return, Notes navigation, switching subjects, navbar full library.');
 console.log('PASS Quick Review: flip import/study, validation, preview, pagination, reading, memorisation, resume, finish, edit/reorder, scoped progress, mobile light/dark, Notes integration.');
 ws.close();
})().catch(e=>{console.error(e);process.exit(1)});
