const assert=require('node:assert/strict'),fetch=require('../support/authenticated_fetch.js');
(async()=>{
 const base='http://127.0.0.1:'+process.argv[2],debug='http://127.0.0.1:'+process.argv[3];
 const pages=await global.fetch(debug+'/json/list').then(r=>r.json()),ws=new WebSocket(pages.find(p=>p.type==='page').webSocketDebuggerUrl);
 await new Promise(r=>ws.onopen=r);let id=0;const pending=new Map();
 ws.onmessage=({data})=>{const m=JSON.parse(data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(m.error.message)):p.resolve(m.result)}};
 const call=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}))});
 const js=async expression=>{const r=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};
 const wait=async q=>{for(let i=0;i<100;i++){if(await js(q))return;await new Promise(r=>setTimeout(r,100))}throw Error('Timeout: '+q)};
 await fetch.browser(base,call);await call('Page.enable');await call('Page.navigate',{url:base});
 await wait("typeof startQuiz==='function' && !!document.querySelector('#portalDashboard .week-hour')");
 await js("state.topics['Mastery Test']=[{question:'Choose A',choices:{A:'Correct',B:'Wrong'},answer:'A',explain:'A is correct'}];state.progress['Mastery Test']={answered:0,correct:0};save();saveQueue");
 const start=async(mode,target)=>{await js("startQuiz('Mastery Test')");await wait("!!document.querySelector('#quizTypeChoice')");await js(`document.querySelector('#quizTypeChoice').value='${mode}';document.querySelector('#masteryTarget').value='${target}';document.querySelector('#beginChosenQuiz').click()`);await wait("document.querySelector('#view-quiz').classList.contains('active')")};
 const answer=async()=>{await js("submitAnswer('A');submitAnswer('A');saveQueue");await js('finishQuiz();saveQueue')};
 await start('normal',2);await answer();assert.equal(await js("QuizMastery.count(state.topics['Mastery Test'][0])"),0);
 await start('mastery',2);await answer();assert.equal(await js("QuizMastery.count(state.topics['Mastery Test'][0])"),1);assert.equal(await js("!!document.querySelector('#deleteMasteredQuestions')"),false);
 await start('mastery',2);await answer();await wait("!!document.querySelector('#deleteMasteredQuestions')");assert.equal(await js("QuizMastery.count(state.topics['Mastery Test'][0])"),2);
 await js("closeModal();window.beforeMasteryReload=true");await call('Page.reload');await wait("!window.beforeMasteryReload && typeof state!=='undefined' && state.quizSettings?.['Mastery Test']?.target===2");
 await start('mastery',2);await answer();await wait("!!document.querySelector('#deleteMasteredQuestions')");
 await js("document.querySelector('[data-mastered]').checked=true;document.querySelector('#deleteMasteredQuestions').click()");await wait("!document.querySelector('#deleteMasteredQuestions')");
 assert.equal(await js("state.topics['Mastery Test'].length"),0);assert.equal(await js("state.latestResults['Mastery Test'].correct"),1);
 const saved=await fetch(base+'/api/state').then(r=>r.json());assert.equal(saved.topics['Mastery Test'].length,0);assert.equal(saved.latestResults['Mastery Test'].questions.length,1);
 await js("state.topics['Manage Test']=[{question:'First',choices:{A:'Yes',B:'No'},answer:'A'},{question:'Second',choices:{A:'Yes',B:'No'},answer:'B'}];state.flashcards['Manage Test']=[{id:'keep',front:'Keep',back:'Me'}];state.sessions['Manage Test']={currentIndex:0,answers:{0:'A'},flags:{0:true}};openTopic('Manage Test')");
 assert(await js("!!document.querySelector('#topicModes [data-manage-quiz]')"));
 await js("document.querySelector('#topicModes [data-manage-quiz]').click()");
 assert.equal(await js("document.querySelectorAll('[data-image-index]').length"),2);
 await js("document.querySelector('[data-move-question=\"0\"][data-step=\"1\"]').click();saveQueue");
 assert.equal(await js("state.topics['Manage Test'][1].question"),'First');assert.equal(await js("state.sessions['Manage Test'].answers[1]"),'A');assert.equal(await js("state.sessions['Manage Test'].currentIndex"),1);
 await js("document.querySelector('[data-duplicate-question=\"0\"]').click();saveQueue");assert.equal(await js("state.topics['Manage Test'].length"),3);
 await js("window.confirm=()=>true;document.querySelector('[data-edit-question=\"0\"]').click();document.querySelector('#managedQuestionText').value='Edited second question';document.querySelector('#managedEditSave').click()");await wait("!!document.querySelector('#managerQuestionSearch')");
 assert.equal(await js("state.topics['Manage Test'][0].question"),'Edited second question');assert.equal(await js("!!state.sessions['Manage Test']"),false);
 await js(`(async()=>{const canvas=document.createElement('canvas');canvas.width=4;canvas.height=4;const blob=await new Promise(r=>canvas.toBlob(r));const original=HTMLInputElement.prototype.click;HTMLInputElement.prototype.click=function(){if(this.type==='file'){const dt=new DataTransfer();dt.items.add(new File([blob],'test.png',{type:'image/png'}));this.files=dt.files;this.onchange()}else original.call(this)};try{document.querySelector('[data-image-index="0"]').click()}finally{HTMLInputElement.prototype.click=original}})()`);
 await wait("!!document.querySelector('[data-remove-image-index=\"0\"]')");await js('saveQueue');assert(await js("state.topics['Manage Test'][0].image.src.startsWith('data:image/png')"));
 await js("document.querySelector('[data-remove-image-index=\"0\"]').click();saveQueue");assert.equal(await js("!!state.topics['Manage Test'][0].image"),false);
 await js("document.querySelector('#managerQuestionSearch').value='Edited second';document.querySelector('#managerQuestionSearch').dispatchEvent(new Event('input'))");assert.equal(await js("document.querySelectorAll('[data-manager-row]:not([hidden])').length"),1);
 await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});assert(await js("document.querySelector('.modal').scrollWidth<=document.querySelector('.modal').clientWidth"));
 await js("document.querySelector('#managerDeleteQuiz').click();saveQueue");assert.equal(await js("state.topics['Manage Test'].length"),0);assert.equal(await js("state.flashcards['Manage Test'].length"),1);
 console.log('PASS mastery and management browser: type selection, persistence, confirmed deletion, visible manager, reorder/checkpoint remapping, duplicate, edit, search, mobile, quiz-only deletion preserving flashcards.');ws.close();
})().catch(e=>{console.error(e);process.exit(1)});
