(function(g){
 'use strict';
 const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const codes=['AUD','MYR','JPY','USD','EUR','GBP','SGD','NZD','CNY','KRW','THB','IDR'];
 const labels=['🇦🇺 AUD (A$)','🇲🇾 MYR (RM)','🇯🇵 JPY (¥)','🇺🇸 USD ($)','🇪🇺 EUR (€)','🇬🇧 GBP (£)','🇸🇬 SGD (S$)','🇳🇿 NZD (NZ$)','🇨🇳 CNY (¥)','🇰🇷 KRW (₩)','🇹🇭 THB (฿)','🇮🇩 IDR (Rp)'];
 const colors=['#38bdf8','#2dd4bf','#fbbf24','#a78bfa','#fb7185','#818cf8','#4ade80','#c084fc','#f472b6','#22d3ee','#94a3b8'];
 const day=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
 const button=(label,action,id='')=>`<button type="button" class="fin-button" data-fin="${action}" data-id="${E(id)}">${label}</button>`;
 const field=(label,name,type='text',value='',attrs='')=>`<label>${label}<input name="${name}" type="${type}" value="${E(value)}" ${attrs}></label>`;
 const select=(label,name,values,value)=>`<label>${label}<select name="${name}">${values.map(v=>{const [k,n]=Array.isArray(v)?v:[v,v];return `<option value="${E(k)}" ${String(value)===String(k)?'selected':''}>${E(n)}</option>`}).join('')}</select></label>`;
 const card=(title,body,action='',cls='')=>`<section class="fin-card ${cls}"><header><h3>${title}</h3>${action}</header>${body}</section>`;
 const empty=(title,detail,action='')=>`<div class="fin-empty"><b>${title}</b><p>${detail}</p>${action}</div>`;
 const formula='Estimate = selected month income − recorded expenses − goal contributions − remaining active monthly goal plans − protected commitments − paid bills not recorded as expenses. Per category, commitments use the larger of remaining monthly budget or unpaid bills due through month end (including overdue bills), avoiding double-counting. No bank balance or past-month cash is assumed. Weekly-only limits are not reserved in this monthly estimate.';
 function create(o){
  let data=null,page='overview',anchor=day(new Date()),period='month',busy=false,notice='',expanded=true,loaded=false;
  let converter={from:'AUD',to:'MYR',amount:'100'},filters={kind:'',category:'',from:'',to:'',search:''};
  try{expanded=localStorage.getItem('portal.financeExpanded')!=='false'}catch{}
  const pages=['overview','goals','budget','currency','insights','transactions'];
  for(const name of pages){const el=document.createElement('section');el.className='view finance-view';el.id='view-finance-'+name;document.querySelector('.main').append(el)}
  const dialog=document.createElement('dialog');dialog.className='fin-dialog';document.body.append(dialog);let dirty=false;
  dialog.addEventListener('input',()=>dirty=true);dialog.addEventListener('cancel',e=>{if(dirty&&!confirm('Discard unsaved Finance changes?'))e.preventDefault()});
  const p=()=>data?.profile||{enabled:false,currency:'AUD',period:'month'};
  const factor=c=>['JPY','KRW'].includes(c||p().currency)?1:100;
  const money=(n,c=p().currency)=>new Intl.NumberFormat(undefined,{style:'currency',currency:c}).format(n/factor(c));
  const amount=n=>String((n||0)/factor());
  const amountField=(label,name,value=0,zero=false)=>field(label+' ('+p().currency+')',name,'number',amount(value),`min="${zero?0:1/factor()}" step="${1/factor()}" required`);
  const dateText=s=>s?new Date(s+'T12:00:00').toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'}):'—';
  const root=()=>document.getElementById('view-finance-'+page);
  const go=name=>o.show('finance-'+name);
  async function request(url,payload){const r=await fetch(url,payload?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}:{}),result=await r.json();if(!r.ok||result.ok===false)throw Error(result.error||'Finance request failed.');return result}
  async function refresh(){data=await request('/api/finance?date='+anchor);if(!loaded){period=p().period;converter.from=p().currency;loaded=true}syncNav()}
  async function save(action,values={},id){if(busy)throw Error('Please wait for the current save.');busy=true;try{await request('/api/finance',{action,data:values,id});try{await refresh();notice='Saved'}catch(err){notice='Saved, but the refreshed list could not load. Reopen Finance to reload your records.'}renderSettings()}finally{busy=false}}
  function feedback(message){notice=message;document.querySelectorAll('[data-fin-status]').forEach(e=>e.textContent=message)}
  function close(){if(dirty&&!confirm('Discard unsaved Finance changes?'))return;dialog.close();dirty=false}
  function modal(title,body,submit){dirty=false;dialog.innerHTML=`<header><h2>${E(title)}</h2><button type="button" data-close aria-label="Close">×</button></header><form>${body}<p class="fin-error" role="alert"></p><footer>${submit?'<button class="fin-button fin-primary" type="submit">Save</button>':''}<button class="fin-button" type="button" data-close>Close</button></footer></form>`;dialog.querySelectorAll('[data-close]').forEach(b=>b.onclick=close);dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();if(busy)return;const b=e.submitter||e.target.querySelector('[type=submit]');if(!submit||!b)return;b.disabled=true;try{await submit(Object.fromEntries(new FormData(e.target)));dirty=false;dialog.close();render()}catch(err){dialog.querySelector('.fin-error').textContent=err.message}finally{b.disabled=false}};bind(dialog);if(!dialog.open)dialog.showModal()}
  function syncNav(){let nav=document.getElementById('financeNav');if(!nav){nav=document.createElement('div');nav.id='financeNav';nav.className='finance-nav';document.querySelector('.nav [data-view=tutor]').before(nav)}const focusedToggle=document.activeElement?.id==='financeToggle';nav.hidden=!p().enabled;nav.innerHTML=`<div class="module-nav-head"><button type="button" data-view="finance-overview" class="${document.getElementById('view-finance-overview').classList.contains('active')?'active':''}" aria-label="Finance overview"><span aria-hidden="true">▤</span><span>Finance</span></button><button type="button" id="financeToggle" aria-controls="financeSubnav" aria-expanded="${expanded}" aria-label="Expand or collapse Finance"><span class="fin-chevron" aria-hidden="true">${expanded?'⌃':'›'}</span></button></div><div id="financeSubnav" ${expanded?'':'hidden'}>${pages.filter(n=>n!=='transactions'&&n!=='overview').map(n=>`<button data-view="finance-${n}" class="${document.getElementById('view-finance-'+n).classList.contains('active')?'active':''}">• &nbsp; ${n[0].toUpperCase()+n.slice(1)}</button>`).join('')}</div>`;nav.querySelector('#financeToggle').onclick=()=>{expanded=!expanded;try{localStorage.setItem('portal.financeExpanded',expanded)}catch{}syncNav();document.getElementById('financeToggle').focus()};nav.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>o.show(b.dataset.view));if(focusedToggle)document.getElementById('financeToggle').focus()}

function balanceCard(){const b=data.balance,a=data.account;return `<section class="fin-wallet"><div class="fin-wallet-top"><div><span class="fin-eyebrow">YOUR MONEY · ${E(p().currency)}</span><h2>Recorded balance</h2><strong class="fin-wallet-amount" data-recorded-balance>${money(b.recorded)}</strong><p>As of ${dateText(b.as_of)} · entered records, not a bank connection</p></div><div class="fin-actions">${button(a.configured?'Edit opening balance':'Set opening balance','account')}${button('+ Income','income')}${button('− Expense','expense')}${button('View statement →','go-transactions')}</div></div><div class="fin-wallet-stats"><div><small>Allocated to goals</small><b>${money(b.reserved)}</b></div><div><small>Unallocated cash</small><b>${money(b.unallocated)}</b></div><div><small>After this month's commitments</small><b class="${b.available<0?'fin-negative':''}">${money(b.available)}</b></div></div>${!a.configured?'<p class="fin-plan-warning">Starting from zero. Set the balance you had before your first recorded transaction for a complete picture.</p>':''}${b.available<0?'<p class="fin-plan-warning">Your recorded cash does not cover the current goal allocations and month commitments. Review your plan below.</p>':''}<details><summary>Understand these balances</summary><p>Recorded balance = opening balance + received income − expenses − paid bills not already recorded as expenses. Future-dated entries are excluded. Goal savings stay inside that total; they are reserved, not spent. Include existing goal savings in your opening balance.</p><p>After commitments = recorded balance − saved goal allocations − the larger of unspent budget or unpaid bills plus future-dated expenses per category through month end − remaining planned goal contributions. A negative number is a shortfall, not zeroed out.</p><p>Opening: ${money(a.opening_amount)} on ${dateText(a.opening_date)}. ${b.excluded_earlier} older entries excluded; opening balance is before entries on that date.</p></details></section>`}
  function goalTotals(){const t=data.goal_totals;return `<div class="fin-goal-totals" data-goal-totals><div><small>Active goals</small><strong>${t.active}</strong></div><div><small>Total to save / week</small><strong>${money(t.weekly)}</strong></div><div><small>Total to save / month</small><strong>${money(t.monthly)}</strong></div><div><small>Your planned / month</small><strong>${money(t.planned_monthly)}</strong></div><p>Required saving to reach target dates. Paused and completed goals are excluded.${t.overdue?' '+t.overdue+' overdue goal(s) need '+money(t.overdue_remaining)+'; update their dates to include them in the weekly/monthly requirement.':''}</p></div>`}
  function cashPlan(){const b=data.balance;return card('Next 30 days · cash-flow plan',`<div class="fin-plan-lines"><span>Recorded balance<b>${money(b.recorded)}</b></span><span>Expected scheduled income<b>+ ${money(b.expected_income)}</b></span><span>Other future-dated entries (net)<b>${money(b.planned_net)}</b></span><span>Unpaid bills, including overdue<b>− ${money(b.upcoming_bills)}</b></span><span class="fin-plan-total">Projected total · ${dateText(b.forecast_end)}<b class="${b.projected<0?'fin-negative':''}">${money(b.projected)}</b></span></div><p class="fin-plan-caption">A forecast, not spendable money. Excludes unrecorded day-to-day spending. Savings allocations do not leave your total balance.${b.overdue_income?' '+money(b.overdue_income)+' in due/unconfirmed pay is excluded; confirm receipt below.':''}</p>`)}
  function paySchedules(){const pending=data.income_occurrences;const row=r=>`<article class="fin-transaction"><div><b>${E(r.description)}</b><small>${dateText(r.due_date)} · ${E(r.frequency)} · ${r.overdue?'Unconfirmed / overdue':'Expected'}</small></div><strong>${money(r.amount)}</strong>${r.can_receive?`<button class="fin-button" data-fin="receive-income" data-id="${E(r.id)}" data-due="${r.due_date}">Mark received</button>`:'<small>Planned</small>'}</article>`;return card('Payday planner',`<p class="fin-plan-caption">Scheduled pay enters your balance only when you mark it received. Never enter the same payment twice.</p>${pending.length?pending.slice(0,5).map(row).join(''):empty('No pay awaiting confirmation.','Add weekly or monthly income to plan your next payday.')}${pending.length>5?`<details><summary>Show ${pending.length-5} more pending payments</summary>${pending.slice(5).map(row).join('')}</details>`:''}<details><summary>Manage income schedules (${data.income_schedules.length})</summary>${data.income_schedules.map(s=>`<article class="fin-transaction"><div><b>${E(s.description)}</b><small>${money(s.amount)} · ${E(s.frequency)} · ${s.paused?'Paused':'Active'}</small></div>${button('Edit','income-schedule',s.id)}</article>`).join('')}</details>`,button('+ Add income','income'))}
  function accountForm(){const a=data.account;modal('Set your opening balance',`${field('Balance before transactions on the date below ('+p().currency+')','opening_amount','number',amount(a.opening_amount),'step="'+1/factor()+'" required')}${field('Starting date','opening_date','date',a.configured?a.opening_date:(data.transactions.map(t=>t.date).sort()[0]||day(new Date())),'required min="2000-01-01" max="'+day(new Date())+'"')}<p>This is your starting cash, not another income entry. Include money already allocated to goals. Existing transactions on or after this date are added/subtracted; earlier entries stay in history but are excluded. Use a negative value for an overdraft. Changing this recalculates your balance without deleting records.</p>`,v=>save('account',v))}
  function incomeScheduleForm(id){const s=data.income_schedules.find(x=>x.id===id);modal('Edit income schedule',`<div class="fin-form-grid">${field('Income source','description','text',s.description,'required')}${amountField('Pay amount','amount',s.amount)}${select('Frequency','frequency',[['weekly','Weekly'],['monthly','Monthly']],s.frequency)}${field('First pay date','start_date','date',s.start_date,'required')}${field('Last pay date (optional)','end_date','date',s.end_date||'')}${select('Status','paused',[['0','Active'],['1','Paused']],s.paused)}</div>${field('Notes','notes','text',s.notes)}<p>Edits affect unpaid occurrences only. Received transactions are preserved. Pause an old schedule before starting a replacement.</p>${button('Delete schedule · keep received income','remove-income-schedule',s.id)}`,v=>save('income-schedule',v,id))}
  function receiveIncome(id,due){const s=data.income_schedules.find(x=>x.id===id);modal('Confirm received: '+s.description,`<p>Scheduled for ${dateText(due)}. Confirm only money actually received; this adds one income transaction.</p>${amountField('Actual amount received','amount',s.amount)}${field('Received date','paid_date','date',day(new Date()),'required max="'+day(new Date())+'"')}`,v=>save('receive-income',{...v,due_date:due},id))}
function summary(){const s=data.summary,b=data.balance;return `<div class="fin-summary">${[['◫','Recorded Monthly Income',b.period_income,'mint'],['▰','Recorded Monthly Spending',b.period_spending,'pink'],['◉','Monthly Net Cash Flow',b.period_income-b.period_spending,'blue'],['◇','Planned Goal Savings / Month',data.goal_totals.planned_monthly,'violet']].map(([icon,title,value,tone])=>`<article class="fin-stat ${tone}"><span class="fin-stat-icon" aria-hidden="true">${icon}</span><div><small>${title}</small><strong>${money(value)}</strong>${title.startsWith('Estimated')?`<details><summary>How is this estimated?</summary><p>${formula}</p></details>`:'<small>'+dateText(s.month_start)+' – '+dateText(b.as_of)+'</small>'}</div></article>`).join('')}</div>`}
  function goalCards(compact=false){const goals=compact?data.goals.slice(0,2):data.goals;if(!goals.length)return empty('No savings goals yet.','Create a goal for a trip, purchase or future plan.',button('+ Create Goal','goal'));return `<div class="fin-goals">${goals.map(g=>{const percent=Math.round(g.saved/g.target*100);return `<article class="fin-goal"><div class="fin-goal-art ${g.data.type==='travel'?'travel':''}" aria-hidden="true">${E(g.data.icon||'🎯')}</div><div class="fin-goal-main"><h4>${E(g.name)} ${g.paused?'<small>Paused</small>':''}</h4><p>${E(g.data.type==='travel'?g.data.travel.destination:g.data.notes)||'A little progress, one contribution at a time.'}</p><progress max="${Math.max(g.target,g.saved)}" value="${g.saved}" aria-label="${E(g.name)} savings progress"></progress><div class="fin-spread"><span>${money(g.saved)} / ${money(g.target)}</span><b>${percent}%</b></div><div class="fin-actions">${button('+ Contribution','contribute',g.id)}${button('Edit','goal',g.id)}${!compact?button('History','goal-history',g.id):''}</div></div><dl><dt>Target date</dt><dd>${dateText(g.target_date)}</dd><dt>Save per week</dt><dd>${g.remaining===0?'Reached':g.weekly_needed===null?'Target date passed':money(g.weekly_needed)}</dd><dt>Save per month</dt><dd>${g.remaining===0?'Reached':g.monthly_needed===null?'Target date passed':money(g.monthly_needed)}</dd>${!compact?`<dt>Remaining</dt><dd>${money(g.remaining)}</dd><dt>At planned contribution</dt><dd>${g.paused?'Paused':g.estimated_completion?dateText(g.estimated_completion):'Set a monthly contribution'}</dd>`:''}</dl></article>`}).join('')}</div>`}
  function budgetCards(){if(!data.budgets.length)return empty('Create your first budget.','Set independent weekly and monthly limits, especially for food and groceries.',button('+ Create Budget','budget'));return `<div class="fin-budget-list">${data.budgets.map(b=>{const limit=b[period==='week'?'weekly':'monthly'],spent=b[period==='week'?'weekly_spent':'monthly_spent'],remaining=limit-spent;return `<article class="fin-budget ${remaining<0?'over':''}"><div><b>${E(b.category)}</b><small>${money(b.weekly)}/week · ${money(b.monthly)}/month</small></div><div><progress max="${Math.max(limit,spent,1)}" value="${spent}" aria-label="${E(b.category)} budget used"></progress><small>${money(spent)} / ${money(limit)} · ${limit?Math.round(spent/limit*100)+'%':'No limit allocated'}</small><b>${remaining<0?money(-remaining)+' over budget':money(remaining)+' remaining '+(period==='week'?'this week':'this month')}</b></div>${button('Edit','budget',b.id)}</article>`}).join('')}</div>`}
  function currencyCard(){const choices=codes.map((c,i)=>[c,labels[i]]);return `<div class="fin-converter"><div class="fin-currency-select">${select('From','fx_from',choices,converter.from)}${button('⇄','reverse')}${select('To','fx_to',choices,converter.to)}</div>${field('Amount','fx_amount','number',converter.amount,'min="0" step="any"')}<div class="fin-converted" data-conversion aria-live="polite"></div>${button('↻ Update Rates','rates')}<small>Updates only when you ask. Switching currencies uses the saved snapshot.</small><small>Rates may differ from banks, cards or payment services.</small></div>`}
  function updateConversion(){document.querySelectorAll('.finance-view.active [data-conversion]').forEach(el=>{const snapshot=data.rates,base=snapshot?.base;const rate=c=>c===base?1:Number(snapshot?.data[c]?.rate);const ratio=converter.from===converter.to?1:rate(converter.to)/rate(converter.from),n=Number(converter.amount);el.innerHTML=Number.isFinite(ratio)&&ratio>0&&Number.isFinite(n)&&n>=0?`<strong>${new Intl.NumberFormat(undefined,{style:'currency',currency:converter.to}).format(n*ratio)}</strong><span>1 ${E(converter.from)} = ${ratio.toLocaleString(undefined,{maximumFractionDigits:6})} ${E(converter.to)}</span>`:'<p>Currency rates have not been downloaded yet. Press Update Rates.</p>';if(snapshot){const dates=[snapshot.data[converter.from]?.rate_date,snapshot.data[converter.to]?.rate_date].filter(Boolean);el.insertAdjacentHTML('beforeend',`<small>${E(snapshot.provider)} · Last updated ${E(new Date(snapshot.fetched_at).toLocaleString())}</small><small>Source date${dates.length>1?'s':''}: ${E([...new Set(dates)].join(', ')||'base currency')}. Cached rates may be outdated.</small>`)}})}
  function snapshot(){const rows=data.summary.breakdown.filter(x=>x.amount),total=rows.reduce((s,x)=>s+x.amount,0);if(!total)return empty('No expenses recorded this week.','Your spending breakdown will appear here.',button('+ Add Expense','expense'));let start=0;const stops=rows.map((r,i)=>{const from=start;start+=r.amount/total*100;return `${colors[i%colors.length]} ${from}% ${start}%`});return `<div class="fin-snapshot"><div class="fin-donut" role="img" aria-label="Weekly spending ${E(money(total))}" style="background:conic-gradient(${stops.join(',')})"><div><strong>${money(total)}</strong><small>Total spent</small></div></div><ul>${rows.map((r,i)=>`<li><i style="background:${colors[i%colors.length]}"></i><span>${E(r.category)}</span><b>${Math.round(r.amount/total*100)}%</b></li>`).join('')}</ul></div><small>${dateText(data.summary.week_start)} – ${dateText(data.summary.week_end)}</small>`}
  function bills(compact=false){const list=compact?data.occurrences.filter(b=>!b.payment).slice(0,5):data.occurrences;return list.length?`<div class="fin-bills">${list.map(b=>`<article><div><b>${E(b.name)}</b><small>${dateText(b.due_date)} · ${E(b.frequency)}</small></div><strong>${money(b.amount)}</strong><span class="fin-bill-status ${b.occurrence_status}">${E(b.occurrence_status)}</span>${b.payment?'<small>Paid '+dateText(b.payment.paid_date)+'</small>':`<button class="fin-button" data-fin="pay" data-id="${E(b.id)}" data-due="${b.due_date}">Pay</button>`}${!compact?button('Edit schedule','bill',b.id):''}</article>`).join('')}</div>`:empty('No upcoming payments.','Add rent, subscriptions or another planned bill.',button('+ Add Bill','bill'))}
  function tips(){const result=[];for(const b of data.budgets){const remaining=b.weekly_remaining;if(b.weekly)result.push({title:b.category,text:remaining<0?`You have spent ${money(-remaining)} more than your weekly limit.`:`You have ${money(remaining)} remaining in this week's budget.`})}for(const r of data.summary.breakdown){if(r.previous>0)result.push({title:r.category,text:`You spent ${Math.round(Math.abs(r.amount-r.previous)/r.previous*100)}% ${r.amount>r.previous?'more':'less'} than last week (${money(r.amount)} versus ${money(r.previous)}).`})}const monthly=data.transactions.filter(t=>t.kind==='expense'&&t.date>=data.summary.month_start&&t.date<=data.summary.month_end),totals={};monthly.forEach(t=>totals[t.category]=(totals[t.category]||0)+t.amount);const highest=Object.entries(totals).sort((a,b)=>b[1]-a[1])[0];if(highest)result.push({title:'This month',text:highest[0]+' is your highest spending category: '+money(highest[1])+'.'});return result.length?`<div class="fin-tips">${result.slice(0,page==='overview'?3:30).map((t,i)=>`<article class="${i%2?'blue':'mint'}"><b>${E(t.title)}</b><p>${E(t.text)}</p></article>`).join('')}</div>`:empty('Your money story starts here.','Add expenses and budget limits to see descriptive insights based on your records.')}
  function historyRows(){const list=data.ledger.filter(t=>(!filters.kind||t.kind===filters.kind)&&(!filters.category||t.category===filters.category)&&(!filters.from||t.date>=filters.from)&&(!filters.to||t.date<=filters.to)&&((t.description+' '+t.notes).toLowerCase().includes(filters.search.toLowerCase()))).sort((a,b)=>b.date.localeCompare(a.date));return list.length?list.map(t=>`<article class="fin-transaction"><div><b>${E(t.description)}</b><small>${dateText(t.date)} · ${E(t.category)}${!t.included?' · '+(t.date>data.balance.as_of?'Planned / future':'Before opening balance'):''}</small></div><strong class="${t.kind==='income'?'fin-income':''}">${t.kind==='income'?'+':'−'}${money(t.amount,t.currency)}</strong><div class="fin-running"><small>Balance after entry</small><b>${t.running_balance===null?'—':money(t.running_balance)}</b></div>${t.source==='transaction'?button('Edit','transaction',t.id):'<small>Bill payment</small>'}</article>`).join(''):empty('No matching transactions.','Adjust your filters or add your first income or expense.')}
  function transactions(){return `<div class="fin-filters">${field('Search','search','search',filters.search)}${select('Type','kind',[['','All'],['income','Income'],['expense','Expenses']],filters.kind)}${select('Category','category',[['','All'],...data.categories],filters.category)}${field('From','from','date',filters.from)}${field('To','to','date',filters.to)}</div><div data-fin-history>${historyRows()}</div>`}
  function periodControls(){return `<div class="fin-period">${button('‹','previous')}${field('Period date','anchor','date',anchor)}${button('›','next')}${button('Today','today')}${select('Budget period','period',[['week','This Week'],['month','This Month']],period)}</div>`}
  function render(){if(!data||!root().classList.contains('active'))return;if(!p().enabled){goDisabled();return}const title={overview:'Finance Hub',goals:'Financial Goals',budget:'Budget Planner',currency:'Currency Converter',insights:'Spending Insights',transactions:'Transaction History'}[page];let body='';const actions=`<div class="fin-actions">${button('+ Add Expense','expense')}${button('+ Add Income','income')}${button('+ Create Goal','goal')}${button('↻ Update Rates','rates')}${button('View Full Budget','go-budget')}${button('Transactions','go-transactions')}</div>`;
   if(page==='overview')body=balanceCard()+summary()+`<div class="fin-wide">${cashPlan()}${paySchedules()}</div>`+`<div class="fin-overview"><div class="fin-wide">${card('◎ Financial Goals',goalTotals()+goalCards(true),button('View All Goals →','go-goals'))}${card('◒ Budget Planner',budgetCards(),button('View Full Budget →','go-budget'))}</div><div class="fin-three">${card('⇄ Currency Converter',currencyCard())}${card('▥ Weekly Spending Snapshot',snapshot())}${card('▣ Bills & Upcoming Payments',bills(true),button('View all →','bills'))}</div><div class="fin-wide fin-footer-grid">${card('💡 Smart Money Tips',tips())}${card('ϟ Quick Actions',actions)}</div></div>`;
   if(page==='goals')body=card('Your plans, one step closer',goalTotals()+goalCards(),button('+ Create Goal','goal'));
   if(page==='budget')body=`<div class="fin-actions">${button('+ Add Expense','expense')}${button('+ Add Income','income')}${button('Transactions','go-transactions')}${button('+ Add Bill','bill')}</div>`+card('Weekly & monthly category limits',budgetCards(),button('+ Create Budget','budget'))+card('Bills & Upcoming Payments',bills(),button('+ Add Bill','bill'));
   if(page==='currency')body=card('Cached exchange rates',currencyCard(),'','fin-currency-page');
   if(page==='insights')body=summary()+`<div class="fin-wide">${card('Weekly Spending Snapshot',snapshot())}${card('Based on your records',tips())}</div>`;
   if(page==='transactions')body=balanceCard()+paySchedules()+card('Account statement · running balances before filters',transactions(),`<div class="fin-actions">${button('+ Expense','expense')}${button('+ Income','income')}${button('Export CSV','csv')}</div>`);
   root().innerHTML=`<header class="fin-hero"><div class="fin-title-icon" aria-hidden="true">▤</div><div><h1>${title}</h1><p>Plan your goals, manage your budget, and track your money smarter.</p></div><span class="fin-currency-badge">${E(p().currency)} workspace</span></header>${periodControls()}<p class="fin-notice" data-fin-status role="status">${E(notice)}</p>${body}<p class="fin-disclaimer">Estimates based on the information you entered. Recorded balance is a manual tracker, not a bank connection. Forecasts are estimates, not received funds. Weeks run Monday–Sunday.</p>`;bind(root());updateConversion();syncNav()
  }
  function transactionForm(kind,item){item=item||{};if(item.id&&data.income_receipts.some(r=>r.transaction_id===item.id)){modal('Received income',`<p>${E(item.description)} · ${money(item.amount)} · ${dateText(item.date)}</p><p>This payment belongs to a pay schedule. To correct it, undo receipt and then mark it received with the correct amount. Undoing removes this transaction from your balance.</p>${button('Undo receipt','delete-transactions',item.id)}`);return}modal(item.id?'Edit transaction':'Add '+kind,`<div class="fin-form-grid">${select('Type','kind',[['income','Income'],['expense','Expense']],item.kind||kind)}${amountField('Amount','amount',item.amount)}${field('Date / first pay date','date','date',item.date||day(new Date()),'required')}${select('Expense category','category',data.categories,item.category||'Other')}${field('Source / merchant / description','description','text',item.description||'','required maxlength="500"')}</div>${!item.id?`<fieldset data-income-options><legend>Income schedule</legend>${select('How often are you paid?','frequency',[['none','Single pay'],['weekly','Weekly'],['monthly','Monthly']],'none')}<div data-recurring-income>${field('Last pay date (optional)','end_date','date','')}${select('First payment','record_first',[['true','Received if due today or earlier'],['false','Not received yet — schedule only']],'true')}<p>Future payments remain planned. Mark each payday received to update your recorded balance. Monthly pay keeps the original day (e.g. 31 January → 28 February → 31 March).</p></div></fieldset>`:''}<label>Notes<textarea name="notes" maxlength="10000">${E(item.notes||'')}</textarea></label>${item.id?button('Delete transaction','delete-transactions',item.id):''}`,v=>v.kind==='income'&&v.frequency&&v.frequency!=='none'?save('income-schedule',{...v,start_date:v.date,record_first:v.record_first==='true'}):save('transactions',v,item.id));if(!item.id){const f=dialog.querySelector('form'),options=f.querySelector('[data-income-options]'),repeat=f.querySelector('[data-recurring-income]');const toggle=()=>{options.hidden=f.elements.kind.value!=='income';options.disabled=options.hidden;repeat.hidden=f.elements.frequency.value==='none'};f.elements.kind.onchange=toggle;f.elements.frequency.onchange=toggle;toggle()}}
  function goalForm(item={}){const d=item.data||{},travel=d.travel||{};modal(item.id?'Edit goal':'Create goal',`<div class="fin-form-grid">${field('Goal name','name','text',item.name||'','required maxlength="500"')}${select('Goal type','type',['purchase','travel','emergency','other'],d.type||'purchase')}${amountField('Target amount','target',item.target)}${amountField('Starting savings','starting',item.starting,true)}${field('Target date','target_date','date',item.target_date||'','required')}${amountField('Planned monthly contribution','monthly',item.monthly,true)}${field('Icon (emoji)','icon','text',d.icon||'🎯','maxlength="8"')}${select('Goal status','paused',[['0','Active'],['1','Paused']],item.paused||0)}</div><label>Notes<textarea name="notes" maxlength="10000">${E(d.notes||'')}</textarea></label><fieldset data-travel><legend>Travel plan (optional)</legend><div class="fin-form-grid">${field('Destination','destination','text',travel.destination||'')}${field('Travel date','travel_date','date',travel.travel_date||'')}${['flights','accommodation','food','transport','activities','shopping','other'].map(k=>amountField(k[0].toUpperCase()+k.slice(1),k,travel[k],true)).join('')}</div><p>Travel components are planning estimates; the target amount above controls your goal.</p></fieldset>${item.id?button('Delete goal & contribution history','delete-goals',item.id):''}`,v=>save('goals',v,item.id));const type=dialog.querySelector('[name=type]'),travelFields=dialog.querySelector('[data-travel]');const toggle=()=>{travelFields.hidden=type.value!=='travel';travelFields.disabled=type.value!=='travel'};type.onchange=toggle;toggle()}
  function contribute(id){modal('Add goal contribution',`<p>This allocates money already inside your recorded balance. It does not add income or spend money. Log income separately if needed.</p>${amountField('Amount','amount')}${field('Date','date','date',day(new Date()),'required')}${field('Notes','notes')}`,v=>save('contributions',{...v,goal_id:id}))}
  function goalHistory(id){const goal=data.goals.find(g=>g.id===id);modal(goal.name+' — contributions',data.contributions.filter(c=>c.goal_id===id).map(c=>`<article class="fin-transaction"><div><b>${money(c.amount)}</b><small>${dateText(c.date)} · ${E(c.notes)}</small></div>${button('Delete','delete-contributions',c.id)}</article>`).join('')||empty('No contributions yet.','Starting savings are recorded separately in Edit Goal.'))}
  function budgetForm(item={}){modal(item.id?'Edit budget':'Create budget',`<div class="fin-form-grid">${select('Category','category',data.categories,item.category||'Groceries')}${amountField('Weekly limit','weekly',item.weekly,true)}${amountField('Monthly limit','monthly',item.monthly,true)}</div><p>Independent limits, reused in each period. Changing a limit also changes comparisons for past periods. Zero means no allocation.</p>${item.id?button('Delete budget','delete-budgets',item.id):''}`,v=>save('budgets',v,item.id))}
  function billForm(item={}){modal(item.id?'Edit bill schedule':'Add bill',`<div class="fin-form-grid">${field('Name','name','text',item.name||'','required maxlength="500"')}${amountField('Amount','amount',item.amount)}${select('Category','category',data.categories,item.category||'Bills')}${field('First due date','start_date','date',item.start_date||day(new Date()),'required min="2000-01-01"')}${select('Frequency','frequency',['none','weekly','fortnightly','monthly','quarterly','yearly'],item.frequency||'none')}${field('End date (optional)','end_date','date',item.end_date||'')}${select('Status','status',['upcoming','scheduled'],item.status||'upcoming')}</div><p>Paid status is tracked per occurrence. Overdue status is calculated from the selected period date.</p>${item.id?button('Delete schedule (keep recorded expenses)','delete-bills',item.id):''}`,v=>save('bills',v,item.id))}
  function pay(id,due){const b=data.bills.find(x=>x.id===id);modal('Pay '+b.name,`<p>${money(b.amount)} · Due ${dateText(due)}</p>${field('Payment date','paid_date','date',day(new Date()),'required')}${select('Also record this as an expense?','record_expense',[['true','Yes — add one linked expense'],['false','No — mark paid only']], 'true')}<p>Marking paid twice will not create duplicate expenses.</p>`,v=>save('pay',{...v,record_expense:v.record_expense==='true',due_date:due},id))}
  async function updateRates(){if(busy)return;busy=true;feedback('Updating currency rates…');try{await request('/api/finance/rates',{});await refresh();feedback('Rates updated.');render();renderSettings()}catch(e){feedback(e.message+(data.rates?' Showing rates last updated '+new Date(data.rates.fetched_at).toLocaleString()+'.':''))}finally{busy=false}}
  function exportCSV(){const cell=v=>'"'+String(/^[=+@\-\t\r]/.test(String(v))?"'"+v:v).replaceAll('"','""')+'"';const rows=[['Date','Type','Description','Category','Amount','Currency','Notes','Balance after entry'],...data.ledger.map(t=>[t.date,t.kind,t.description,t.category,amount(t.amount),t.currency,t.notes,t.running_balance===null?'':amount(t.running_balance)])];const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='finance-transactions.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  function bind(host){host.querySelectorAll('[data-fin]').forEach(b=>b.onclick=async()=>{const a=b.dataset.fin,id=b.dataset.id;try{if(a==='account')return accountForm();if(a==='income-schedule')return incomeScheduleForm(id);if(a==='receive-income')return receiveIncome(id,b.dataset.due);if(a==='remove-income-schedule'){if(!confirm('Delete this pay schedule? Received income stays in your balance.'))return;await save('delete-income-schedule',{},id);dirty=false;dialog.close();render();return}if(a.startsWith('go-'))return go(a.slice(3));if(a==='income'||a==='expense')return transactionForm(a);if(a==='transaction')return transactionForm('expense',data.transactions.find(t=>t.id===id));if(a==='goal')return goalForm(data.goals.find(t=>t.id===id));if(a==='contribute')return contribute(id);if(a==='goal-history')return goalHistory(id);if(a==='budget')return budgetForm(data.budgets.find(t=>t.id===id));if(a==='bill')return billForm(data.bills.find(t=>t.id===id));if(a==='bills')return go('budget');if(a==='pay')return pay(id,b.dataset.due);if(a==='rates')return updateRates();if(a==='csv')return exportCSV();if(a.startsWith('delete-')){if(!confirm('Delete this record? This cannot be undone. Linked contribution/payment history is removed where applicable; recorded expenses remain.'))return;await save('delete',{table:a.slice(7)},id);dirty=false;dialog.close();render();return}if(a==='reverse'){const s=data.rates,rate=c=>c===s?.base?1:Number(s?.data[c]?.rate),ratio=rate(converter.to)/rate(converter.from);if(Number.isFinite(ratio))converter.amount=String(Number((Number(converter.amount)*ratio).toFixed(factor(converter.to)===1?0:2)));[converter.from,converter.to]=[converter.to,converter.from];render();return}if(['previous','next','today'].includes(a)){const d=new Date(anchor+'T12:00:00');if(a==='today')anchor=day(new Date());else{if(period==='week')d.setDate(d.getDate()+(a==='next'?7:-7));else{d.setDate(1);d.setMonth(d.getMonth()+(a==='next'?1:-1))}anchor=day(d)}await refresh();render()}}catch(e){if(dialog.open)dialog.querySelector('.fin-error').textContent=e.message;else feedback(e.message)}});
   host.querySelector('[name=anchor]')?.addEventListener('change',async e=>{if(!e.target.value)return;anchor=e.target.value;try{await refresh();render()}catch(err){feedback(err.message)}});
   host.querySelector('[name=period]')?.addEventListener('change',e=>{period=e.target.value;render()});
   for(const [name,key] of [['fx_from','from'],['fx_to','to'],['fx_amount','amount']])host.querySelector('[name='+name+']')?.addEventListener('input',e=>{converter[key]=e.target.value;updateConversion()});
   host.querySelectorAll('.fin-filters input,.fin-filters select').forEach(el=>el.oninput=()=>{filters[el.name]=el.value;const list=host.querySelector('[data-fin-history]');list.innerHTML=historyRows();bind(list)})
  }
  function renderSettings(){const host=document.getElementById('portalSettings');if(!host)return;host.querySelector('.finance-settings')?.remove();const section=document.createElement('section');section.className='gym-card finance-settings';section.innerHTML=`<h3>Modules / Features</h3><div class="gym-module-row"><div><h4>Finance Module</h4><p>Plan savings goals, manage budgets and track personal spending.</p></div><label class="gym-switch"><input id="financeEnabled" type="checkbox" ${p().enabled?'checked':''} ${!data?'disabled':''}><span>${p().enabled?'Enabled':'Enable Finance'}</span></label></div><p>Disabling hides Finance without deleting any financial records.</p>${p().enabled?`<form id="financePreferences"><div class="fin-form-grid">${select('Base currency','currency',codes.map((c,i)=>[c,labels[i]]),p().currency)}${select('Week start','week_start',[['monday','Monday']],p().week_start)}${select('Default budget period','period',[['week','Week'],['month','Month']],p().period)}</div><p>Base currency cannot be changed after financial records exist; historical values are never silently converted.</p><button class="fin-button" type="submit">Save Finance preferences</button><p>Provider: Frankfurter v2 · manual updates only.<br>Last rate update: ${data.rates?E(new Date(data.rates.fetched_at).toLocaleString()):'Not downloaded'}</p></form>`:''}<p data-fin-status role="status">${!data?E(notice):''}</p>${!data?'<button class="fin-button" data-fin-retry>Retry Finance connection</button>':''}`;host.append(section);section.querySelector('[data-fin-retry]')?.addEventListener('click',init);section.querySelector('#financeEnabled').onchange=async e=>{const value=e.target.checked;e.target.disabled=true;try{await save('profile',{enabled:value});renderSettings()}catch(err){e.target.checked=!value;e.target.disabled=false;feedback(err.message)}};section.querySelector('form')?.addEventListener('submit',async e=>{e.preventDefault();try{await save('profile',Object.fromEntries(new FormData(e.target)));period=p().period;feedback('Finance preferences saved.')}catch(err){feedback(err.message)}})}
  function goDisabled(){o.show('settings')}
  async function onShow(name){document.body.classList.toggle('finance-open',name.startsWith('finance-'));if(name==='settings')renderSettings();if(!name.startsWith('finance-'))return;page=name.slice(8);if(!pages.includes(page))return;root().innerHTML=card('Finance','<p>Loading your workspace…</p>');try{await refresh();if(!p().enabled){goDisabled();return}render()}catch(e){root().innerHTML=card('Finance unavailable',`<p>${E(e.message)}</p>${button('Retry','go-'+page)}`);bind(root())}}
  async function init(){try{await refresh();notice='';renderSettings()}catch(e){notice='Finance could not load. Restart the local server and retry. '+e.message;renderSettings()}}
  function canLeave(){if(dialog.open&&dirty&&!confirm('Discard unsaved Finance changes?'))return false;if(dialog.open)dialog.close();dirty=false;return true}
  return {init,onShow,renderSettings,canLeave};
 }
 g.StudentFinance={create};
})(window);
