(function(g){
 'use strict';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const statuses={no_progress:'No Progress',in_progress:'In Progress',done:'Done'},rank={in_progress:0,no_progress:1,done:2};
 let data=null,loadError='',refreshDashboard=()=>{},manager=null,query='',filter='',sort='status',draft='';
 async function api(payload){const r=await fetch('/api/general-todos',payload?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}:{});const result=await r.json();if(!r.ok)throw Error(result.error||'Could not save. Please try again.');return result}
 function dateLabel(t){if(!t.due_date)return '';const d=new Date(t.due_date+'T12:00:00'),today=new Date(),tomorrow=new Date();tomorrow.setDate(today.getDate()+1);let label=d.toDateString()===today.toDateString()?'Today':d.toDateString()===tomorrow.toDateString()?'Tomorrow':d.toLocaleDateString(undefined,{weekday:'short',day:'numeric',month:'short',...(d.getFullYear()!==today.getFullYear()?{year:'numeric'}:{})});if(t.due_time)label+=', '+new Date(t.due_date+'T'+t.due_time).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'});return label}
 function ordered(items,mode='status'){const due=t=>(t.due_date||'9999-12-31')+'T'+(t.due_time||'23:59');return [...items].sort((a,b)=>Number(a.status==='done')-Number(b.status==='done')||(mode==='newest'?b.created_at.localeCompare(a.created_at):mode==='oldest'?a.created_at.localeCompare(b.created_at):(mode==='status'?rank[a.status]-rank[b.status]:0)||due(a).localeCompare(due(b)))||a.created_at.localeCompare(b.created_at)||a.id.localeCompare(b.id))}
 function options(value){return Object.entries(statuses).map(([k,v])=>`<option value="${k}" ${k===value?'selected':''}>${v}</option>`).join('')}
 function rows(items){return items.map(t=>`<div class="dash-reminder general-todo-row ${t.status==='done'?'todo-completed':''}" data-todo="${esc(t.id)}" title="${t.cleanup_after?esc('Automatically deleted after '+new Date(t.cleanup_after).toLocaleString()+'. Saved edits restart the 24-hour timer.'):'Done tasks are automatically deleted after 24 hours without edits.'}"><button type="button" class="reminder-circle ${t.status==='done'?'checked':''}" data-toggle aria-label="${esc((t.status==='done'?'Reopen ':'Complete ')+t.title)}" aria-pressed="${t.status==='done'}">${t.status==='done'?'✓':''}</button><button type="button" class="reminder-detail" data-edit title="${esc(t.title)}"><b>${esc(t.title)}</b>${t.due_date?`<small>▦ ${esc(dateLabel(t))}</small>`:''}</button><select class="status-badge status-${t.status}" aria-label="${esc('Status for '+t.title)}">${options(t.status)}</select></div>`).join('')||'<p class="todo-empty">Nothing on your list yet.<small>Add something below when it comes to mind.</small></p>'}
 function announce(host,message){host.querySelector('[data-todo-message]').textContent=message}
 async function save(payload){data=await api(payload);paint();return data}
 function bindRows(host){host.querySelectorAll('[data-todo]').forEach(row=>{const t=data.todos.find(t=>t.id===row.dataset.todo);row.querySelector('[data-edit]').onclick=()=>edit(t);const update=async status=>{row.querySelectorAll('button,select').forEach(el=>el.disabled=true);try{await save({action:'save',item:{id:t.id,status}});announce(host,'Status saved.')}catch(e){row.querySelectorAll('button,select').forEach(el=>el.disabled=false);row.querySelector('select').value=t.status;announce(host,e.message)}};row.querySelector('[data-toggle]').onclick=()=>update(t.status==='done'?'no_progress':'done');row.querySelector('select').onchange=e=>update(e.target.value)})}
 function quickForm(){return '<form class="todo-quick"><input name="title" aria-label="Add a general to-do" placeholder="Add a general to-do..." maxlength="500" autocomplete="off"><button type="submit" aria-label="Add general to-do">+</button></form><p class="todo-feedback" data-todo-message role="status" aria-live="polite"></p>'}
 function bindQuick(host,isCard=false){const form=host.querySelector('.todo-quick'),input=form.elements.title;if(isCard){input.value=draft;input.oninput=()=>draft=input.value}form.onsubmit=async e=>{e.preventDefault();if(form.dataset.busy)return;const title=input.value.trim();if(!title){announce(host,'Enter a task first.');input.focus();return}form.dataset.busy='true';form.querySelector('button').disabled=true;input.readOnly=true;try{await save({action:'save',item:{title}});input.value='';if(isCard)draft='';announce(host,'To-do added.')}catch(err){announce(host,err.message)}finally{delete form.dataset.busy;input.readOnly=false;form.querySelector('button').disabled=false;input.focus()}}}
 function paint(){const card=document.querySelector('.general-todo-card');if(card){const list=card.querySelector('.todo-list');list.innerHTML=rows(ordered(data.todos));bindRows(card)}if(manager?.isConnected){const items=ordered(data.todos.filter(t=>(!filter||t.status===filter)&&((t.title+' '+t.notes).toLowerCase().includes(query.toLowerCase()))),sort);manager.querySelector('.todo-list').innerHTML=items.length?rows(items):'<p class="todo-empty">No matching tasks.</p>';bindRows(manager)}}
 function mount(target){if(!data?.enabled)return;const slot=target.querySelector('.dash-actions-column');if(!slot||slot.querySelector('.general-todo-card'))return;slot.classList.add('has-general-todos');[...slot.children].forEach(el=>{el.classList.add('todo-original-card');el.inert=true;el.setAttribute('aria-hidden','true')});const card=document.createElement('article');card.className='dash-card general-todo-card';card.innerHTML='<header class="todo-heading"><h3><span aria-hidden="true">☷</span> General To-Do</h3><button class="dash-link" data-view-todos>View all →</button></header><div class="todo-list" tabindex="0" role="region" aria-label="General to-do list"></div>'+quickForm();slot.append(card);card.querySelector('[data-view-todos]').onclick=openManager;bindQuick(card,true);paint()}
 function dialog(title,cls=''){const previous=document.activeElement,d=document.createElement('dialog');d.className='todo-dialog '+cls;d.innerHTML=`<header class="todo-heading"><h2>${esc(title)}</h2><button type="button" data-close aria-label="Close">×</button></header>`;document.body.append(d);d.querySelector('[data-close]').onclick=()=>d.close();d.addEventListener('close',()=>{d.remove();if(previous?.isConnected)previous.focus()});d.addEventListener('click',e=>{if(e.target===d){const b=d.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)d.close()}});return d}
 function openManager(){if(manager?.isConnected){manager.focus();return}manager=dialog('General To-Do','todo-manager');manager.insertAdjacentHTML('beforeend','<p class="todo-description">Everyday tasks, separate from your coursework and calendar. Done tasks are deleted after 24 hours without saved edits; reopening cancels the timer.</p><div class="todo-filters"><input data-search aria-label="Search general tasks" placeholder="Search tasks..."><select data-filter aria-label="Filter by status"><option value="">All statuses</option>'+options('')+'</select><select data-sort aria-label="Sort tasks"><option value="status">Status</option><option value="due">Due date</option><option value="newest">Newest</option><option value="oldest">Oldest</option></select><button data-add-details>Add To-Do</button></div><div class="todo-list" tabindex="0" role="region" aria-label="All general to-dos"></div>'+quickForm());const search=manager.querySelector('[data-search]');search.value=query;search.oninput=()=>{query=search.value;paint()};const f=manager.querySelector('[data-filter]');f.value=filter;f.onchange=()=>{filter=f.value;paint()};const s=manager.querySelector('[data-sort]');s.value=sort;s.onchange=()=>{sort=s.value;paint()};manager.querySelector('[data-add-details]').onclick=()=>edit();bindQuick(manager);paint();manager.showModal()}
 function edit(item={}){const d=dialog(item.id?'Edit general to-do':'New general to-do','todo-editor');d.insertAdjacentHTML('beforeend',`<form><label>Title<input name="title" required maxlength="500" value="${esc(item.title||'')}"></label><div class="todo-fields"><label>Due date (optional)<input name="due_date" type="date" value="${esc(item.due_date||'')}"></label><label>Due time (optional)<input name="due_time" type="time" value="${esc(item.due_time||'')}"></label></div><label>Status<select name="status">${options(item.status||'no_progress')}</select></label><label>Notes (optional)<textarea name="notes" rows="3" maxlength="10000">${esc(item.notes||'')}</textarea></label><p data-todo-message class="todo-feedback" role="status"></p><footer><button type="submit" class="todo-primary">Save</button>${item.id?'<button type="button" data-duplicate>Duplicate</button><button type="button" data-delete>Delete</button>':''}</footer></form>`);const form=d.querySelector('form');let busy=false;async function act(payload){if(busy)return;busy=true;d.querySelectorAll('button').forEach(b=>b.disabled=true);try{await save(payload);d.close()}catch(e){announce(d,e.message)}finally{busy=false;d.querySelectorAll('button').forEach(b=>b.disabled=false)}}form.onsubmit=e=>{e.preventDefault();act({action:'save',item:{...(item.id?{id:item.id}:{}),...Object.fromEntries(new FormData(form))}})};if(item.id){d.querySelector('[data-delete]').onclick=()=>{if(confirm('Delete this general to-do? This cannot be undone.'))act({action:'delete',id:item.id})};d.querySelector('[data-duplicate]').onclick=()=>act({action:'save',item:{...Object.fromEntries(new FormData(form)),status:'no_progress'}})}d.showModal()}
 function renderSettings(){const host=document.getElementById('portalSettings');if(!host)return;host.querySelector('.general-todo-settings')?.remove();const section=document.createElement('section');section.className='gym-card general-todo-settings';section.innerHTML=`<h3>Modules / Features</h3><div class="gym-module-row"><div><h4>General To-Do</h4><p>Quickly manage everyday personal tasks directly from your Dashboard.</p></div><label class="gym-switch"><input id="generalTodosEnabled" type="checkbox" ${data?.enabled?'checked':''} ${!data?'disabled':''}> <span>${data?.enabled?'Enabled':'Enable General To-Do'}</span></label></div><p class="gym-caution">Replaces Quick Actions and the motivational card. Disabling restores those cards. Unfinished tasks are kept; Done tasks still expire after 24 hours without edits.</p><p data-todo-message role="status">${esc(loadError)}</p>${loadError?'<button data-retry>Retry connection</button>':''}`;host.append(section);section.querySelector('[data-retry]')?.addEventListener('click',()=>init(refreshDashboard));section.querySelector('input').onchange=async e=>{const enabled=e.target.checked;e.target.disabled=true;try{await save({action:'settings',enabled});refreshDashboard();renderSettings()}catch(err){e.target.checked=!enabled;e.target.disabled=false;announce(section,err.message)}}}
 async function init(refresh){refreshDashboard=refresh;try{data=await api();loadError='';refreshDashboard()}catch(e){loadError='General To-Do unavailable. '+e.message}renderSettings()}
 async function refresh(){if(!data)return;data=await api();paint()}
 g.GeneralTodos={init,mount,renderSettings,refresh};
})(window);
