const fetch=require('../support/authenticated_fetch.js');
// Isolated browser fixture only; never run against the user's database.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
(async()=>{
 const base='http://127.0.0.1:'+(process.argv[2]||8794);
 const post=async(url,body)=>{const r=await fetch(base+url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});assert(r.ok,await r.text())};
 const existing=await fetch(base+'/api/portal').then(r=>r.json());
 for(const r of existing.reminders)await post('/api/portal/delete',{table:'reminders',id:r.id});
 const now=new Date(),key=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
 const monday=new Date(now.getFullYear(),now.getMonth(),now.getDate()-(now.getDay()+6)%7);
 for(let i=0;i<7;i++)await post('/api/portal',{table:'timetable_events',item:{id:'dash-event-'+i,title:'Study session '+(i+1),day:i,start_time:'09:30',end_time:'11:30',recurrence:'weekly',color:['#9660f4','#4fb783','#51a0d1'][i%3],location:'Library'}});
 for(let i=0;i<5;i++){const d=new Date(now.getFullYear(),now.getMonth(),now.getDate()+i);await post('/api/portal',{table:'reminders',item:{id:'dash-reminder-'+i,title:'Review chapter '+(i+1),due_at:key(d)+'T17:00',status:['no_progress','in_progress','done'][i%3]}})}
 await post('/api/portal',{table:'settings',item:{display_name:'Test Student'}});
 const pages=await fetch('http://127.0.0.1:'+(process.argv[3]||9333)+'/json/list').then(r=>r.json()),ws=new WebSocket(pages.find(p=>p.type==='page').webSocketDebuggerUrl);
 await new Promise(r=>ws.onopen=r);let id=0;const pending=new Map(),errors=[];
 ws.onmessage=({data})=>{const m=JSON.parse(data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(m.error.message)):p.resolve(m.result)}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text)};
 const call=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}))});
 const js=async expression=>{const r=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};
 const wait=async expression=>{for(let i=0;i<100;i++){if(await js(expression))return;await new Promise(r=>setTimeout(r,100))}throw Error('Timed out: '+expression)};
 await fetch.browser(base,call);await call('Runtime.enable');await call('Page.enable');await call('Emulation.setDeviceMetricsOverride',{width:1280,height:960,deviceScaleFactor:1,mobile:false});
 await call('Page.navigate',{url:base});await wait("document.querySelectorAll('.week-hour').length===24");await wait("getComputedStyle(document.querySelector('.app')).gridTemplateColumns.startsWith('190px')");
 assert.equal(await js("document.querySelectorAll('.week-day-row').length"),7);
 assert.equal(await js("document.querySelectorAll('.nav [data-view=timetable],.nav [data-view=reminders],.nav [data-view=progress]').length"),0);
 assert.equal(await js("document.querySelectorAll('#subjectsSubnav [data-view]').length"),3);
 assert(await js("document.querySelector('.portal-welcome').textContent.includes('Test Student')"));
 assert.equal(await js("document.querySelector('[data-week-event=\"dash-event-0\"]').style.left"),'646px');
 assert.equal(await js("document.querySelector('[data-week-event=\"dash-event-0\"]').style.width"),'136px');
 await wait("document.querySelector('.week-scroll').scrollLeft>400");
 const left=await js("document.querySelector('.week-day-row .week-day-label').getBoundingClientRect().left");
 await js("document.querySelector('.week-scroll').scrollLeft=1200");
 assert.equal(await js("document.querySelector('.week-day-row .week-day-label').getBoundingClientRect().left"),left);
 await js("document.querySelector('.week-scroll').scrollLeft=476");
 assert.equal(await js("document.querySelectorAll('.dash-reminder').length"),5);
 await js("var select=document.querySelector('[data-status=\"dash-reminder-0\"]');select.value='in_progress';select.dispatchEvent(new Event('change'))");
 await wait("document.querySelector('[data-status=\"dash-reminder-0\"]').classList.contains('status-in_progress')");
 await js("document.querySelector('[data-done=\"dash-reminder-0\"]').click()");
 await wait("document.querySelector('[data-status=\"dash-reminder-0\"]').value==='done'");
 assert(await js("(()=>{const statuses=[...document.querySelectorAll('.dashboard-reminder-list [data-status]')].map(e=>e.value);return statuses.slice(statuses.indexOf('done')).every(s=>s==='done')})()"));
 assert.equal(await js("document.querySelectorAll('.dash-reminder').length"),5);
 let data=await fetch(base+'/api/portal').then(r=>r.json());assert.equal(data.reminders.find(r=>r.id==='dash-reminder-0').status,'done');
 await js("document.querySelector('#subjectsToggle').click()");
 assert.equal(await js("localStorage.getItem('portal.subjectsExpanded')"),'false');
 await call('Page.navigate',{url:base+'/?reload=1'});await wait("document.querySelectorAll('.week-hour').length===24");
 assert.equal(await js("document.querySelector('#subjectsToggle').getAttribute('aria-expanded')"),'false');
 assert.equal(await js("document.querySelector('[data-status=\"dash-reminder-0\"]').value"),'done');
 await js("document.querySelector('#subjectsToggle').click()");
 for(const v of ['library','flashcards','notes','tutor','settings','home']){await js(`document.querySelector('.nav [data-view=${v}]').click()`);assert(await js(`document.querySelector('#view-${v}').classList.contains('active')`))}
 await js("document.querySelector('.portal-home').click();document.querySelector('[data-new-reminder]').click()");
 assert(await js("!!document.querySelector('.reminders-form')"));await js("document.querySelector('[data-cancel]').click()");
 for(const v of ['import','flashcard-import','timetable']){await js(`document.querySelector('#portalDashboard [data-go="${v}"]').click()`);assert(await js(`document.querySelector('#view-${v}').classList.contains('active')`));await js("document.querySelector('.portal-home').click()")}
 // Exercise the existing import/study engines, not just their navigation links.
 await js("showView('import');document.querySelector('#loadSampleBtn').click();document.querySelector('#generateBtn').click()");
 await wait("state.topics['Design Principles']?.length===2");
 await new Promise(r=>setTimeout(r,1000)); // Existing import success navigates after 900ms.
 assert(await js("validateQuiz('not a valid quiz',null).errors.length>0"));
 await js("state.subjects.computing.topics.push('Design Principles');save();startQuiz('Design Principles');submitAnswer('A');goNextQuestion();submitAnswer('B');goNextQuestion()");
 assert(await js("document.querySelector('#view-results').classList.contains('active')"));
 assert.equal(await js("state.latestResults['Design Principles'].correct"),2);
 const previousReviews=await js("Object.values(state.flashcardProgress['Networking Fundamentals']||{})[0]?.reviews||0");
 await js("showView('flashcard-import');document.querySelector('#flashcardSampleBtn').click();document.querySelector('#generateFlashcardsBtn').click();startFlashcards('Networking Fundamentals');state.flashcardStudy.flipped=true;rateFlashcard('good')");
 assert.equal(await js("Object.values(state.flashcardProgress['Networking Fundamentals'])[0].reviews"),previousReviews+1);
 await js("window.portalNotes.open(Object.keys(state.subjects)[0])");
 await wait("!!document.querySelector('[data-new-note]')");
 await js("document.querySelector('[data-new-note]').click();document.querySelector('#notebookTitle').value='Dashboard regression note';document.querySelector('#notebookWeek').value='4';var noteDoc=document.querySelector('#notebookDocument');noteDoc.textContent='Existing notes still save.';noteDoc.dispatchEvent(new Event('input'));document.querySelector('[data-action=save]').click()");
 await wait("document.querySelector('#notebookStatus').textContent==='Saved'");
 await js("document.querySelector('[data-action=close]').click()");
 await wait("!document.querySelector('.notebook-editor') && document.querySelector('#notebookCards').textContent.includes('Dashboard regression note')");
 await js("document.querySelector('.portal-home').click()");
 assert.equal(await js("document.querySelectorAll('.dash-stat strong')[0].textContent"),'1');
 assert.equal(await js("document.querySelectorAll('.dash-stat strong')[1].textContent"),String(previousReviews+1));
 await call('Emulation.setDeviceMetricsOverride',{width:1035,height:800,deviceScaleFactor:1,mobile:false});
 await new Promise(r=>setTimeout(r,350));
 const desktop=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});fs.writeFileSync(path.join(os.tmpdir(),'student-dashboard-desktop.png'),Buffer.from(desktop.data,'base64'));
 assert(await js("Math.abs(document.querySelector('.dash-reminders').getBoundingClientRect().top-document.querySelector('.dash-timetable').getBoundingClientRect().top)<2"));
 await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await new Promise(r=>setTimeout(r,350));
 if(!await js("document.documentElement.scrollWidth<=innerWidth"))console.log(await js("({width:innerWidth,scroll:document.documentElement.scrollWidth,els:[...document.querySelectorAll('body *')].filter(e=>e.offsetParent&&e.getBoundingClientRect().right>innerWidth&&!e.closest('.week-grid')).map(e=>({tag:e.tagName,cls:e.className,width:e.getBoundingClientRect().width,right:e.getBoundingClientRect().right})).slice(0,20)})"));
 assert(await js("document.documentElement.scrollWidth<=innerWidth"));
 assert(await js("document.querySelector('.week-scroll').scrollWidth>document.querySelector('.week-scroll').clientWidth"));
 await js("document.querySelector('#menuToggle').click()");assert(await js("document.body.classList.contains('nav-open')"));
 await js("document.querySelector('.nav [data-view=notes]').click()");assert.equal(await js("document.body.classList.contains('nav-open')"),false);
 await js("document.querySelector('.portal-home').click()");
 const mobile=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});fs.writeFileSync(path.join(os.tmpdir(),'student-dashboard-mobile.png'),Buffer.from(mobile.data,'base64'));
 await require('../planner/calendar_fading.js')(js);
 await require('../planner/week_popup_browser.js')(js,call);
 await require('./mobile_navigation.js')(js,call);
 await require('../planner/general_todos_browser.js')(js,call);
 await require('../finance/finance_browser.js')(js,call);
 await require('../study/study_progress_browser.js')(js,call);
 await require('../social/social_browser.js')(js,call);
 await require('../marketplace/marketplace_browser.js')(js,call);
 assert.deepEqual(errors,[]);console.log('PASS dashboard: 24-hour grid, accurate half-hour positioning, sticky days, status persistence, completed visibility, saved display name, collapsed nav persistence, existing pages, quick actions, desktop proportions, mobile drawer and no page overflow.');ws.close();
})().catch(e=>{console.error(e);process.exit(1)});
