const fetch=require('../../support/authenticated_fetch.js');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
(async()=>{
 const base=`http://127.0.0.1:${process.argv[2]}`,debug=process.argv[3],pages=await fetch(`http://127.0.0.1:${debug}/json/list`).then(r=>r.json()),ws=new WebSocket(pages.find(p=>p.type==='page').webSocketDebuggerUrl);
 await new Promise(r=>ws.onopen=r);let id=0;const pending=new Map(),errors=[];let acceptDialog=true;
 const call=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}))});
 ws.onmessage=({data})=>{const m=JSON.parse(data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(m.error.message)):p.resolve(m.result)}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text);else if(m.method==='Page.javascriptDialogOpening')call('Page.handleJavaScriptDialog',{accept:acceptDialog})};
 const js=async expression=>{const r=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};
 const wait=async exp=>{for(let i=0;i<100;i++){if(await js(exp))return;await new Promise(r=>setTimeout(r,100))}throw Error('Timed out: '+exp)};
 const state=()=>fetch(base+'/api/portal').then(r=>r.json());
 const shot=async name=>{const r=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});fs.writeFileSync(path.join(os.tmpdir(),name),Buffer.from(r.data,'base64'))};
 await fetch.browser(base,call);await call('Runtime.enable');await call('Page.enable');await call('Emulation.setDeviceMetricsOverride',{width:1672,height:1000,deviceScaleFactor:1,mobile:false});
 await call('Page.navigate',{url:base});await wait("!!document.querySelector('#tutorComposer')");await js("document.querySelector('.nav [data-view=notes]').click()");await wait("!!document.querySelector('[data-note-subject=computing]')");
 assert(await js("document.querySelector('#portalNotes').textContent.includes('Choose a subject')"));
 await js("document.querySelector('[data-note-subject=computing]').click()");await wait("document.querySelectorAll('[data-select-note]').length===5");
 assert(!await js("document.querySelector('#noteLibraryList').textContent.includes('Algebra only')"));
 await js("document.querySelector('[data-select-note=n0]').click()");await wait("document.querySelector('.note-reader-head').textContent.includes('Network fundamentals')");
 await wait("!!document.querySelector('.note-prose .note-callout')");await shot('subject-notes-desktop.png');
 const n0=(await state()).notes.find(n=>n.id==='n0');assert(n0.last_studied_at);
 await js("document.querySelector('#noteSearch').value='Practical';document.querySelector('#noteSearch').dispatchEvent(new Event('input'))");assert.equal(await js("document.querySelectorAll('[data-select-note]').length"),1);
 await js("document.querySelector('#noteSearch').value='';document.querySelector('#noteSearch').dispatchEvent(new Event('input'));document.querySelector('[data-note-filter=pinned]').click()");assert.equal(await js("document.querySelectorAll('[data-select-note]').length"),2);
 await js("document.querySelector('[data-pin=n0]').click()");await wait("document.querySelectorAll('[data-select-note]').length===1");assert.equal((await state()).notes.find(n=>n.id==='n0').is_pinned,0);
 await js("document.querySelector('[data-note-filter=all]').click();document.querySelector('[data-filter-toggle]').click();document.querySelector('#noteTagFilter').value='Practice';document.querySelector('#noteTagFilter').dispatchEvent(new Event('change'))");assert.equal(await js("document.querySelectorAll('[data-select-note]').length"),2);
 await js("document.querySelector('#noteTagFilter').value='';document.querySelector('#noteTagFilter').dispatchEvent(new Event('change'));document.querySelector('[data-new-note]').click()");
 assert.equal(await js("document.querySelector('#noteEditor [name=subject_id]').value"),'computing');
 assert(!await js("document.querySelector('#noteEditor [name=topic_name]').textContent.includes('Algebra')"));
 await js("var f=document.querySelector('#noteEditor');f.elements.title.value='New revision note';f.elements.topic_name.value='Networks';f.elements.week.value=4;f.elements.tags.value='Exam, Memory';f.elements.content.value='# A clear idea\\n\\n**Review** this ==important== point.\\n\\n> [!TIP]\\n> Try explaining it out loud.';f.dispatchEvent(new Event('input',{bubbles:true}));f.requestSubmit()");
 await wait("!document.querySelector('#noteEditor')&&document.querySelector('.note-reader-head').textContent.includes('New revision note')");
 let created=(await state()).notes.find(n=>n.title==='New revision note');assert.equal(created.subject_id,'computing');assert.equal(created.week,4);assert.deepEqual(created.tags,['Exam','Memory']);assert.equal(created.last_studied_at,null);
 await js("document.querySelector('[data-edit-note]').click();document.querySelector('[name=title]').value='Do not save';document.querySelector('[name=title]').dispatchEvent(new Event('input',{bubbles:true}))");
 acceptDialog=false;await js("document.querySelector('.portal-home').click()");assert(await js("document.querySelector('#view-notes').classList.contains('active')"));
 acceptDialog=true;await js("document.querySelector('[data-cancel-edit]').click()");assert.equal((await state()).notes.find(n=>n.id===created.id).title,'New revision note');
 await js("document.querySelector('[data-edit-note]').click();document.querySelector('[name=title]').value='Saved revision note';document.querySelector('#noteEditor').requestSubmit()");await wait("!document.querySelector('#noteEditor')");assert.equal((await state()).notes.find(n=>n.id===created.id).title,'Saved revision note');
 await js("document.querySelector('[data-ask-note]').click()");assert(await js("document.querySelector('#view-tutor').classList.contains('active')"));assert(await js("document.querySelector('#tutorNoteContext').textContent.includes('Saved revision note')"));
 await js("document.querySelector('.nav [data-view=notes]').click()");await wait("document.querySelector('.note-reader-head').textContent.includes('Saved revision note')");
 await js("document.querySelector('[data-study=flashcards]').click()");await wait("!!document.querySelector('#topicFlashcardInput')");assert(await js("document.querySelector('#topicFlashcardInput').value.includes('Front:')"));
 await js("document.querySelector('#addTopicFlashcardsBtn').click()");await wait("state.flashcards.Networks?.length===1");await new Promise(r=>setTimeout(r,1000));
 await js("document.querySelector('[data-study=quiz]').click()");await wait("!!document.querySelector('#topicQuestionInput')");await js("document.querySelector('#addTopicQuestionsBtn').click()");await wait("state.topics.Networks.length===1");await new Promise(r=>setTimeout(r,1000));
 await js("document.querySelector('.portal-home').click();document.querySelector('#portalSearch').value='Saved revision';document.querySelector('#portalSearch').dispatchEvent(new Event('input'));document.querySelector('#portalSearchResults button').click()");await wait("document.querySelector('#view-notes').classList.contains('active')&&document.querySelector('.note-reader-head').textContent.includes('Saved revision note')");
 // Same subject/topic study engines still run after note-based imports.
 await js("startFlashcards('Networks');state.flashcardStudy.flipped=true;rateFlashcard('good');startQuiz('Networks');submitAnswer('A');goNextQuestion()");assert(await js("document.querySelector('#view-results').classList.contains('active')"));
 await js("showView('notes')");await wait("document.querySelector('#view-notes').classList.contains('active')");
 await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await new Promise(r=>setTimeout(r,250));
 assert(await js("document.documentElement.scrollWidth<=innerWidth"));assert.equal(await js("getComputedStyle(document.querySelector('.notes-library')).display"),'none');
 await js("document.querySelector('[data-details]').click()");assert(await js("document.querySelector('.notes-details').classList.contains('open')"));await js("document.querySelector('[data-details-close]').click()");await shot('subject-notes-mobile.png');
 await js("document.querySelector('[data-library-back]').click()");assert.equal(await js("getComputedStyle(document.querySelector('.notes-reader')).display"),'none');
 await js(`document.querySelector('[data-select-note="${created.id}"]').click()`);
 acceptDialog=false;await js("document.querySelector('[data-delete-note]').click()");assert((await state()).notes.some(n=>n.id===created.id));
 acceptDialog=true;await js("document.querySelector('[data-delete-note]').click()");await wait("!document.querySelector('.note-reader-head').textContent.includes('Saved revision note')");assert(!(await state()).notes.some(n=>n.id===created.id));
 await js("document.querySelector('[data-choose-subject]').click();document.querySelector('[data-unassigned]').click()");await wait("document.querySelector('#noteLibraryList').textContent.includes('Preserved unassigned')");await js("document.querySelector('[data-select-note=legacy-unassigned]').click();document.querySelector('[data-edit-note]').click();document.querySelector('[name=subject_id]').value='math';document.querySelector('[name=subject_id]').dispatchEvent(new Event('change'));document.querySelector('#noteEditor').requestSubmit()");await wait("!document.querySelector('#noteEditor')");assert.equal((await state()).notes.find(n=>n.id==='legacy-unassigned').subject_id,'math');
 assert.deepEqual(errors,[]);console.log('PASS Notes browser: subject isolation, create/edit/cancel, tags/week/pin, search/filter, study timestamps, AI context, real importers, global search, mobile reader/details, delete confirmation, legacy reassignment.');ws.close();
})().catch(e=>{console.error(e);process.exit(1)});
