const fetch=require('../support/authenticated_fetch.js');
// Runs only against the runner's temporary database and hidden browser.
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
(async()=>{
 const base='http://127.0.0.1:'+process.argv[2],debug=process.argv[3],pages=await fetch('http://127.0.0.1:'+debug+'/json/list').then(r=>r.json()),ws=new WebSocket(pages.find(p=>p.type==='page').webSocketDebuggerUrl);
 await new Promise(r=>ws.onopen=r);let id=0;const pending=new Map(),errors=[];const call=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}))});
 ws.onmessage=({data})=>{const m=JSON.parse(data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(m.error.message)):p.resolve(m.result)}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text);else if(m.method==='Page.javascriptDialogOpening')call('Page.handleJavaScriptDialog',{accept:true})};
 const js=async expression=>{const r=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};
 const wait=async exp=>{for(let i=0;i<120;i++){if(await js(exp))return;await new Promise(r=>setTimeout(r,80))}throw Error('Timed out: '+exp)};
 const click=async sel=>js(`document.querySelector(${JSON.stringify(sel)}).click()`);
 const state=()=>fetch(base+'/api/gym').then(r=>r.json());
 const form=async values=>js(`(()=>{const f=document.querySelector('dialog[open] form');for(const [k,v] of Object.entries(${JSON.stringify(values)})){if(f.elements[k].type==='checkbox')f.elements[k].checked=v;else f.elements[k].value=v}f.requestSubmit()})()`);
 const shot=async name=>{const r=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});fs.writeFileSync(path.join(os.tmpdir(),name),Buffer.from(r.data,'base64'))};
 await fetch.browser(base,call);await call('Runtime.enable');await call('Page.enable');await call('Emulation.setDeviceMetricsOverride',{width:1536,height:1024,deviceScaleFactor:1,mobile:false});await call('Page.navigate',{url:base});
 await wait("document.querySelector('#gymEnabled')&&!document.querySelector('#gymEnabled').disabled");
 assert(await js("document.querySelector('#gymNav').hidden"));assert.equal((await state()).profile.enabled,false);
 await click('.nav [data-view=settings]');await click('#gymEnabled');await wait("!document.querySelector('#gymNav').hidden");await click('#gymNav [data-view=gym-overview]');await wait("!!document.querySelector('.gym-view.active .gym-levels')");
 assert(await js("document.querySelector('.gym-view.active').textContent.includes('comfortable starting weight')"));assert.equal((await state()).sets.length,0);
 await shot('gym-overview-desktop.png');
 await click('.gym-view.active [data-pref=equipment][data-value=bodyweight]');await wait("document.querySelector('.gym-view.active [data-value=bodyweight]').classList.contains('selected')");
 assert.equal((await state()).profile.equipment,'bodyweight');
 await click('.gym-view.active [data-pref=level][data-value=advanced]');await wait("document.querySelector('.gym-view.active [data-value=advanced]').classList.contains('selected')");
 await click('.gym-view.active [data-pref=goal][data-value=strength]');await wait("document.querySelector('.gym-view.active [data-value=strength]').classList.contains('selected')");
 await js("var dur=document.querySelector('.gym-view.active [name=duration]');dur.value='60';dur.dispatchEvent(new Event('change'))");await wait("document.querySelector('.gym-workout-heading').textContent.includes('60 minutes')");
 await click('.gym-view.active [data-gym=change]');
 await click('.gym-view.active [data-gym="swap:0"]');await wait("!!document.querySelector('dialog[open]')");
 if(await js("!!document.querySelector('dialog[open] [name=exercise]')")){await form({});await wait("!document.querySelector('dialog[open]')")}else await click('dialog[open] [data-close]');
 await click('.gym-view.active [data-gym=save-suggestion]');await wait("document.querySelector('[data-gym-status]').textContent.includes('Program saved')");
 await click('.gym-view.active [data-gym=start]');await wait("!!document.querySelector('.gym-view.active #gymSetForm')");
 await js("var f=document.querySelector('#gymSetForm');f.elements.weight.value='0';f.elements.reps.value='8';f.requestSubmit()");await wait("document.querySelector('.gym-set-history').textContent.includes('Set 1')");
 await click('.gym-view.active [data-gym=timer-pause]');await click('.gym-view.active [data-gym=timer-reset]');assert.equal(await js("document.querySelector('.gym-view.active [data-timer-output]').textContent"),'01:30');await click('.gym-view.active [data-gym=timer-add]');assert.equal(await js("document.querySelector('.gym-view.active [data-timer-output]').textContent"),'02:00');
 await call('Page.navigate',{url:base+'/?recover=1'});await wait("!!document.querySelector('#gymNav [data-view=gym-workouts]')");await click('#gymNav [data-view=gym-workouts]');await wait("!!document.querySelector('.gym-view.active #gymSetForm')");assert(await js("document.querySelector('.gym-set-history').textContent.includes('Set 1')"));
 await click('.gym-view.active [data-gym=finish]');await wait("!document.querySelector('.gym-view.active #gymSetForm')");let s=await state();assert.equal(s.sessions[0].status,'completed');assert.equal(s.sets.length,1);
 // Weekly Progress: first week sets the benchmark; the logged exercise's muscle is covered, the rest are listed as still to train.
 await click('#gymNav [data-view=gym-overview]');await wait("!!document.querySelector('.gym-view.active .gym-weekly [data-gym-weekly-status]')");
 const trained=await js(`GymRules.muscleOf(${JSON.stringify(s.sets[0].exercise_id)}).muscle`);
 assert.equal(await js("document.querySelectorAll('.gym-view.active .gym-weekly [data-gym-muscle]').length"),7);
 assert(await js(`document.querySelector('.gym-view.active .gym-weekly [data-gym-muscle=${JSON.stringify(trained)}]').classList.contains('covered')`));
 assert(await js("document.querySelector('.gym-view.active [data-gym-weekly-status]').textContent.includes('first benchmark')"));
 assert(!(await js("document.querySelector('.gym-view.active .gym-weekly-gap b').textContent.split(', ')")).includes(trained));
 assert(await js("document.querySelector('.gym-view.active [data-gym=review-next]').disabled"));
 await click('.gym-view.active [data-gym=review-prev]');await wait("!document.querySelector('.gym-view.active [data-gym=review-next]').disabled");
 assert(await js("document.querySelector('.gym-view.active [data-gym-weekly-status]').textContent.includes('Complete a workout to set your first weekly benchmark')"));
 await click('.gym-view.active [data-gym=review-next]');await wait("document.querySelector('.gym-view.active [data-gym=review-next]').disabled");
 await click('#gymNav [data-view=gym-workouts]');await wait("document.querySelector('.gym-view.active')?.id==='view-gym-workouts'");
 await click('.gym-view.active [data-gym=custom]');await wait("!!document.querySelector('dialog[open] [name=name]')");await form({name:'My custom session',include_pushup:true,sets_pushup:2,reps_pushup:10});await wait("!document.querySelector('dialog[open]')");assert((await state()).workouts.some(w=>w.data.name==='My custom session'));
 const custom=(await state()).workouts.find(w=>w.data.name==='My custom session');await click('.gym-view.active [data-gym="duplicate:'+custom.id+'"]');await wait("document.querySelector('.gym-programs').textContent.includes('(copy)')");await click('.gym-view.active [data-gym="edit:'+custom.id+'"]');await form({name:'Edited program'});await wait("!document.querySelector('dialog[open]')");await click('.gym-view.active [data-gym="delete:'+custom.id+'"]');await wait("!document.querySelector('.gym-programs').textContent.includes('Edited program')");
 await click('#gymNav [data-view=gym-nutrition]');await wait("!!document.querySelector('.gym-view.active [data-gym=calculator]')");await click('.gym-view.active [data-gym=calculator]');await form({height:175,weight:70,age:21,sex:'male',activity:'moderate',goal:'maintain',adult_confirmation:true});await wait("!!document.querySelector('.gym-view.active .gym-targets')");assert((await state()).targets.calories>0);
 await click('.gym-view.active [data-gym=food]');await form({name:'Test lunch',calories:600,protein:30,carbs:70,fat:20});await wait("!document.querySelector('dialog[open]')");assert.equal((await state()).food_logs.length,1);assert(await js("document.querySelector('.gym-view.active').textContent.includes('Test lunch')"));
 await click('#gymNav [data-view=gym-progress]');await wait("!!document.querySelector('.gym-view.active [data-gym=measurement]')");await click('.gym-view.active [data-gym=measurement]');await form({weight:70,waist:80});await wait("!document.querySelector('dialog[open]')");await click('.gym-view.active [data-gym=measurement]');await form({weight:71});await wait("!document.querySelector('dialog[open]')");assert.equal((await state()).measurements.length,2);
 await click('#gymNav [data-view=gym-overview]');await wait("!!document.querySelector('.gym-view.active .gym-week')");await click('.gym-view.active .gym-week button');await form({label:'Rest / recovery'});await wait("!document.querySelector('dialog[open]')");assert.equal((await state()).schedule[0].label,'Rest / recovery');
 await click('.gym-view.active [data-gym=plates]');await js("var pf=document.querySelector('dialog[open] form');pf.elements.target.value='100';pf.elements.target.dispatchEvent(new Event('input'))");assert(await js("document.querySelector('[data-plate-result]').textContent.includes('Exact load')"));await click('dialog[open] [data-close]');
 await click('#gymToggle');assert.equal(await js("localStorage.getItem('portal.gymExpanded')"),'false');await click('#gymToggle');
 await click('.nav [data-view=settings]');await click('#gymEnabled');await wait("document.querySelector('#gymNav').hidden");assert.equal((await state()).sessions.length,1);await click('#gymEnabled');await wait("!document.querySelector('#gymNav').hidden");assert.equal((await state()).sets.length,1);
 await click('#gymNav [data-view=gym-overview]');await wait("!!document.querySelector('.gym-view.active .gym-week')");
 await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await js("document.body.classList.add('dark')");await shot('gym-mobile-dark.png');
 assert(await js("document.documentElement.scrollWidth<=innerWidth"));assert(await js("getComputedStyle(document.querySelector('.gym-view.active .gym-card')).backgroundColor!== 'rgb(255, 255, 255)'"));
 await click('#menuToggle');await click('#gymNav [data-view=gym-workouts]');await wait("!!document.querySelector('.gym-view.active .gym-programs')");assert.equal(await js("document.body.classList.contains('nav-open')"),false);assert(await js("document.documentElement.scrollWidth<=innerWidth"));
 await call('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
 await click('#gymNav [data-view=gym-overview]');await wait("!!document.querySelector('.gym-view.active [data-gym=athlete]')");
 await click('.gym-view.active [data-gym=athlete]');await form({age:22,gender:'Non-binary',activity:'light',height:175,weight:71});await wait("!document.querySelector('dialog[open]')");assert.equal((await state()).profile.athlete.gender,'Non-binary');
 await click('.gym-view.active [data-gym=challenge]');await form({weeks:8,sessions_per_week:2,goal:'gain',target_weight:73});await wait("!document.querySelector('dialog[open]')");assert.equal((await state()).journey.target_weight,73);assert.equal((await state()).journey.status,'active');
 await click('.gym-view.active [data-gym="source:own"]');await wait("!!document.querySelector('.gym-view.active [data-gym=examples]')");await click('.gym-view.active [data-gym=examples]');await wait("[...document.querySelectorAll('.gym-view.active .gym-programs h4')].some(e=>e.textContent==='Gym B')");
 let journeyState=await state(),gymA=journeyState.workouts.find(w=>w.data.name==='Gym A');assert.equal(gymA.data.exercises[4].unit,'seconds');assert.equal(gymA.data.exercises[4].reps_max,45);
 await click('.gym-view.active [data-gym=own-workout]');await form({name:'My timed circuit',duration:20,routine:'Wall sit | 2 | 30-45 | seconds\nStep ups | 2 | 8-12 | reps'});await wait("!document.querySelector('dialog[open]')");
 const circuit=(await state()).workouts.find(w=>w.data.name==='My timed circuit');assert.equal(circuit.data.exercises.length,2);
 await click('.gym-view.active [data-gym="plan:'+gymA.id+'"]');await form({date:'2027-01-05',start_time:'17:00',end_time:'18:00',recurrence:'weekly',repeat_until:'2027-02-02',location:'Uni Gym'});await wait("!document.querySelector('dialog[open]')");
 let planned=(await state()).calendar_workouts[0];assert.equal(planned.title,'Gym · Gym A');assert.equal(planned.recurrence,'weekly');
 const portal=await fetch(base+'/api/portal').then(r=>r.json());assert(portal.timetable_events.some(e=>e.id===planned.id));
 await click('.gym-view.active [data-gym="program:'+circuit.id+'"]');await wait("!!document.querySelector('.gym-view.active #gymSetForm')");assert(await js("document.querySelector('.gym-session-head').textContent.includes('Wall sit')"));assert(await js("document.querySelector('#gymSetForm').textContent.includes('Seconds')"));
 await js("var gf=document.querySelector('#gymSetForm');gf.elements.weight.value='0';gf.elements.reps.value='35';gf.requestSubmit()");await wait("document.querySelector('.gym-set-history').textContent.includes('35 sec')");
 await click('.gym-view.active [data-gym=finish]');await wait("!document.querySelector('.gym-view.active #gymSetForm')");assert.equal((await state()).journey.credited_days,0);
 await call('Page.navigate',{url:base+'/?journey=1'});await wait("!!document.querySelector('#gymNav [data-view=gym-overview]')&&!!document.querySelector('#tutorComposer')");await click('#gymNav [data-view=gym-overview]');await wait("!!document.querySelector('.gym-view.active .gym-level-card')");assert(await js("document.querySelector('.gym-view.active').textContent.includes('My timed circuit')"));
 await shot('gym-journey-desktop.png');
 for(const width of [320,390,744]){await call('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:true});for(const dark of [true,false]){await js(`document.body.classList.toggle('dark',${dark})`);assert(await js("document.documentElement.scrollWidth<=innerWidth"),'No page overflow at '+width);}}
 await shot('gym-journey-mobile.png');
 await click('.gym-view.active [data-gym="remove-plan:'+planned.id+'"]');await wait("!document.querySelector('.gym-calendar-list').textContent.includes('Uni Gym')");assert.equal((await state()).calendar_workouts.length,0);
 assert.deepEqual(errors,[]);console.log('PASS Gym browser: existing workflows, profile, challenges, personal routines, timed sets, Gym A/B, calendar linking, persistence, mobile and dark/light themes');ws.close();
})().catch(e=>{console.error(e);process.exit(1)});
