"""Scoped study metrics and append-only activity snapshots.

Topics are the existing quiz sets. Question SQL ids are regenerated by the
legacy state writer, so identities hash question text/choices/answer instead.
Legacy totals remain labelled separately; we never fabricate historical attempts.
"""
import hashlib,json,sqlite3,uuid
from contextlib import closing
from datetime import datetime,timezone

def now():return datetime.now(timezone.utc).isoformat()
def dump(x):return json.dumps(x,sort_keys=True,ensure_ascii=False)
def fingerprint(q):return hashlib.sha256(dump([q.get('question'),q.get('choices'),q.get('answer')]).encode()).hexdigest()
def answer(v):return ','.join(sorted(str(x).strip().upper() for x in (v if isinstance(v,list) else str(v or '').split(','))))
def accuracy(correct,answered):return int(correct/answered*100+.5) if answered else None

def migrate(path,backups):
    with closing(sqlite3.connect(path)) as con,con:
        if con.execute("SELECT 1 FROM sqlite_master WHERE name='study_legacy'").fetchone():return
        backups.mkdir(parents=True,exist_ok=True)
        with closing(sqlite3.connect(backups/('before-study-progress-'+datetime.now().strftime('%Y%m%d-%H%M%S-%f')+'.db'))) as dest:con.backup(dest)
        con.executescript('''BEGIN IMMEDIATE;
        CREATE TABLE study_legacy(topic_name TEXT PRIMARY KEY,answered INTEGER NOT NULL,correct INTEGER NOT NULL);
        INSERT INTO study_legacy SELECT topic_name,answered,correct FROM progress;
        CREATE TABLE study_answers(id TEXT PRIMARY KEY,topic_name TEXT NOT NULL,subject_id TEXT,question_key TEXT NOT NULL,selected TEXT NOT NULL,is_correct INTEGER NOT NULL,attempted_at TEXT NOT NULL,run_id TEXT NOT NULL);
        CREATE INDEX study_answers_scope ON study_answers(topic_name,subject_id);
        CREATE TABLE study_runs(id TEXT PRIMARY KEY,topic_name TEXT NOT NULL,subject_id TEXT,result_json TEXT NOT NULL,finished_at TEXT NOT NULL);
        CREATE TABLE study_active(topic_name TEXT PRIMARY KEY,run_id TEXT NOT NULL);
        CREATE TABLE study_known(topic_name TEXT NOT NULL,question_key TEXT NOT NULL,is_correct INTEGER NOT NULL,PRIMARY KEY(topic_name,question_key));
        ''')
        # Coverage evidence can be recovered from real latest/session answers,
        # without claiming they are individual timestamped historical attempts.
        for topic,raw in con.execute('SELECT topic_name,result_json FROM latest_results').fetchall():
            result=json.loads(raw);questions=result.get('questions') or [json.loads(r[0]) for r in con.execute('SELECT data_json FROM questions WHERE topic_name=? ORDER BY position',(topic,))]
            for i,selected in result.get('answers',{}).items():
                if str(i).isdigit() and int(i)<len(questions):
                    q=questions[int(i)];con.execute('INSERT OR REPLACE INTO study_known VALUES(?,?,?)',(topic,fingerprint(q),int(answer(selected)==answer(q.get('answer')))))
        for topic,raw in con.execute('SELECT topic_name,answers_json FROM topic_sessions').fetchall():
            questions=[json.loads(r[0]) for r in con.execute('SELECT data_json FROM questions WHERE topic_name=? ORDER BY position',(topic,))]
            for i,selected in json.loads(raw).items():
                if str(i).isdigit() and int(i)<len(questions):
                    q=questions[int(i)];con.execute('INSERT OR REPLACE INTO study_known VALUES(?,?,?)',(topic,fingerprint(q),int(answer(selected)==answer(q.get('answer')))))

def before(con):
    return {'sessions':{r['topic_name']:json.loads(r['answers_json']) for r in con.execute('SELECT * FROM topic_sessions')},'results':{r['topic_name']:json.loads(r['result_json']) for r in con.execute('SELECT * FROM latest_results')}}

def capture(con,state,previous):
    # Match existing explicit topic deletion/reset semantics, not quiz retries.
    for table in ('study_legacy','study_answers','study_runs','study_active','study_known'):
        con.execute('DELETE FROM '+table+' WHERE topic_name NOT IN (SELECT name FROM topics)')
    stamp=now();owners={t:s.get('id',sid) for sid,s in state.get('subjects',{}).items() for t in s.get('topics',[])}
    for topic,questions in state.get('topics',{}).items():
        result=state.get('latestResults',{}).get(topic)
        finished=bool(result and result!=previous['results'].get(topic))
        answers=(result.get('answers',{}) if finished else state.get('sessions',{}).get(topic,{}).get('answers',{}))
        old=previous['sessions'].get(topic,{})
        if not answers:
            con.execute('DELETE FROM study_active WHERE topic_name=?',(topic,));continue
        active=con.execute('SELECT run_id FROM study_active WHERE topic_name=?',(topic,)).fetchone()
        run=active[0] if active else str(uuid.uuid4())
        con.execute('INSERT OR REPLACE INTO study_active VALUES(?,?)',(topic,run))
        actual_questions=result.get('questions',questions) if finished else questions
        for index,selected in answers.items():
            if not str(index).isdigit() or int(index)>=len(actual_questions):continue
            q=actual_questions[int(index)];key=fingerprint(q);ok=int(answer(selected)==answer(q.get('answer')))
            if old.get(str(index))!=selected:
                con.execute('INSERT INTO study_answers VALUES(?,?,?,?,?,?,?,?)',(str(uuid.uuid4()),topic,owners.get(topic),key,answer(selected),ok,stamp,run))
            con.execute('INSERT OR REPLACE INTO study_known VALUES(?,?,?)',(topic,key,ok))
        if finished:
            con.execute('INSERT OR IGNORE INTO study_runs VALUES(?,?,?,?,?)',(run,topic,owners.get(topic),dump(result),stamp))
            con.execute('DELETE FROM study_active WHERE topic_name=?',(topic,))

def mastery(correct,answered,coverage,available):
    if not answered:return 'Not Started'
    pct=accuracy(correct,answered)
    if pct<50:return 'Needs Practice'
    if pct<70 or coverage<.5 or available<5:return 'Developing'
    if pct<85 or coverage<.8 or coverage*available<5:return 'Good'
    return 'Strong'

def report(con,subject_id,topic_name=None):
    subject=con.execute('SELECT id,name FROM subjects WHERE id=?',(subject_id,)).fetchone()
    if not subject:raise ValueError('Choose an existing subject.')
    names=[r[0] for r in con.execute('SELECT topic_name FROM subject_topics WHERE subject_id=? ORDER BY position',(subject_id,))]
    if topic_name and topic_name not in names:raise ValueError('This topic does not belong to this subject.')
    if topic_name:names=[topic_name]
    all_questions={};all_cards={}
    for r in con.execute('SELECT topic_name,data_json FROM questions ORDER BY position'):all_questions.setdefault(r['topic_name'],[]).append(json.loads(r['data_json']))
    for r in con.execute('SELECT topic_name,data_json FROM flashcards'):all_cards.setdefault(r['topic_name'],[]).append(json.loads(r['data_json']))
    legacy={r['topic_name']:dict(r) for r in con.execute('SELECT * FROM study_legacy')}
    current={r['topic_name']:dict(r) for r in con.execute('SELECT * FROM progress')}
    known={}
    for r in con.execute('SELECT * FROM study_known'):known.setdefault(r['topic_name'],{})[r['question_key']]=r['is_correct']
    attempts=[dict(r) for r in con.execute('SELECT * FROM study_answers WHERE subject_id=? ORDER BY attempted_at',(subject_id,))]
    runs=[dict(r) for r in con.execute('SELECT * FROM study_runs WHERE subject_id=? ORDER BY finished_at DESC',(subject_id,))]
    latest={r['topic_name']:json.loads(r['result_json']) for r in con.execute('SELECT * FROM latest_results')}
    sessions={r['topic_name']:json.loads(r['answers_json']) for r in con.execute('SELECT * FROM topic_sessions')}
    notes=[dict(r) for r in con.execute('SELECT * FROM notes WHERE subject_id=?',(subject_id,))]
    reviews=[dict(r) for r in con.execute('SELECT * FROM flashcard_reviews')]
    card_progress={r['topic_name']:json.loads(r['data_json']) for r in con.execute('SELECT * FROM flashcard_progress')}
    result=[]
    for name in names:
        qs=all_questions.get(name,[]);keys={fingerprint(q) for q in qs};evidence={k:v for k,v in known.get(name,{}).items() if k in keys}
        for i,a in sessions.get(name,{}).items():
            if str(i).isdigit() and int(i)<len(qs):evidence[fingerprint(qs[int(i)])]=int(answer(a)==answer(qs[int(i)].get('answer')))
        events=[r for r in attempts if r['topic_name']==name]
        old=legacy.get(name,{});total=old.get('answered',0)+len(events);correct=old.get('correct',0)+sum(r['is_correct'] for r in events)
        # Imported legacy totals are still real data, not synthetic attempts.
        if current.get(name,{}).get('answered',0)>total:total=current[name]['answered'];correct=current[name]['correct']
        correct=max(0,min(correct,total));coverage=len(evidence)/len(keys) if keys else 0
        candidates=[json.loads(r['result_json']) for r in runs if r['topic_name']==name]+([latest[name]] if name in latest else [])
        completed=False
        for r in candidates:
            snapshot=r.get('questions') or qs;answered_keys={fingerprint(snapshot[int(i)]) for i in r.get('answers',{}) if str(i).isdigit() and int(i)<len(snapshot)}
            if keys and keys<=answered_keys:completed=True;break
        status='Completed' if completed else 'In Progress' if total or evidence or sessions.get(name) else 'Not Started'
        ns=[n for n in notes if n['topic_name']==name];rs=[r for r in reviews if r['topic_name']==name]
        ratings={k:sum(r['rating']==k for r in rs) for k in ('again','hard','good','easy')}
        timestamps=[r['attempted_at'] for r in events]+[r['reviewed_at'] for r in rs]+[n['last_studied_at'] for n in ns if n['last_studied_at']]
        card_count=len(all_cards.get(name,[]));reviewed=len({r['card_position'] for r in rs if 0<=r['card_position']<card_count})
        reviewed=max(reviewed,min(card_count,len(card_progress.get(name,{}))))
        result.append(dict(topic=name,answered=total,correct=correct,incorrect=total-correct,accuracy=accuracy(correct,total),legacy_answered=old.get('answered',0),detailed_attempts=len(events),available=len(keys),unique=len(evidence),latest_correct=sum(evidence.values()),coverage=round(coverage*100),quiz_status=status,quiz_total=int(bool(qs)),quiz_completed=int(completed),mastery=mastery(correct,total,coverage,len(keys)),cards_available=card_count,cards_reviewed=reviewed,ratings=ratings,notes=len(ns),last_studied=max(timestamps) if timestamps else None))
    totals={k:sum(t[k] for t in result) for k in ('answered','correct','incorrect','available','unique','quiz_total','quiz_completed','cards_available','cards_reviewed','detailed_attempts','legacy_answered')}
    totals.update(accuracy=accuracy(totals['correct'],totals['answered']),completion=accuracy(totals['quiz_completed'],totals['quiz_total']),topics=len(result),studied=sum(bool(t['answered'] or t['cards_reviewed'] or t['last_studied']) for t in result),in_progress=sum(t['quiz_total'] and t['quiz_status']=='In Progress' for t in result),not_started=sum(t['quiz_total'] and t['quiz_status']=='Not Started' for t in result),notes=sum(t['notes'] for t in result) if topic_name else len(notes))
    recent=[]
    for r in runs:
        if r['topic_name'] not in names:continue
        snapshot=json.loads(r['result_json']);a=snapshot.get('answers',{});qs=snapshot.get('questions',[]);correct=sum(answer(v)==answer(qs[int(i)].get('answer')) for i,v in a.items() if str(i).isdigit() and int(i)<len(qs))
        recent.append(dict(id=r['id'],topic=r['topic_name'],finished_at=r['finished_at'],answered=len(a),correct=correct,accuracy=accuracy(correct,len(a)),result=snapshot))
    eligible=[t for t in result if t['unique']>=5 and t['coverage']>=50 and t['accuracy'] is not None]
    return dict(subject=dict(subject),topic=topic_name,summary=totals,topics=result,recent=recent[:20],strongest=max(eligible,key=lambda t:t['accuracy'])['topic'] if eligible else None,practice=min(eligible,key=lambda t:t['accuracy'])['topic'] if len(eligible)>1 else None)
