(function(g){'use strict';
 const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const B=(label,action,id='',extra='')=>`<button type="button" class="qr-button" data-qr="${action}" data-id="${E(id)}" ${extra}>${label}</button>`;
 const markdown=s=>g.StudentNotes.markdown(s.replace(/^\s*(?:```|~~~)(.*)$/gm,'```$1'));
 function create(o){
  let root=document.getElementById('view-flashcards');const tabs=document.createElement('nav'),area=document.createElement('section');let data={decks:[],topics:[]},mode='flip',scope='',subject='',busy=false,dirty=false,deck=null,index=0,editing=null,preview=null,sourceNote=null; 
  let embeddedSubject='';
  function mount(host){if(root===host)return;host.append(...root.childNodes);root=host}
  function resetLibrary(){embeddedSubject='';scope='';subject='';setMode('flip')}
  async function embedded(sid,quick=false){embeddedSubject=sid;subject=sid;scope='';setMode(quick?'quick':'flip');try{await refresh();library()}catch(e){error(e.message)}}
  tabs.className='qr-tabs';tabs.setAttribute('aria-label','Flashcard types');tabs.innerHTML=B('Flip Flashcards','flip')+B('Quick Review Cards','quick');root.prepend(tabs);area.className='qr-library';area.hidden=true;root.append(area);
  const dialog=document.createElement('dialog');dialog.className='qr-dialog';document.body.append(dialog);dialog.oninput=()=>dirty=true;dialog.oncancel=e=>{if(dirty&&!confirm('Discard unsaved Quick Review changes?'))e.preventDefault();else dirty=false};
  async function api(action,values={},id){const r=await fetch('/api/quick-review',action?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,data:values,id})}:{});const result=await r.json();if(!r.ok)throw Error(result.error||'Quick Review is unavailable. Restart the portal server if it was just updated.');return result}
  async function refresh(){await o.saved();data=await api()}
  function error(message){const el=dialog.open?dialog.querySelector('[data-qr-error]'):area.querySelector('[data-qr-error]');if(el)el.textContent=message}
  function bind(host){host.querySelectorAll('[data-qr]').forEach(b=>b.onclick=async()=>{try{await act(b.dataset.qr,b.dataset.id,b)}catch(e){error(e.message)}})}
  function modal(title,body){dirty=false;dialog.classList.remove('qr-reading');dialog.innerHTML=`<header><h2>${E(title)}</h2>${B('✕','close','','aria-label="Close Quick Review"')}</header>${body}<p data-qr-error class="qr-error" role="alert"></p>`;bind(dialog);if(!dialog.open)dialog.showModal()}
  function setMode(next){mode=next;tabs.querySelectorAll('button').forEach(b=>{b.classList.toggle('active',b.dataset.qr===mode);b.setAttribute('aria-pressed',String(b.dataset.qr===mode))});root.querySelector('#flashcardTopics').hidden=mode!=='flip';root.querySelector('.section-head').hidden=mode!=='flip';area.hidden=mode!=='quick';if(mode==='quick')library()}
  async function open(topic=null,sid=null){o.show('flashcards');scope=topic||'';subject=sid||'';setMode('quick');try{await refresh();library()}catch(e){error(e.message)}}
  function library(){const rows=data.decks.filter(d=>(!scope||d.topic_name===scope)&&(!subject||data.topics.some(t=>t.name===d.topic_name&&t.subject_id===subject)));area.innerHTML=`<header class="qr-library-header"><div><span class="qr-eyebrow">Read • remember • revisit</span><h2>Quick Review Cards</h2><p>Small revision pages. No flipping, no hidden answers.</p></div>${B('＋ Create Quick Review Deck','import')}</header><div class="qr-filters"><label>Subject<select id="qrSubject" ${embeddedSubject?'disabled':''}>${embeddedSubject?'':'<option value="">All subjects</option>'}${o.subjects().filter(s=>!embeddedSubject||s.id===embeddedSubject).map(s=>`<option value="${E(s.id)}" ${subject===s.id?'selected':''}>${E(s.name)}</option>`).join('')}</select></label><label>Topic<select id="qrTopic"><option value="">All topics</option>${[...new Set(data.topics.filter(t=>!subject||t.subject_id===subject).map(t=>t.name))].map(n=>`<option ${scope===n?'selected':''}>${E(n)}</option>`).join('')}</select></label>${B('Refresh','refresh')}</div><p data-qr-error class="qr-error" role="alert"></p><div class="qr-decks">${rows.map(d=>{const viewed=d.pages.filter(p=>p.viewed_at).length,memorised=d.pages.filter(p=>p.memorised).length;return `<article class="qr-deck"><span class="qr-eyebrow">${E(d.topic_name)}</span><h3>${E(d.title)}</h3><p>${d.pages.length} pages · ${viewed} / ${d.pages.length} viewed · ${memorised} memorised</p><progress value="${viewed}" max="${d.pages.length}" aria-label="Pages viewed"></progress><small>${d.progress.sessions} reviews completed · ${d.progress.last_reviewed?'Last reviewed '+E(new Date(d.progress.last_reviewed).toLocaleString()):'Not reviewed yet'}</small><div class="qr-actions">${B(d.progress.last_reviewed?'Resume deck':'Open deck','read',d.id)}${B('Manage deck','manage',d.id)}</div></article>`}).join('')||'<div class="qr-empty"><h3>Your next revision starts here</h3><p>Paste important points, or create a deck from Notes. Existing Flip Flashcards are unchanged.</p></div>'}</div>`;bind(area);area.querySelector('#qrSubject').onchange=e=>{subject=e.target.value;scope='';library()};area.querySelector('#qrTopic').onchange=e=>{scope=e.target.value;library()}}
  function importer(note=null){sourceNote=note;preview=null;const topics=[...new Set(data.topics.filter(t=>!(note?.subject_id||embeddedSubject)||t.subject_id===(note?.subject_id||embeddedSubject)).map(t=>t.name))];const fixed=note?.topic_name||scope;modal('Paste Quick Review Cards',`<p>Choose a topic to omit Topic: from your paste, or choose “Topics in pasted text” for a multi-topic import. Only existing topics are used.</p><div class="qr-filters"><label>Topic<select id="qrImportTopic">${embeddedSubject?'':'<option value="">Topics in pasted text</option>'}${topics.map(n=>`<option ${fixed===n?'selected':''}>${E(n)}</option>`).join('')}</select></label><label>Maximum points per page<select id="qrLimit">${[3,4,5,6].map(n=>`<option ${n===5?'selected':''}>${n}</option>`).join('')}</select></label></div>${note?`<details open><summary>Source note: ${E(note.title)}</summary><p>Select and copy the important material below. Nothing is extracted by AI.</p><pre class="qr-source">${E(note.content)}</pre></details>`:''}<label>Deck name (optional)<input id="qrDeckName" maxlength="300" placeholder="Uses the first section title"></label><label>Paste / edit your revision content<textarea id="qrImportText" rows="12" spellcheck="false" placeholder="${E('Title: Important concepts\nPoints:\n- **Term**: important fact.\n- A command: `example`.\n\n---\n\nTitle: Another section\nPoints:\n- Another important point.')}"></textarea></label><div class="qr-actions">${B('Validate & Preview','preview')}${B('Import deck(s)','confirm-import','','disabled id="qrConfirmImport"')}</div><div id="qrValidation" aria-live="polite"></div><div id="qrPreview"></div>`);dialog.querySelectorAll('input,textarea,select').forEach(el=>el.addEventListener('input',()=>{preview=null;dialog.querySelector('#qrConfirmImport').disabled=true;dialog.querySelector('#qrValidation').textContent='Content changed. Validate again before importing.'}))}
  function payload(){return {text:dialog.querySelector('#qrImportText').value,topic_name:dialog.querySelector('#qrImportTopic').value||null,points_per_page:Number(dialog.querySelector('#qrLimit').value),title:dialog.querySelector('#qrDeckName').value,source_note:sourceNote?.id||null}}
  function validation(result){const host=dialog.querySelector('#qrValidation');host.innerHTML=result.errors.length?`<section class="qr-error-box"><h3>Nothing imported — fix ${result.errors.length} issue(s)</h3>${result.errors.map(e=>`<p><b>Section ${e.section}, around line ${e.line}: ${E(e.problem)}</b><br>${E(e.fix)} ${B('Jump to error','jump',String(e.line))}</p>`).join('')}</section>`:`<p class="qr-success">Ready: ${result.decks.length} deck(s), ${result.decks.reduce((n,d)=>n+d.pages.length,0)} pages. Review everything below before importing.</p>`;host.innerHTML+=result.warnings.map(w=>`<p>⚠ Line ${w.line}: ${E(w.message)}</p>`).join('');bind(host);dialog.querySelector('#qrConfirmImport').disabled=!!result.errors.length;dialog.querySelector('#qrPreview').innerHTML=result.errors.length?'':result.decks.map(d=>`<h3>${E(d.topic_name)} · ${E(d.title)}</h3>${d.pages.map((p,i)=>pageHTML(p,i,d.pages.length)).join('')}`).join('')}
  function pageHTML(p,i,total){return `<article class="qr-page"><span class="qr-eyebrow">Page ${i+1} of ${total}</span><h2>${E(p.title)}</h2><ol>${p.points.map(t=>`<li><div>${markdown(typeof t==='string'?t:t.content)}</div></li>`).join('')}</ol></article>`}
  async function read(id){await refresh();deck=data.decks.find(d=>d.id===id);if(!deck)throw Error('Deck no longer exists.');index=Math.max(0,deck.pages.findIndex(p=>p.id===deck.progress.current_page));reader();await visit()}
  function reader(){const p=deck.pages[index];modal(deck.title,`<section class="qr-reader"><div class="qr-reader-meta"><span>${E(deck.topic_name)}</span><b>Page ${index+1} of ${deck.pages.length}</b></div><progress max="${deck.pages.length}" value="${index+1}" aria-label="Reading position"></progress><div class="qr-reading-scroll">${pageHTML(p,index,deck.pages.length)}</div><div class="qr-reader-nav">${B('← Previous','previous','','id="qrPrevious" '+(index===0?'disabled':''))}${B(p.memorised?'✓ Memorised · undo':'Mark as memorised','memorise','','aria-pressed="'+!!p.memorised+'"')}${B(index===deck.pages.length-1?'Finish Review':'Next →',index===deck.pages.length-1?'finish':'next','','id="qrNext"')}</div><small>Reading is not memorising. Mark pages only when you choose. ← → to navigate.</small></section>`);dialog.classList.add('qr-reading');}
  async function visit(){await api('view',{page:deck.pages[index].id},deck.id);deck.pages[index].viewed_at=new Date().toISOString()}
  async function move(step){if(busy||!deck||index+step<0||index+step>=deck.pages.length)return;busy=true;try{index+=step;reader();await visit()}finally{busy=false}}
  function manage(id){deck=data.decks.find(d=>d.id===id);editing=structuredClone(deck);drawManager()}
  function drawManager(){modal('Manage Quick Review Deck',`<label>Deck name<input id="qrEditName" value="${E(editing.title)}" maxlength="300"></label><p>Move pages or individual points, edit text, or split a long point manually. Changes are applied only when you save. Changed pages lose their viewed/memorised flags; unchanged pages keep them.</p><div class="qr-actions">${B('＋ Add page','add-page')}${B('Save deck','save-deck')}${B('Delete deck','delete-deck',editing.id)}</div><div class="qr-edit-pages">${editing.pages.map((p,i)=>`<section class="qr-edit-page"><div class="qr-actions"><b>Page ${i+1}</b>${B('↑ Page','page-up',String(i),'aria-label="Move page '+(i+1)+' up" '+(i===0?'disabled':''))}${B('↓ Page','page-down',String(i),i===editing.pages.length-1?'disabled':'')}${B('Delete page','delete-page',String(i))}</div><label>Section title<input data-qr-title="${i}" value="${E(p.title)}" maxlength="300"></label>${p.points.map((pt,j)=>`<div class="qr-edit-point"><label>Point ${j+1}<textarea rows="4" data-qr-point="${i}:${j}">${E(typeof pt==='string'?pt:pt.content)}</textarea></label><div class="qr-actions">${B('↑ Point','point-up',i+':'+j,j===0?'disabled':'')}${B('↓ Point','point-down',i+':'+j,j===p.points.length-1?'disabled':'')}${B('Delete point','delete-point',i+':'+j)}<label>Move to page<select data-qr-move="${i}:${j}">${editing.pages.map((_,k)=>`<option value="${k}" ${i===k?'selected':''}>${k+1}</option>`).join('')}</select></label></div></div>`).join('')}${B('＋ Add point','add-point',String(i),p.points.length>=editing.points_per_page?'disabled':'')}</section>`).join('')}</div>`);dirty=true;dialog.querySelectorAll('[data-qr-move]').forEach(el=>el.onchange=()=>{capture();const [i,j]=el.dataset.qrMove.split(':').map(Number),k=Number(el.value);if(editing.pages[k].points.length>=editing.points_per_page){error('The destination page is full. Add a page or move a different point first.');el.value=i;return}editing.pages[k].points.push(editing.pages[i].points.splice(j,1)[0]);drawManager()})}
  function capture(){if(!editing||!dialog.querySelector('#qrEditName'))return;editing.title=dialog.querySelector('#qrEditName').value;dialog.querySelectorAll('[data-qr-title]').forEach(el=>editing.pages[+el.dataset.qrTitle].title=el.value);dialog.querySelectorAll('[data-qr-point]').forEach(el=>{const [i,j]=el.dataset.qrPoint.split(':').map(Number);editing.pages[i].points[j]=el.value})}
  async function act(a,id,b){
   if(a==='flip'){setMode('flip');return}if(a==='quick'||a==='refresh'){setMode('quick');await refresh();library();return}
   if(a==='close'){if(dirty&&!confirm('Discard unsaved Quick Review changes?'))return;dirty=false;dialog.close();dialog.classList.remove('qr-reading');await refresh();library();return}
   if(a==='import'){await refresh();importer();return}
   if(a==='jump'){const t=dialog.querySelector('#qrImportText'),lines=t.value.split('\n'),start=lines.slice(0,Number(id)-1).join('\n').length+(Number(id)>1?1:0);t.focus();t.setSelectionRange(start,start+(lines[Number(id)-1]?.length||0));t.scrollTop=Math.max(0,(Number(id)-3)*22);return}
   if(a==='preview'){preview=await api('preview',payload());validation(preview);return}
   if(a==='confirm-import'){if(busy||!preview||preview.errors.length)return;busy=true;b.disabled=true;try{const result=await api('import',payload());if(result.ok===false){validation(result);return}dirty=false;dialog.close();await refresh();library();await read(result.ids[0])}finally{busy=false}return}
   if(a==='read'){await read(id);return}if(a==='next'||a==='previous'){await move(a==='next'?1:-1);return}
   if(a==='memorise'){if(busy)return;busy=true;try{const p=deck.pages[index];await api('memorise',{page:p.id,memorised:!p.memorised},deck.id);p.memorised=!p.memorised;reader()}finally{busy=false}return}
if(a==='finish'){await visit();await api('finish',{},deck.id);await refresh();deck=data.decks.find(d=>d.id===deck.id);modal('Review complete',`<div class="qr-finished"><span>✓</span><h3>${E(deck.title)}</h3><p>${deck.pages.length} pages reviewed · ${deck.pages.filter(p=>p.memorised).length} marked memorised</p><p>${deck.progress.sessions} review session(s) completed</p>${B('Restart deck','restart')}${B('Back to decks','close')}</div>`);return}
   if(a==='restart'){await api('restart',{},deck.id);await read(deck.id);return}
   if(a==='manage'){dialog.classList.remove('qr-reading');manage(id);return}
   if(a==='delete-deck'){if(!confirm('Permanently delete this Quick Review deck and its own review progress? Flip Flashcards and quizzes are kept.'))return;await api('delete',{},id);dirty=false;dialog.close();await refresh();library();return}
   if(a==='save-deck'){if(busy)return;capture();busy=true;b.disabled=true;try{await api('save',editing,editing.id);dirty=false;dialog.close();await refresh();library()}finally{busy=false;b.disabled=false}return}
   capture();const i=Number(id),parts=id.split(':').map(Number);
   if(a==='add-page')editing.pages.push({title:'New revision page',points:['Write an important point.']});
   else if(a==='delete-page'){if(!confirm('Remove this page and its points from the draft? Nothing is deleted until you save.'))return;editing.pages.splice(i,1)}
   else if(a==='page-up'||a==='page-down'){const k=i+(a==='page-up'?-1:1);[editing.pages[i],editing.pages[k]]=[editing.pages[k],editing.pages[i]]}
   else if(a==='add-point')editing.pages[i].points.push('New important point.');
   else if(a==='delete-point'){if(!confirm('Remove this point from the draft?'))return;editing.pages[parts[0]].points.splice(parts[1],1)}
   else if(a==='point-up'||a==='point-down'){const points=editing.pages[parts[0]].points,k=parts[1]+(a==='point-up'?-1:1);[points[parts[1]],points[k]]=[points[k],points[parts[1]]]}
   else return;
   drawManager();
  }
  dialog.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select,button')||!dialog.querySelector('.qr-reader'))return;if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();move(e.key==='ArrowLeft'?-1:1).catch(e=>error(e.message))}});
  // Dialog arrow navigation also works when the default focused button is Close.
  dialog.addEventListener('keydown',e=>{if(!e.defaultPrevented&&dialog.querySelector('.qr-reader')&&e.target.matches('button')&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();move(e.key==='ArrowLeft'?-1:1).catch(e=>error(e.message))}});
  bind(tabs);setMode('flip');
  window.addEventListener('beforeunload',e=>{if(dirty&&dialog.open){e.preventDefault();e.returnValue=''}});
  document.addEventListener('click',e=>{const b=e.target.closest('[data-quick-topic]');if(b){e.preventDefault();e.stopPropagation();(o.openTopic||open)(b.dataset.quickTopic)}},true);
  return {open,mount,resetLibrary,embedded,fromNote:async note=>{if(note.subject_id&&o.openSubject)await o.openSubject(note.subject_id);else await open(note.topic_name,note.subject_id);scope=note.topic_name||'';importer(note)},canLeave:()=>{if(dialog.open&&dirty&&!confirm('Discard unsaved Quick Review changes?'))return false;dirty=false;dialog.close();return true}};
 }
 g.StudentQuickReview={create};
})(window);
