(function(g){
 'use strict';
 const originalFetch=g.fetch.bind(g);let user=null,accountId=document.querySelector('meta[name=portal-account]')?.content||null,dirty=false,tab='profile',pendingPhoto,chosenAvatar;
 const avatars={graduate:'🎓',owl:'🦉',fox:'🦊',cat:'🐱',panda:'🐼',robot:'🤖',astronaut:'🧑‍🚀',leaf:'🌱'};
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const loginPage=location.pathname==='/login';
 g.fetch=async(input,init={})=>{const url=new URL(typeof input==='string'?input:input.url,location.href);if(url.origin===location.origin&&url.pathname.startsWith('/api/')){const headers=new Headers(init.headers||(input instanceof Request?input.headers:undefined));headers.set('X-Portal-Request','1');if(accountId)headers.set('X-Portal-Account',accountId);init={...init,headers};}const response=await originalFetch(input,init);if(!loginPage&&url.origin===location.origin&&(response.status===401||response.status===409)){const data=await response.clone().json().catch(()=>({}));if(response.status===401||data.code==='account_changed'){location.replace('/login?expired=1');throw Error('Your sign-in changed. Please sign in again.')}}return response};
 async function api(path,values){const r=await fetch(path,values===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)}),data=await r.json();if(!r.ok)throw Error(data.error||'Request failed');return data}
 const img=(photo,avatar)=>photo?`<img src="${esc(photo)}" alt="Profile photo">`:`<span aria-hidden="true">${avatars[avatar]||avatars.graduate}</span>`;
 function applyAppearance(){if(!user)return;const p=user.profile,theme=p.theme||'system';document.body.classList.toggle('dark',theme==='dark'||theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.body.dataset.accountAccent=p.accent||'violet';document.body.classList.toggle('account-compact',p.density==='compact');updateHeader()}
 function updateHeader(){if(!user)return;document.querySelectorAll('[data-display-name]').forEach(x=>x.textContent=user.display_name);const avatar=document.querySelector('[data-avatar]');if(avatar)avatar.innerHTML=img(user.profile.photo,user.profile.avatar);const button=document.querySelector('.profile-button');if(button){button.title='Your profile and account settings';button.setAttribute('aria-label','Account settings for '+user.display_name)}}
 async function refresh(){const r=await api('/api/auth/me');user=r.user;accountId=user.id;applyAppearance();window.dispatchEvent(new CustomEvent('portal-profile-changed',{detail:user}));return user}
 function message(text,bad=false){const el=document.querySelector('#accountFeedback');if(el){el.textContent=text;el.classList.toggle('error',bad)}}
 const label=(title,key,value='',extra='')=>`<label>${title}<input name="${key}" value="${esc(value)}" ${extra}></label>`;
 const button=(label,action,primary=false)=>`<button type="button" class="account-button ${primary?'primary':''}" data-account="${action}">${label}</button>`;
 function profilePanel(){const p=user.profile;pendingPhoto=p.photo||null;chosenAvatar=p.avatar||'graduate';return `<form id="accountProfile"><div class="profile-editor-top"><div class="account-portrait" id="profilePreview">${img(pendingPhoto,chosenAvatar)}</div><div><h3>Make it feel like you</h3><p>Choose an avatar or add a profile photo.</p><div class="account-actions"><label class="account-button upload-photo">Upload photo<input type="file" id="profilePhoto" accept="image/png,image/jpeg,image/webp" hidden></label>${button('Remove photo','remove-photo')}</div><small>PNG, JPEG or WebP · up to 5 MB. Cropped to a square and stored locally.</small></div></div><div class="avatar-picker" role="group" aria-label="Choose an avatar">${Object.entries(avatars).map(([key,emoji])=>`<button type="button" data-avatar-choice="${key}" class="${chosenAvatar===key&&!pendingPhoto?'selected':''}" aria-label="${key}" aria-pressed="${chosenAvatar===key&&!pendingPhoto}">${emoji}</button>`).join('')}</div><div class="account-form-grid">${label('Display name','display_name',user.display_name,'required maxlength="60" autocomplete="nickname"')}${label('Contact email (optional)','email',p.email,'type="email" maxlength="150" autocomplete="email"')}${label('University / school','university',p.university,'maxlength="100"')}${label('Course / study focus','course',p.course,'maxlength="100"')}<label class="wide">A little about you<textarea name="bio" rows="3" maxlength="300" placeholder="What are you working towards?">${esc(p.bio)}</textarea></label></div><small>Email is profile information only—not verified and not used for recovery.</small><div class="account-actions"><button class="account-button primary">Save profile</button>${button('Discard changes','discard')}</div></form>`}
 function appearancePanel(){const p=user.profile;return `<form id="accountAppearance"><h3>Your space, your style</h3><p>Preferences follow your account on this portal.</p><label>Theme</label><div class="account-option-grid">${[['system','◐','System'],['light','☀','Light'],['dark','☾','Dark']].map(([v,i,n])=>`<label class="appearance-option"><input type="radio" name="theme" value="${v}" ${(p.theme||'system')===v?'checked':''}><span>${i}</span><b>${n}</b></label>`).join('')}</div><label>Accent colour</label><div class="account-swatches">${['violet','blue','teal','rose'].map(v=>`<label class="accent-${v}"><input type="radio" name="accent" value="${v}" ${(p.accent||'violet')===v?'checked':''}><span></span>${v}</label>`).join('')}</div><label>Layout density<select name="density"><option value="comfortable" ${p.density!=='compact'?'selected':''}>Comfortable — room to breathe</option><option value="compact" ${p.density==='compact'?'selected':''}>Compact — more in view</option></select></label><div class="account-actions"><button class="account-button primary">Save appearance</button></div></form>`}
 function securityPanel(){return `<div class="account-security-summary"><span>🔐</span><div><h3>Your account, protected</h3><p>Password changes sign out every device, including this one.</p></div></div><form id="accountPassword"><div class="account-form-grid">${label('Current password','current_password','','type="password" required autocomplete="current-password" maxlength="128"')}${label('New password','new_password','','type="password" required minlength="12" maxlength="128" autocomplete="new-password"')}${label('Confirm new password','confirm_password','','type="password" required minlength="12" maxlength="128" autocomplete="new-password"')}</div><small>Use a unique passphrase of at least 12 characters. Spaces are welcome.</small><div class="account-actions"><button class="account-button primary">Change password</button></div></form><hr><h3>Signed-in devices</h3><div id="accountSessions"><p>Loading sessions…</p></div><div class="account-actions">${button('Sign out other devices','revoke')}${button('Sign out this device','logout')}</div><p class="account-note">Sessions expire after 12 hours of inactivity or 7 days. This local HTTP connection is not encrypted. Use trusted Wi-Fi only, or configure HTTPS before exposing the app beyond your private network.</p>`}
 function adminPanel(){return `<h3>People & access</h3><p>New accounts start with an empty, separate workspace. Disabling an account keeps its data and signs out its sessions.</p><details class="create-account"><summary>＋ Create an account</summary><form id="adminCreate"><div class="account-form-grid">${label('Username','username','','required pattern="[a-zA-Z0-9][a-zA-Z0-9_.-]{2,31}" autocomplete="off"')}${label('Display name','display_name','','required maxlength="60"')}${label('Temporary password','password','','type="password" required minlength="12" maxlength="128" autocomplete="new-password"')}<label>Access level<select name="role"><option value="student">Student — own workspace</option><option value="admin">Administrator — can manage accounts</option></select></label></div><small>Share the temporary password privately. The user must change it on first sign-in.</small><div class="account-actions"><button class="account-button primary">Create account</button></div></form></details><div id="accountUsers">Loading accounts…</div>`}
 function renderSettings(){const host=document.getElementById('accountSettings');if(!host||!user||(dirty&&host.querySelector('form')))return;host.innerHTML=`<header class="account-hero"><div class="account-portrait">${img(user.profile.photo,user.profile.avatar)}</div><div><span class="account-eyebrow">YOUR PERSONAL SPACE</span><h2>${esc(user.display_name)}</h2><p>@${esc(user.username)} <span class="account-role">${user.role==='admin'?'Administrator':'Student'}</span></p></div>${button('Sign out ↗','logout')}</header><nav class="account-tabs" aria-label="Account settings">${[['profile','Profile'],['appearance','Appearance'],['security','Security'],...(user.role==='admin'?[['admin','People & access']]:[])].map(([k,n])=>`<button data-account-tab="${k}" class="${tab===k?'active':''}">${n}</button>`).join('')}</nav><section class="account-card"><p id="accountFeedback" role="status"></p>${tab==='profile'?profilePanel():tab==='appearance'?appearancePanel():tab==='security'?securityPanel():adminPanel()}</section>`;
   host.querySelectorAll('[data-account-tab]').forEach(b=>b.onclick=()=>{if(dirty&&!confirm('Discard unsaved profile or settings changes?'))return;dirty=false;tab=b.dataset.accountTab;renderSettings()});host.querySelectorAll('form').forEach(f=>{f.oninput=()=>dirty=true;f.onsubmit=submit});host.querySelectorAll('[data-account]').forEach(b=>b.onclick=()=>action(b.dataset.account));
   host.querySelectorAll('[data-avatar-choice]').forEach(b=>b.onclick=()=>{chosenAvatar=b.dataset.avatarChoice;pendingPhoto=null;dirty=true;preview()});
   host.querySelector('#profilePhoto')?.addEventListener('change',photoSelected);
   if(tab==='security')loadSessions();if(tab==='admin')loadUsers()
 }
 function preview(){document.getElementById('profilePreview').innerHTML=img(pendingPhoto,chosenAvatar);document.querySelectorAll('[data-avatar-choice]').forEach(b=>{const selected=b.dataset.avatarChoice===chosenAvatar&&!pendingPhoto;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',selected)})}
 async function photoSelected(ev){const file=ev.target.files[0];if(!file)return;try{if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>5*1024*1024)throw Error('Choose a PNG, JPEG or WebP photo under 5 MB.');const url=URL.createObjectURL(file);try{const image=new Image();image.src=url;await image.decode();if(image.width*image.height>16000000)throw Error('Choose a photo smaller than 16 megapixels.');const canvas=document.createElement('canvas');canvas.width=canvas.height=256;const size=Math.min(image.width,image.height);canvas.getContext('2d').drawImage(image,(image.width-size)/2,(image.height-size)/2,size,size,0,0,256,256);pendingPhoto=canvas.toDataURL('image/jpeg',.85);dirty=true;preview();message('Photo ready. Save your profile to keep it.')}finally{URL.revokeObjectURL(url)}}catch(err){message(err.message,true)}finally{ev.target.value=''}}
 async function submit(ev){ev.preventDefault();const f=ev.target,b=ev.submitter||f.querySelector('button[type=submit],button:not([type])'),values=Object.fromEntries(new FormData(f));if(b)b.disabled=true;try{
   if(f.id==='accountPassword'){if(values.new_password!==values.confirm_password)throw Error('New passwords do not match.');await api('/api/auth/password',values);dirty=false;location.href='/login?changed=1';return}
   if(f.id==='adminCreate'){await api('/api/admin/users',values);dirty=false;f.reset();await loadUsers();message('Account created. Share the temporary password privately.');return}
   await api('/api/auth/profile',f.id==='accountProfile'?{...values,avatar:chosenAvatar,photo:pendingPhoto}:{...values,display_name:user.display_name});dirty=false;await refresh();renderSettings();message('Saved. Your profile is up to date.');
  }catch(err){message(err.message,true)}finally{if(b)b.disabled=false}}
 async function action(name){try{
   if(name==='logout'){if(!confirm('Sign out? Make sure any changes have finished saving.'))return;await api('/api/auth/logout',{});dirty=false;location.href='/login';}
   if(name==='discard'){if(!dirty||confirm('Discard unsaved profile changes?')){dirty=false;renderSettings()}}
   if(name==='remove-photo'){pendingPhoto=null;dirty=true;preview()}
   if(name==='revoke'){await api('/api/auth/revoke',{});await loadSessions();message('Other devices have been signed out.')}
  }catch(err){message(err.message,true)}}
 async function loadSessions(){try{const r=await api('/api/auth/sessions');const el=document.getElementById('accountSessions');if(el)el.innerHTML=r.sessions.map(s=>`<div class="account-session"><span>${s.current?'●':'○'}</span><div><b>${s.current?'This device':'Another signed-in device'}</b><small>${esc(s.agent||'Browser')}<br>Last active ${new Date(s.last_seen*1000).toLocaleString()}</small></div></div>`).join('')}catch(err){message(err.message,true)}}
 async function loadUsers(){try{const r=await api('/api/admin/users'),el=document.getElementById('accountUsers');if(!el)return;el.innerHTML=r.users.map(u=>`<article class="account-user"><div class="account-user-avatar">${img(u.profile.photo,u.profile.avatar)}</div><div><b>${esc(u.display_name)}</b><small>@${esc(u.username)} · ${u.role} · ${u.disabled?'Disabled':'Active'}${u.must_change?' · Password change required':''}</small></div>${u.id!==user.id&&u.id!=='admin'?`<div>${button(u.disabled?'Enable':'Disable',(u.disabled?'enable:':'disable:')+u.id)}${button('Reset password','reset:'+u.id)}</div>`:'<span class="account-role">'+(u.id===user.id?'You':'Owner')+'</span>'}</article>`).join('');el.querySelectorAll('[data-account]').forEach(b=>b.onclick=async()=>{const [action,id]=b.dataset.account.split(':');try{if(action==='reset'){showReset(id);return}if(!confirm(action==='disable'?'Disable this account? Its sessions will be signed out; all saved data stays.':'Enable this account again?'))return;await api('/api/admin/manage',{id,action});await loadUsers();message('Account access updated')}catch(err){message(err.message,true)}})}catch(err){message(err.message,true)}}
 function showReset(id){const dialog=document.createElement('dialog');dialog.className='account-reset-dialog';dialog.innerHTML=`<form><h3>Set a temporary password</h3><p>The user must change it at next sign-in. All existing sessions will end.</p>${label('New temporary password','password','','type="password" required minlength="12" maxlength="128" autocomplete="new-password"')}<p role="alert"></p><div class="account-actions"><button class="account-button primary">Reset password</button><button type="button" class="account-button">Cancel</button></div></form>`;document.body.append(dialog);dialog.querySelector('[type=button]').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();dialog.querySelector('form').onsubmit=async ev=>{ev.preventDefault();try{await api('/api/admin/manage',{id,action:'reset_password',password:new FormData(ev.target).get('password')});dialog.close();loadUsers();message('Temporary password set. Share it privately.')}catch(err){dialog.querySelector('[role=alert]').textContent=err.message}};dialog.showModal()}
 async function initLogin(){const form=document.getElementById('loginForm');let change=false;try{const r=await originalFetch('/api/auth/me').then(r=>r.ok?r.json():null);if(r?.user){user=r.user;accountId=user.id;if(user.must_change){change=true;document.getElementById('loginTitle').textContent='Make your account yours.';document.getElementById('loginIntro').textContent='Choose a new password before opening your workspace.';form.innerHTML=`${label('Temporary / current password','current_password','','type="password" required autocomplete="current-password"')}${label('New password','new_password','','type="password" required minlength="12" maxlength="128" autocomplete="new-password"')}${label('Confirm new password','confirm_password','','type="password" required minlength="12" maxlength="128" autocomplete="new-password"')}<button class="account-button primary">Set my password →</button><p id="loginError" role="alert"></p>`}else{location.replace('/');return}}}catch{}
   document.querySelector('[data-reveal]')?.addEventListener('click',ev=>{const input=form.elements.password,show=input.type==='password';input.type=show?'text':'password';ev.target.textContent=show?'Hide':'Show';ev.target.setAttribute('aria-label',show?'Hide password':'Show password')});
   if(new URLSearchParams(location.search).has('changed'))document.getElementById('loginIntro').textContent='Password updated. Sign in with your new password.';
   form.onsubmit=async ev=>{ev.preventDefault();const b=form.querySelector('button:not([type=button])'),v=Object.fromEntries(new FormData(form));b.disabled=true;document.getElementById('loginError').textContent='';try{if(change){if(v.new_password!==v.confirm_password)throw Error('New passwords do not match.');await api('/api/auth/password',v);location.href='/login?changed=1'}else{const r=await api('/api/auth/login',v);accountId=r.user.id;location.href=r.user.must_change?'/login?change=1':'/'}}catch(err){document.getElementById('loginError').textContent=err.message}finally{b.disabled=false}}
 }
 function canLeave(){if(dirty&&!confirm('Discard unsaved profile or settings changes?'))return false;dirty=false;return true}
 g.PortalAccount={refresh,renderSettings,updateHeader,canLeave,openAppearance:()=>{if(canLeave()){tab='appearance';renderSettings()}}};
 window.addEventListener('beforeunload',ev=>{if(dirty){ev.preventDefault();ev.returnValue=''}});
 document.addEventListener('DOMContentLoaded',()=>{if(loginPage)initLogin();else refresh().then(()=>renderSettings()).catch(()=>{})});
 matchMedia('(prefers-color-scheme: dark)').addEventListener('change',()=>{if(user?.profile.theme==='system'||!user?.profile.theme)applyAppearance()});
})(window);
