(function(g){
 'use strict';
 function create(o){
  const {E,button,field,select,card,modal,save,render,toast,date,display,kg,unit}=o;
  const data=()=>o.data(),p=()=>data().profile;
  const descriptions={sedentary:'Mostly sitting',light:'Lightly active',moderate:'Moderately active',very:'Very active',high:'Physically demanding days'};
  function panel(){const a=p().athlete,j=data().journey,level=p().game_level||1;
   const credit=j?j.weekly_counts.reduce((n,v)=>n+Math.min(v,j.sessions_per_week),0):0;
   return `<div class="gym-journey-grid">${card('YOUR TRAINING PROFILE',`<h2>${a?'Built around your routine':'Let’s get to know you'}</h2><p>${a?`${E(a.age)} years · ${E(a.gender)} · ${E(descriptions[a.activity])}<br>${display(a.weight)} ${unit()} profile weight · ${a.height} cm`:'Add your age, gender, lifestyle, height and weight to plan a training block.'}</p><div class="gym-actions">${button(a?'Edit profile':'Set up profile','athlete',true)}${button('Log measurement','measurement')}</div><small>Profile weight is your starting reference; measurements track changes. Gender does not determine difficulty or weights.</small>`)}${card(`✦ LEVEL ${level} · ${level===1?'Starting strong':'Building momentum'}`,`<h2>${j?.status==='completed'?'Level up — block completed!':j?.status==='active'?'Your next milestone':'Small steps. Real consistency.'}</h2>${j?`<p>${E(j.start)} → ${E(j.end)} · ${j.sessions_per_week} training days/week</p><progress aria-label="Challenge training days" max="${j.required_days}" value="${credit}"></progress><p>${credit} / ${j.required_days} training days credited · ${j.goal==='gain'?`Target ${display(j.target_weight)} ${unit()} (baseline ${display(j.baseline_weight)} ${unit()})`:'Consistency goal'}</p><div class="gym-block-weeks">${j.weekly_counts.map((n,i)=>`<span class="${n>=j.sessions_per_week?'met':''}">Week ${i+1}<b>${n}/${j.sessions_per_week}</b></span>`).join('')}</div><p role="status">${j.status==='completed'?`✓ Level ${level} unlocked. Choose a fresh block when you’re ready.`:j.status==='ended'?'Block ended. Your workout history is kept.':!j.elapsed?'Keep going: the block must finish before a level is awarded.':credit<j.required_days?'Some weeks did not meet your plan. No penalty—end this block and try a more manageable plan.':!j.target_met?'Training goal met. Add a measurement dated in the final 7 days to check your weight target.':'Checking your milestone…'}</p>`:'<p>Complete a 4–24 week block with consistent, fully logged workouts to unlock your next game level.</p>'}<div class="gym-actions">${j?.status==='active'?button('End this block','end-block'):button('Start a training block','challenge',true)}</div><small>No punishment for rest. Levels never automatically increase weights or certify technique.</small>`,'gym-level-card')}</div>`;
  }
  function source(){return `<div class="gym-source"><div><b>Your workout, your way</b><small>Suggestions or your own saved routines—both count toward your block.</small></div><div class="gym-actions">${button('Suggested workouts','source:suggested',p().workout_source!=='own')}${button('My own workouts','source:own',p().workout_source==='own')}</div></div>`}
  function ownCard(){return card('Your personal training plan',`<p>Choose a routine, follow it at your own pace, and log each set.</p><div class="gym-actions">${button('＋ Write my routine','own-workout',true)}${button('Load Gym A / B examples','examples')}</div><div class="gym-programs">${data().workouts.map(w=>`<article><h4>${E(w.data.name)}</h4><small>${w.data.duration} minutes · ${w.data.exercises.length} exercises</small><ul>${w.data.exercises.map(e=>`<li>${E(g.GymRules.byId(e.id)?.name||e.name||e.id)} <b>${e.sets} × ${e.reps}${e.reps_max>e.reps?'–'+e.reps_max:''} ${e.unit==='seconds'?'sec':'reps'}</b></li>`).join('')}</ul><div class="gym-actions">${button('Start','program:'+w.id,true)}${button('Schedule','plan:'+w.id)}${button('Edit','own-workout:'+w.id)}</div></article>`).join('')||'<p>No routines saved yet. Write your own, or load the editable Gym A / B examples.</p>'}</div>`)}
  function calendarCard(){return card('▦ Gym in your timetable',`<p>Choose the actual date for Gym A, Gym B or any saved routine. Repeat weekly if you want.</p>${button('＋ Schedule a workout','plan',true)} ${button('Open timetable','open-calendar')}<div class="gym-calendar-list">${data().calendar_workouts.map(e=>`<div class="gym-history-row"><div><b>${E(e.title)}</b><small>${E(e.event_date)} · ${E(e.start_time)}–${E(e.end_time)}${e.recurrence==='weekly'?' · Weekly'+(e.repeat_until?' until '+E(e.repeat_until):''):''} · ${E(e.location)}</small></div>${button('Remove','remove-plan:'+e.id)}</div>`).join('')||'<p class="gym-empty">No linked workouts yet. Existing classes are left untouched.</p>'}</div><small>Change dates/times in Timetable. Each scheduled workout keeps a snapshot; editing or deleting its saved routine does not alter existing calendar entries.</small>`)}
  function profile(){const a=p().athlete||{};modal('Your training profile',`<p>For adults (18+). Used for your starting measurements and planning defaults—not to judge ability or prescribe weights.</p><div class="gym-form-grid">${field('Age','age','number',a.age||'','required min="18" max="100" step="1"')}<label>Gender${select('gender',['Prefer not to say','Woman','Man','Non-binary','Self-described'],a.gender||'Prefer not to say')}</label><label>Lifestyle${select('activity',Object.entries(descriptions),a.activity||'light')}</label>${field('Height (cm)','height','number',a.height||'','required min="100" max="250" step="0.1"')}${field('Weight ('+unit()+')','weight','number',a.weight?display(a.weight):'','required min="1" step="0.1"')}</div><p class="gym-caution">Saved in your private Gym profile. Nutrition uses a separately chosen calculation coefficient, not your gender identity.</p>`,async v=>{await save('athlete',{...v,weight:kg(v.weight)});toast('Training profile saved')})}
  function challenge(){if(!p().athlete){profile();return}const a=p().athlete,baseline=data().measurements.filter(m=>m.data.weight).sort((x,y)=>y.date.localeCompare(x.date))[0]?.data.weight||a.weight;
   modal('Start your next level',`<p>Level ${p().game_level||1} → ${(p().game_level||1)+1}. Starts today. Choose a realistic plan with recovery time; your chosen difficulty stays unchanged.</p><div class="gym-form-grid">${field('Block length (weeks)','weeks','number',8,'required min="4" max="24"')}<label>Training days per week${select('sessions_per_week',[1,2,3,4,5],a.activity==='very'||a.activity==='high'?1:2)}</label><label>Milestone${select('goal',[['consistency','Build consistency'],['gain','My gradual weight-gain goal']],'consistency')}</label>${field('Target weight ('+unit()+', gain goal only)','target_weight','number',display(baseline+2),'min="1" step="0.1"')}</div><p>Current baseline: ${display(baseline)} ${unit()}. Lifestyle only supplies an editable scheduling default. Height and weight can prefill your optional nutrition calculator.</p><ul><li>Finish every planned set at its minimum reps/duration.</li><li>Only one fully logged training day counts per date; each week must meet its own target.</li><li>Wait until the full block ends. For a gain goal, record weight in the final 7 days.</li></ul><p class="gym-caution">Self-reported activity cannot verify safe technique. Gain targets are optional, not a recommendation; the app limits the requested pace to 0.5 kg/week. A health professional can help set a suitable target. <a href="https://www.nhs.uk/live-well/healthy-weight/managing-your-weight/healthy-ways-to-gain-weight/" target="_blank" rel="noopener">Gradual weight gain guidance</a></p>`,async v=>{await save('journey',{...v,weeks:+v.weeks,sessions_per_week:+v.sessions_per_week,target_weight:kg(v.target_weight)});toast('Training block started — your progress will update automatically')})}
  function own(existing){const w=existing?.data;modal(existing?'Edit your routine':'Write your own routine',`${field('Workout name','name','text',w?.name||'Gym A','required maxlength="120"')}${field('Duration (minutes)','duration','number',w?.duration||45,'required min="5" max="240"')}<label>Exercises<textarea name="routine" class="gym-routine-input" rows="9" required placeholder="Squat or leg press | 3 | 8-12 | reps&#10;Plank | 3 | 30-45 | seconds">${E(w?.exercises.map(e=>`${g.GymRules.byId(e.id)?.name||e.name||e.id} | ${e.sets} | ${e.reps}${e.reps_max>e.reps?'-'+e.reps_max:''} | ${e.unit||'reps'}`).join('\n')||'')}</textarea></label><p>One exercise per line: <b>Name | Sets | Reps or range | reps / seconds</b>. Up to 20 exercises; 1–10 sets; targets 1–100. Example: Lunges (each leg) | 3 | 10 | reps. Weights are logged during the workout.</p>`,async v=>{const lines=v.routine.trim().split('\n').filter(x=>x.trim());const exercises=lines.map((line,i)=>{const parts=line.split('|').map(x=>x.trim());const range=parts[2]?.match(/^(\d+)(?:\s*[-–]\s*(\d+))?$/);if(parts.length!==4||!parts[0]||!range||!['reps','seconds'].includes(parts[3]))throw Error('Check line '+(i+1)+': use Name | Sets | 8-12 | reps (or seconds).');const previous=w?.exercises.find(e=>(e.name===parts[0]||g.GymRules.byId(e.id)?.name===parts[0])&&(e.unit||'reps')===parts[3]);return {id:previous?.id||o.uid(),name:parts[0],sets:+parts[1],reps:+range[1],reps_max:+(range[2]||range[1]),unit:parts[3],weight:previous?.weight??null}});await save('workout',{name:v.name,duration:+v.duration,level:'custom',exercises},existing?.id);toast('Your routine is saved')})}
  function plan(id){if(!data().workouts.length){toast('Save a workout first, then schedule it.');return}modal('Add workout to timetable',`<label>Routine${select('workout_id',data().workouts.map(w=>[w.id,w.data.name]),id||data().workouts[0].id)}</label><div class="gym-form-grid">${field('First date','date','date',date(),'required')}${field('Start time','start_time','time','17:00','required')}${field('End time','end_time','time','18:00','required')}<label>Repeat${select('recurrence',[['none','Just this date'],['weekly','Every week']],'none')}</label>${field('Repeat until (optional)','repeat_until','date')}${field('Location','location','text','Gym','maxlength="200"')}</div><p>Creates a green event in your real timetable. It is a plan, not a completed workout. Check your calendar for conflicts before choosing a time.</p>`,async v=>{await save('calendar_workout',v);toast('Workout added to your timetable')})}
  async function examples(){const definitions=[['Gym A',[['Squat or leg press',3,8,12],['Bench press',3,8,12],['Seated cable row',3,8,12],['Romanian deadlift',2,8,10],['Plank',3,30,45,'seconds']]],['Gym B',[['Lunges (each leg)',3,10,10],['Lat pulldown',3,8,12],['Shoulder press',3,8,10],['Hip thrust',3,10,12],['Biceps curls',2,10,15]]]];
   for(const [name,rows] of definitions){if(data().workouts.some(w=>w.data.name===name))continue;await save('workout',{name,duration:45,level:'custom',exercises:rows.map(([name,sets,reps,reps_max,unit='reps'])=>({id:o.uid(),name,sets,reps,reps_max,unit}))})}toast('Gym A / B examples ready. Edit them to suit your own plan.');render()}
  async function act(key,id){if(key==='athlete')profile();else if(key==='challenge')challenge();else if(key==='end-block'){if(confirm('End this block without awarding a level? All workout history is kept.')){await save('end_journey');render()}}else if(key==='source'){await save('workout_source',{source:id});render()}else if(key==='own-workout')own(data().workouts.find(w=>w.id===id));else if(key==='examples')await examples();else if(key==='plan')plan(id);else if(key==='remove-plan'){if(confirm('Remove this scheduled workout (and its weekly repeats) from the timetable?')){await save('delete_calendar_workout',{},id);render()}}else if(key==='open-calendar')o.show('timetable')}
  return {panel,source,ownCard,calendarCard,act,own};
 }
 g.GymJourneyUI={create};
})(window);
