(function(g){
 'use strict';
 const R=g.GymRules,E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),uid=()=>crypto.randomUUID?.()||'gym-'+Date.now()+'-'+Math.random().toString(36).slice(2);
 const names={beginner:'Beginner',intermediate:'Intermediate',advanced:'Advanced',muscle:'Build Muscle',strength:'Strength',fitness:'General Fitness',loss:'Fat Loss',gym:'Full Gym',dumbbells:'Dumbbells Only',bodyweight:'Bodyweight Only'};
 const button=(label,action,primary=false)=>`<button type="button" class="gym-btn ${primary?'primary':''}" data-gym="${action}">${label}</button>`;
 const select=(name,values,value)=>`<select name="${name}">${values.map(v=>{const [key,label]=Array.isArray(v)?v:[v,names[v]||v];return `<option value="${E(key)}" ${String(value)===String(key)?'selected':''}>${E(label)}</option>`}).join('')}</select>`;
 const field=(label,name,type='number',value='',attrs='')=>`<label>${label}<input name="${name}" type="${type}" value="${E(value)}" ${attrs}></label>`;
 const card=(title,body,extra='')=>`<section class="gym-card ${extra}"><h3>${title}</h3>${body}</section>`;
 const empty=text=>`<p class="gym-empty">${text}</p>`;
 function create(o){
  let data=null,page='overview',variant=0,suggestion=null,weekOffset=0,reviewOffset=0,period=56,chartExercise='',notice='',requestBusy=false,dialogDirty=false;
  let timerEnd=null,timerRemaining=90,timerOriginal=90,expanded=true;
  try{expanded=localStorage.getItem('portal.gymExpanded')!=='false'}catch{}
  for(const name of ['overview','workouts','nutrition','progress']){const el=document.createElement('section');el.className='view gym-view';el.id='view-gym-'+name;document.querySelector('.main').append(el)}
  const dialog=document.createElement('dialog');dialog.className='gym-dialog';document.body.append(dialog);
  dialog.addEventListener('cancel',ev=>{if(dialogDirty&&!confirm('Discard unsaved changes?'))ev.preventDefault()});
  dialog.addEventListener('input',()=>dialogDirty=true);
  const p=()=>data?.profile||{},kg=v=>p().units==='lb'?Number(v)/2.2046226218:Number(v),display=v=>Math.round(Number(v)*(p().units==='lb'?2.2046226218:1)*10)/10,unit=()=>p().units||'kg';
  const active=()=>data.sessions.find(s=>s.status==='active');
  const completed=()=>data.sessions.filter(s=>s.status==='completed');
  const finishedSets=()=>{const ids=new Set(completed().map(s=>s.id));return data.sets.filter(s=>ids.has(s.session_id))};
  const root=()=>document.getElementById('view-gym-'+page);
  const date=()=>R.day(new Date());
  const journey=GymJourneyUI.create({data:()=>data,uid,E,button,field,select,card,modal,save,render,toast,date,display,kg,unit,show:o.show});
  function exercise(id){const x=active()?.data.exercises.find(e=>e.id===id)||data.workouts.flatMap(w=>w.data.exercises).find(e=>e.id===id)||data.sessions.flatMap(s=>s.data.exercises).find(e=>e.id===id);return x?.name&&x.name!==id?{name:x.name,muscle:R.byId(id)?.muscle||'Personal',secondary:[],gear:'Your choice',difficulty:0,instructions:'Your own exercise. Follow guidance from your programme or a qualified trainer.'}:R.byId(id)||{name:id,muscle:'Other',secondary:[],gear:'Your choice',difficulty:0,instructions:''}}
  function toast(message){notice=message;document.querySelectorAll('[data-gym-status]').forEach(x=>x.textContent=message)}
  async function refresh(){const r=await fetch('/api/gym');if(!r.ok)throw Error('Could not load Gym data.');data=await r.json();syncNav()}
  async function save(action,values={},id){if(requestBusy)throw Error('Please wait for the current save.');requestBusy=true;try{const r=await fetch('/api/gym',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,data:values,id})}),result=await r.json();if(!r.ok||!result.ok)throw Error(result.error||'Save failed.');await refresh();if(action==='calendar_workout'||action==='delete_calendar_workout')await o.calendarChanged?.();return result}finally{requestBusy=false}}
  function close(){if(dialogDirty&&!confirm('Discard unsaved changes?'))return;dialog.close();dialogDirty=false}
  function modal(title,body,submit){if(dialog.open&&!canLeave())return;dialogDirty=false;dialog.innerHTML=`<div class="gym-dialog-head"><h2>${title}</h2><button type="button" data-close aria-label="Close dialog">×</button></div><form>${body}<p class="gym-error" role="alert"></p><div class="gym-actions">${submit?'<button class="gym-btn primary" type="submit">Save</button>':''}<button class="gym-btn" type="button" data-close>Close</button></div></form>`;
    dialog.querySelectorAll('[data-close]').forEach(b=>b.onclick=close);dialog.querySelector('form').onsubmit=async ev=>{ev.preventDefault();const b=ev.submitter;if(b)b.disabled=true;try{if(submit)await submit(Object.fromEntries(new FormData(ev.target)));dialogDirty=false;dialog.close();render()}catch(err){dialog.querySelector('.gym-error').textContent=err.message}finally{if(b)b.disabled=false}};if(!dialog.open)dialog.showModal();bind(dialog)
  }
  function canLeave(){if(dialog.open&&dialogDirty&&!confirm('Discard unsaved changes?'))return false;if(dialog.open)dialog.close();dialogDirty=false;return true}
  function syncNav(){let nav=document.getElementById('gymNav');if(!nav){nav=document.createElement('div');nav.id='gymNav';nav.className='gym-nav';document.querySelector('.nav [data-view=tutor]').before(nav)}const focusedToggle=document.activeElement?.id==='gymToggle';nav.hidden=!p().enabled;
    nav.innerHTML=`<div class="module-nav-head"><button type="button" data-view="gym-overview" class="${document.getElementById('view-gym-overview').classList.contains('active')?'active':''}" aria-label="Gym overview"><span class="gym-dumbbell"><svg class="gym-weight-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M6 12h12M3 8v8M6 5v14M18 5v14M21 8v8"/></svg></span><span>Gym</span></button><button type="button" id="gymToggle" aria-controls="gymSubnav" aria-expanded="${expanded}" aria-label="Expand or collapse Gym"><span class="gym-chevron" aria-hidden="true">${expanded?'⌃':'›'}</span></button></div><div id="gymSubnav" ${expanded?'':'hidden'}>${['workouts','nutrition','progress'].map(n=>`<button data-view="gym-${n}" class="${document.getElementById('view-gym-'+n).classList.contains('active')?'active':''}">• &nbsp; ${n[0].toUpperCase()+n.slice(1)}</button>`).join('')}</div>`;
    nav.querySelector('#gymToggle').onclick=()=>{expanded=!expanded;try{localStorage.setItem('portal.gymExpanded',expanded)}catch{}syncNav();document.getElementById('gymToggle').focus()};nav.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>o.show(b.dataset.view));if(focusedToggle)document.getElementById('gymToggle').focus();
  }
  function preferences(){return `<div class="gym-preferences">${card('◈ &nbsp; Choose your training level',`<div class="gym-levels">${['beginner','intermediate','advanced'].map((v,i)=>`<button data-pref="level" data-value="${v}" class="${p().level===v?'selected':''}" aria-pressed="${p().level===v}"><span>${['♟','▥','♛'][i]}</span><b>${names[v]}</b><small>${['Learn the movements.<br>Build your routine.','Build on your<br>foundation.','More variety.<br>Your own emphasis.'][i]}</small></button>`).join('')}</div>`)}${card('✦ &nbsp; Your goal',`<div class="gym-goals">${['muscle','strength','fitness','loss'].map((v,i)=>`<button data-pref="goal" data-value="${v}" class="${p().goal===v?'selected':''}" aria-pressed="${p().goal===v}">${['◉','♜','↗','♨'][i]} &nbsp; ${names[v]}</button>`).join('')}</div>`)}${card('<svg class="gym-weight-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M6 12h12M3 8v8M6 5v14M18 5v14M21 8v8"/></svg> &nbsp; Available equipment',`<div class="gym-equipment">${['gym','dumbbells','bodyweight'].map(v=>`<button data-pref="equipment" data-value="${v}" class="${p().equipment===v?'selected':''}" aria-pressed="${p().equipment===v}">${names[v]} <span>${p().equipment===v?'●':'○'}</span></button>`).join('')}</div>`)}${card('Workout length',`<label class="gym-label">Preferred duration${select('duration',[30,45,60,75,90].map(n=>[n,n+' minutes']),p().duration)}</label>`,'gym-duration')}</div>`}
  function workoutCard(){const w=suggestion||R.suggest(p(),variant);suggestion=w;return card(`<svg class="gym-weight-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M6 12h12M3 8v8M6 5v14M18 5v14M21 8v8"/></svg> &nbsp; Today's Suggested Workout`,`<div class="gym-workout-heading"><div><h2>${E(w.name)} <span class="gym-pill">${E(names[w.level]||w.level)}</span></h2><p>${w.duration} minutes · ${[...new Set(w.exercises.map(x=>R.byId(x.id)?.muscle))].join(' • ')}</p></div>${button('↻ Change Workout','change')}</div><div class="gym-exercises"><div class="gym-exercise-head"><span>Exercise</span><span>Sets × Reps</span><span>Weight reference</span><span>Actions</span></div>${w.exercises.map((x,i)=>{const e=R.byId(x.id),last=finishedSets().filter(s=>s.exercise_id===x.id).at(-1);return `<div class="gym-exercise"><button class="gym-exercise-name" data-gym="exercise:${x.id}"><span class="gym-exercise-icon">${e.muscle==='Legs'?'↟':'<svg class="gym-weight-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M6 12h12M3 8v8M6 5v14M18 5v14M21 8v8"/></svg>'}</span><span><b>${E(e.name)}</b><small>${E(e.muscle)}</small></span></button><span>${x.sets} × ${x.reps}</span><small>${last?'Last logged: '+display(last.weight)+' '+unit()+' × '+last.reps:x.weight!=null?'Your target: '+display(x.weight)+' '+unit():'Choose a comfortable starting weight'}</small><div>${button('Log','start:'+i)}${button('⇄','swap:'+i)}</div></div>`}).join('')}</div><div class="gym-actions">${button(active()?'▶ Resume Workout':'▶ Start Workout','start',true)}${button('＋ Save as Program','save-suggestion')}${button('◷ Rest Timer','timer')}</div><small class="gym-caution">General suggestions, not personalised prescriptions. Warm up, keep control and stop if you feel pain or unusual symptoms.</small>`)}
  function totals(d=date()){return data.food_logs.filter(f=>f.date===d).reduce((a,f)=>{for(const k in a)a[k]+=f.data[k];return a},{calories:0,protein:0,carbs:0,fat:0})}
  function nutritionCard(full=false){const n=data.targets,t=totals();return card('♜ &nbsp; Daily Nutrition Targets',`<div class="gym-actions gym-tabs">${button('Calculator','calculator')}${button("Today's Intake",'food')}${button('Nutrition Tips','tips')}</div>${n?`<div class="gym-targets">${['calories','protein','carbs','fat'].map((k,i)=>`<div><span class="gym-macro-icon macro-${i}">${['♨','◈','▤','◆'][i]}</span><small>${k[0].toUpperCase()+k.slice(1)}</small><strong>${n[k].toLocaleString()}</strong><small>${k==='calories'?'kcal':'g'}/day</small></div>`).join('')}</div>${Object.keys(t).map((k,i)=>`<div class="gym-meter"><b>${k[0].toUpperCase()+k.slice(1)}</b><progress class="macro-${i}" value="${Math.min(t[k],n[k])}" max="${Math.max(n[k],1)}"></progress><small>${Math.round(t[k])} / ${n[k]} ${k==='calories'?'kcal':'g'}</small></div>`).join('')}`:empty('Calculate your estimated daily targets when you’re ready. Height and weight are optional for workouts.')+button('＋ Open Calculator','calculator',true)}<p class="gym-caution">These are general estimates and may not reflect individual medical or nutritional needs.</p>${full?`<h4>Today’s food log</h4>${data.food_logs.filter(f=>f.date===date()).map(f=>`<div class="gym-history-row"><div><b>${E(f.data.name)}</b><small>${f.data.calories} kcal · P ${f.data.protein} g · C ${f.data.carbs} g · F ${f.data.fat} g</small></div>${button('Delete','delete-food:'+f.id)}</div>`).join('')||empty('No meals logged today. Add nutrition values from the label or your own estimate.')}<details><summary>Previous intake entries</summary>${data.food_logs.filter(f=>f.date!==date()).map(f=>`<div class="gym-history-row"><span>${E(f.date)} · ${E(f.data.name)} · ${f.data.calories} kcal</span>${button('Delete','delete-food:'+f.id)}</div>`).join('')||empty('No earlier entries.')}</details>`:''}`)}
  function weekCard(){const monday=new Date();monday.setDate(monday.getDate()-(monday.getDay()+6)%7+weekOffset*7);const days=Array.from({length:7},(_,i)=>{const d=new Date(monday);d.setDate(d.getDate()+i);return R.day(d)});return card('▦ &nbsp; This Week',`<div class="gym-week-head">${button('‹','week-prev')}<b>${E(days[0])} – ${E(days[6])}</b>${button('›','week-next')}</div><div class="gym-week">${days.map((d,i)=>{const entry=data.schedule.find(x=>x.date===d),done=completed().some(s=>s.date===d);return `<button data-gym="schedule:${d}" class="${done?'trained':''}"><b>${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][i]}</b><small>${d.slice(8)}</small><span>${done?'✓':'＋'}</span><small>${E(entry?.label||'Plan')}</small></button>`}).join('')}</div><div class="gym-streak"><span>♨</span><div><b>${R.streak(data.sessions)} day streak</b><small>Completed workouts count. Rest matters too.</small></div></div><small class="gym-caution">These are optional day notes. Use Schedule a workout below to add routines to your real timetable.</small>`)}
  function lineChart(points,label){if(!points.length)return empty('No '+label.toLowerCase()+' yet. Your logged history will appear here.');const values=points.map(p=>p.value),lo=Math.min(...values),hi=Math.max(...values),range=hi-lo||1;return `<div class="gym-chart"><svg viewBox="0 0 360 140" role="img" aria-label="${E(label)}"><path d="M35 15V115H345 M35 65H345 M35 15H345" stroke="var(--line)" fill="none"/><polyline points="${points.map((p,i)=>`${35+i*310/Math.max(1,points.length-1)},${110-(p.value-lo)*90/range}`).join(' ')}" fill="none" stroke="var(--primary)" stroke-width="3"/>${points.map((p,i)=>`<circle cx="${35+i*310/Math.max(1,points.length-1)}" cy="${110-(p.value-lo)*90/range}" r="4" fill="var(--primary)"><title>${E(p.date)}: ${p.value}</title></circle>`).join('')}<text x="0" y="20" fill="var(--muted)" font-size="10">${Math.round(hi)}</text><text x="0" y="115" fill="var(--muted)" font-size="10">${Math.round(lo)}</text></svg><div><small>${E(points[0].date)}</small><small>${E(points.at(-1).date)}</small></div></div>`}
  function strengthCard(){const sets=finishedSets().filter(s=>data.sessions.find(w=>w.id===s.session_id)?.data.exercises.find(e=>e.id===s.exercise_id)?.unit!=='seconds');const ids=[...new Set(sets.map(s=>s.exercise_id))];if(!ids.includes(chartExercise))chartExercise=ids[0]||'';const cutoff=new Date();cutoff.setDate(cutoff.getDate()-period);const dated=sets.filter(s=>s.exercise_id===chartExercise).map(s=>({...s,date:data.sessions.find(w=>w.id===s.session_id).date})).filter(s=>s.date>=R.day(cutoff)).sort((a,b)=>a.date.localeCompare(b.date));const bodyweight=dated.length>0&&dated.every(s=>s.weight===0);const map=new Map();for(const s of dated)map.set(s.date,Math.max(map.get(s.date)||0,bodyweight?s.reps:s.weight));const points=[...map].map(([date,v])=>({date,value:bodyweight?v:display(v)}));const best=R.records(sets,data.sessions).find(s=>s.exercise_id===chartExercise);return card('▥ &nbsp; Progress & Strength',`<div class="gym-chart-options"><label>Exercise${select('chartExercise',ids.map(id=>[id,exercise(id).name]),chartExercise)}</label><label>Period${select('period',[[28,'Last 4 weeks'],[56,'Last 8 weeks'],[90,'3 months'],[180,'6 months'],[365,'1 year']],period)}</label></div>${lineChart(points,bodyweight?'Bodyweight repetitions':'Top weight ('+unit()+')')}${best?`<div class="gym-mini-stats"><div><small>${bodyweight?'Best reps, latest day':'Latest top weight'}</small><b>${points.length?points.at(-1).value+' '+(bodyweight?'reps':unit()):'No sets in period'}</b></div><div><small>Personal best</small><b>${best.weight?display(best.weight)+' '+unit():'Bodyweight'} × ${best.reps}</b></div><div><small>Estimated 1RM</small><b>${R.estimated1RM(best)?display(R.estimated1RM(best))+' '+unit():'Not estimated'}</b></div></div><small class="gym-caution">Epley estimate for sets of 1–10 reps, not a recommendation to attempt a maximum.</small>`:''}`)}
  function recordsCard(){const records=R.records(data.sets,data.sessions).sort((a,b)=>b.created_at.localeCompare(a.created_at));return card('♜ &nbsp; Personal Bests',records.map(s=>`<div class="gym-history-row"><span class="gym-exercise-icon"><svg class="gym-weight-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M6 12h12M3 8v8M6 5v14M18 5v14M21 8v8"/></svg></span><div><b>${E(exercise(s.exercise_id).name)}</b><small>${display(s.weight)} ${unit()} × ${s.reps} · ${E(data.sessions.find(w=>w.id===s.session_id)?.date)}</small></div></div>`).join('')||empty('Your personal records will appear as you complete workouts.'))}
  function muscleCard(){const cutoff=new Date();cutoff.setDate(cutoff.getDate()-30);const ids=new Set(completed().filter(s=>s.date>=R.day(cutoff)).map(s=>s.id)),sets=data.sets.filter(s=>ids.has(s.session_id)),counts={};for(const s of sets){const m=R.byId(s.exercise_id)?.muscle||'Other';counts[m]=(counts[m]||0)+1}return card('◈ &nbsp; Muscle Focus · 30 days',Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([m,n])=>`<div class="gym-meter"><b>${m}</b><progress max="${sets.length}" value="${n}"></progress><small>${Math.round(n/sets.length*100)}% · ${n} sets</small></div>`).join('')||empty('Log sets to see your training distribution.'))}
  function weeklyCard(){const now=reviewOffset===0,c=R.weekCompare(data.sessions,data.sets,new Date(),reviewOffset),cur=c.current,prev=c.previous,show=(k,v)=>(k==='volume'?display(v):v).toLocaleString(),plural=(n,w)=>n+' '+w+(n===1?'':'s');
    const labels={workouts:'Workouts',sets:'Sets',reps:'Reps',volume:'Volume ('+unit()+')',seconds:'Timed (sec)'},more=[cur.sets>prev.sets&&plural(cur.sets-prev.sets,'more set'),cur.volume>prev.volume&&show('volume',cur.volume-prev.volume)+' '+unit()+' more volume'].filter(Boolean).join(' and ');
    const status=c.firstWeek?(cur.workouts?'No workouts the week before, so this week sets your first benchmark.':'Complete a workout to set your first weekly benchmark.'):c.beaten?`✓ ${now?'Ahead of last week':'Beat the week before'}: ${more}.`:now?`${plural(c.setsToBeat,'more set')}, or more than ${show('volume',prev.volume)} ${unit()} total volume, to beat last week.`:'Less training than the week before.';
    const gaps=[...cur.missed,...cur.partial];
    return card('▲ &nbsp; Weekly Progress',`<div class="gym-week-head">${button('‹','review-prev')}<b>${E(cur.start)} – ${E(cur.end)}${now?' · this week':''}</b><button type="button" class="gym-btn" data-gym="review-next" ${now?'disabled':''} aria-label="Next week">›</button></div><p class="gym-weekly-status ${c.beaten&&!c.firstWeek?'ahead':''}" data-gym-weekly-status>${E(status)}</p><div class="gym-weekly-grid"><div><h4>${now?'This week':'That week'} vs the week before</h4>${c.metrics.map(x=>`<div class="gym-meter"><b>${labels[x.key]}</b><progress max="${Math.max(x.current,x.previous,1)}" value="${x.current}"></progress><small>${show(x.key,x.current)} / ${show(x.key,x.previous)}${x.beaten?' ✓':''}</small></div>`).join('')}</div><div><h4>Muscles trained</h4><div class="gym-muscles">${R.muscles.map(m=>{const n=cur.primary[m]||0,state=n?'covered':cur.secondary[m]?'partial':'missed';return `<div class="gym-muscle ${state}" data-gym-muscle="${m}"><b>${state==='covered'?'✓':state==='partial'?'◐':'✕'} ${m}</b><small>${n?plural(n,'set'):state==='partial'?'Assisting only':'Not trained'} · before: ${prev.primary[m]||0}</small></div>`}).join('')}</div><p class="gym-weekly-gap">${gaps.length?`${now?'Still to train this week':'Not trained that week'}: <b>${E(gaps.join(', '))}</b>`:`All muscle groups trained ${now?'this week':'that week'}.`}</p></div></div>${cur.unclassified?`<small class="gym-caution">${plural(cur.unclassified,'set')} from your own exercises could not be matched to a muscle group. Names such as “Bench press” or “Leg curl” are recognised.</small>`:''}<small class="gym-caution">Weeks run Monday–Sunday and count completed workouts. “Assisting only” means the muscle only worked as a helper (for example triceps during bench press). Rest and recovery matter as much as doing more.</small>`,'gym-weekly')}
  function toolsCard(){return card('ϟ &nbsp; Quick Tools',`<div class="gym-tools">${button('▤ Plate Calculator','plates')}${button('◷ Rest Timer','timer')}${button('◈ Body Weight','measurement')}${button('↔ Measurements','measurement')}</div>`)}
  function timerMarkup(){return `<div class="gym-timer"><small>REST TIMER</small><strong data-timer-output>01:30</strong><div class="gym-actions">${button('Start','timer-start')}${button('Pause','timer-pause')}${button('Reset','timer-reset')}${button('+30 sec','timer-add')}</div><small>Stops at zero. No sound or notification permissions needed.</small></div>`}
  function tick(){const left=timerEnd?Math.max(0,Math.ceil((timerEnd-Date.now())/1000)):timerRemaining;if(timerEnd&&left===0){timerRemaining=0;timerEnd=null}document.querySelectorAll('[data-timer-output]').forEach(x=>x.textContent=String(Math.floor(left/60)).padStart(2,'0')+':'+String(left%60).padStart(2,'0'))}
  setInterval(tick,250);
  function sessionCard(s){const w=s.data,cursor=w.cursor||0,x=w.exercises[cursor],e=exercise(x.id),sets=data.sets.filter(z=>z.session_id===s.id&&z.exercise_id===x.id),last=sets.at(-1);return card('▶ &nbsp; Active Workout',`<div class="gym-session-head"><div><span class="gym-pill">${E(w.name)} · ${E(s.date)}</span><p>Exercise ${cursor+1} of ${w.exercises.length}</p><h2>${E(e.name)}</h2><p>Planned ${x.sets} sets × ${x.reps}${x.reps_max>x.reps?'–'+x.reps_max:''} ${x.unit==='seconds'?'seconds':'reps'} · ${sets.length} sets logged</p></div><div>${button('Technique','exercise:'+x.id)}${button('Change log date','session-date')}</div></div><form id="gymSetForm" class="gym-set-form">${field('Weight ('+unit()+')','weight','number',last?display(last.weight):x.weight==null?(x.unit==='seconds'?0:''):display(x.weight),'min="0" max="1300" step="0.1" required placeholder="0 for bodyweight"')}${field(x.unit==='seconds'?'Seconds':'Reps','reps','number',x.reps,'min="1" max="100" step="1" required')}<label>Difficulty (optional)${select('rpe',[['','Not recorded'],'Easy','Moderate','Hard','Very Hard'],'')}</label>${field('Notes (optional)','notes','text','','maxlength="2000"')}<button class="gym-btn primary" type="submit">✓ Complete Set ${sets.length+1}</button></form><div class="gym-set-history">${sets.map(z=>`<span>Set ${z.position}: ${display(z.weight)} ${unit()} × ${z.reps} ${x.unit==='seconds'?'sec':'reps'} ${E(z.rpe||'')}</span>`).join('')}</div>${timerMarkup()}<div class="gym-actions">${button('← Previous','cursor:'+Math.max(0,cursor-1))}${button('Next / Skip →','cursor:'+Math.min(w.exercises.length-1,cursor+1))}${button('✓ Finish Workout','finish',true)}${button('Cancel Workout','cancel-session')}</div><small class="gym-caution">Every completed set is saved immediately. You can resume this session on another visit or device. Cancelled sessions are retained but excluded from progress.</small>`,'gym-active')}
  function workoutsPage(){return `${journey.source()}${active()?sessionCard(active()):p().workout_source==='own'?journey.ownCard():workoutCard()}${journey.calendarCard()}${card('Saved Programs',`<div class="gym-actions">${button('＋ Create Workout','custom',true)}</div><div class="gym-programs">${data.workouts.map(w=>`<article><h4>${E(w.data.name)}</h4><p>${E(w.data.level)} · ${w.data.duration} min · ${w.data.exercises.length} exercises</p><small>${[...new Set(w.data.exercises.map(e=>R.byId(e.id)?.muscle||'Other'))].join(' • ')}</small><div class="gym-actions">${button('Start','program:'+w.id,true)}${button('Schedule','plan:'+w.id)}${button('Edit','edit:'+w.id)}${button('Duplicate','duplicate:'+w.id)}${button('Delete','delete:'+w.id)}</div></article>`).join('')||empty('Save a suggested workout or build your own program.')}</div>`)}${card('Workout History',data.sessions.filter(s=>s.status!=='active').map(s=>`<details class="gym-history-detail"><summary>${E(s.data.name)} · ${E(s.date)} · ${E(s.status)}</summary>${data.sets.filter(x=>x.session_id===s.id).map(x=>`<p>${E(exercise(x.exercise_id).name)} · Set ${x.position}: ${display(x.weight)} ${unit()} × ${x.reps} · ${E(x.rpe||'')} ${E(x.notes||'')}</p>`).join('')||'<p>No sets logged.</p>'}</details>`).join('')||empty('No workouts logged yet. Start your first workout to begin tracking progress.'))}${card('Exercise Library',`<p class="gym-caution">Choose an exercise for equipment and basic technique guidance.</p><div class="gym-library">${R.exercises.map(e=>button(E(e.name)+' <small>'+E(e.muscle)+'</small>','exercise:'+e.id)).join('')}</div>`)}`}
  function progressPage(){const weights=data.measurements.filter(m=>m.data.weight).sort((a,b)=>a.date.localeCompare(b.date)).map(m=>({date:m.date,value:display(m.data.weight)}));const days={};for(const s of completed())days[s.date]=(days[s.date]||0)+1;return `${weeklyCard()}<div class="gym-two">${strengthCard()}${muscleCard()}${card('Body Weight Progress',button('＋ Add Measurement','measurement')+lineChart(weights,'Body weight ('+unit()+')'))}${card('Workout Frequency',lineChart(Object.entries(days).sort().map(([date,value])=>({date,value})),'Completed workouts per logged day')+`<p>${completed().length} completed workouts · ${R.streak(data.sessions)} day streak</p>`)}</div><div class="gym-two">${recordsCard()}${card('Measurements',button('＋ Add Measurement','measurement')+data.measurements.map(m=>`<div class="gym-history-row"><b>${E(m.date)}</b><small>${Object.entries(m.data).map(([k,v])=>E(k)+': '+(k==='weight'?display(v)+' '+unit():v+' cm')).join(' · ')}</small></div>`).join('')+(data.measurements.length?'':empty('Your measurement history is kept when you add a new entry.')))}</div>`}
  function render(){if(!data||!p().enabled)return;const el=root();el.innerHTML=`<header class="gym-header"><div class="gym-title-icon"><svg class="gym-weight-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M6 12h12M3 8v8M6 5v14M18 5v14M21 8v8"/></svg></div><div><h1>${page==='overview'?'Gym Hub':page==='workouts'?'Your Workouts':page==='nutrition'?'Nutrition':'Progress & Strength'}</h1><p>Train smarter. Fuel better. Track your progress.</p></div><div class="gym-banner"><b>Discipline today<br>leads to a stronger tomorrow.</b><span>Same student.<br>Stronger you.</span></div></header><p data-gym-status class="gym-status" role="status">${E(notice)}</p>${page==='overview'?`${journey.panel()}${preferences()}${journey.source()}<div class="gym-main-grid">${active()?sessionCard(active()):p().workout_source==='own'?journey.ownCard():workoutCard()}${nutritionCard()}</div>${journey.calendarCard()}${weeklyCard()}<div class="gym-bottom-grid">${weekCard()}<div class="gym-stack">${strengthCard()}${muscleCard()}</div><div class="gym-stack">${toolsCard()}${recordsCard()}</div></div>`:page==='workouts'?workoutsPage():page==='nutrition'?`<div class="gym-two">${nutritionCard(true)}${card('Eat well, study well',`<p>Build regular meals around foods you enjoy. Include varied protein sources, vegetables, fruit, fibre-rich carbohydrates and fats.</p><p>Logs are approximate. You don’t need to hit every number exactly, and tracking is optional.</p>${button('How estimates work','tips')}`)}</div>`:journey.panel()+progressPage()}`;
    bind(el);el.querySelectorAll('[data-pref]').forEach(b=>b.onclick=async()=>{try{await save('profile',{[b.dataset.pref]:b.dataset.value});suggestion=null;toast('Training preferences saved');render()}catch(err){toast(err.message)}});
    el.querySelector('[name=duration]')?.addEventListener('change',async ev=>{try{await save('profile',{duration:+ev.target.value});suggestion=null;toast('Workout duration saved');render()}catch(err){toast(err.message)}});
    el.querySelector('[name=chartExercise]')?.addEventListener('change',ev=>{chartExercise=ev.target.value;render()});el.querySelector('[name=period]')?.addEventListener('change',ev=>{period=+ev.target.value;render()});
    el.querySelector('#gymSetForm')?.addEventListener('submit',async ev=>{ev.preventDefault();const b=ev.submitter||ev.target.querySelector('[type=submit]');b.disabled=true;const values=Object.fromEntries(new FormData(ev.target)),s=active(),x=s.data.exercises[s.data.cursor||0],position=data.sets.filter(z=>z.session_id===s.id&&z.exercise_id===x.id).length+1;try{await save('set',{...values,weight:kg(values.weight),session_id:s.id,exercise_id:x.id,position});timerRemaining=90;timerEnd=Date.now()+90000;toast('Set logged — take a rest.');render()}catch(err){toast(err.message);b.disabled=false}});tick();syncNav()
  }
  async function start(w,index=0){if(active()){page='workouts';o.show('gym-workouts');return}const result=await save('start',{...w,date:date()});if(index)await save('cursor',{session_id:result.id,cursor:index});toast('Workout started. Completed sets are saved automatically.');o.show('gym-workouts')}
  function custom(existing=null){const w=existing?.data||suggestion||R.suggest(p());modal(existing?'Edit Workout':'Create Workout',`${field('Workout name','name','text',existing?w.name:'My workout','required maxlength="120"')}${field('Duration (minutes)','duration','number',w.duration,'min="5" max="240" required')}<p>Tick exercises to include. Sets and reps are required; weight is optional. All library exercises are available for custom programs.</p><div class="gym-custom-list">${R.exercises.map(e=>{const x=existing?w.exercises.find(x=>x.id===e.id):null;return `<div><label><input type="checkbox" name="include_${e.id}" ${x?'checked':''}>${E(e.name)}</label><div>${field('Sets','sets_'+e.id,'number',x?.sets||3,'min="1" max="10"')}${field('Reps','reps_'+e.id,'number',x?.reps||8,'min="1" max="100"')}${field('Target '+unit(),'weight_'+e.id,'number',x?.weight!=null?display(x.weight):'','min="0" step="0.1"')}</div></div>`}).join('')}</div>`,async v=>{const exercises=R.exercises.filter(e=>v['include_'+e.id]).map(e=>({id:e.id,sets:+v['sets_'+e.id],reps:+v['reps_'+e.id],weight:v['weight_'+e.id]===''?null:kg(v['weight_'+e.id])}));await save('workout',{name:v.name,duration:+v.duration,level:'custom',exercises},existing?.id);toast('Workout saved')})}
  function calculator(){const n=data.targets?.inputs||p().athlete||{};modal('Estimated daily nutrition targets',`<p class="gym-caution">Optional adult estimate, not medical advice. Not suitable for pregnancy, breastfeeding or medical dietary needs. Seek individual guidance if needed.</p><div class="gym-form-grid">${field('Height (cm)','height','number',n.height||'','required min="100" max="250" step="0.1"')}${field('Weight ('+unit()+')','weight','number',n.weight?display(n.weight):'','required min="1" step="0.1"')}${field('Age (18+)','age','number',n.age||'','required min="18" max="100"')}<label>Calculation profile${select('sex',[['','Choose explicitly'],['female','Female formula (−161)'],['male','Male formula (+5)']],n.sex||'')}</label><label>Activity level${select('activity',[['','Choose activity'],['sedentary','Sedentary'],['light','Lightly active'],['moderate','Moderately active'],['very','Very active'],['high','Highly active']],n.activity||'')}</label><label>Nutrition goal${select('goal',[['','Choose goal'],['lose','Lose weight'],['maintain','Maintain weight'],['gain','Gain / build muscle']],n.goal||'')}</label></div><label class="gym-check"><input type="checkbox" name="adult_confirmation" required> I am an adult and understand the limitations above.</label><small>The equation uses a sex-based coefficient; choose the formula appropriate for your calculation with professional guidance if unsure. This is separate from gender identity.</small>`,async v=>{await save('nutrition',{...v,weight:kg(v.weight),adult_confirmation:v.adult_confirmation==='on'});toast('Nutrition targets updated')})}
  function measurement(){modal('Add body measurement',`<p>All fields except the date are optional. New entries never overwrite older measurements.</p><div class="gym-form-grid">${field('Date','date','date',date(),'required')}${field('Body weight ('+unit()+')','weight','number','','min="1" step="0.1"')}${['waist','chest','arms','legs'].map(k=>field(k[0].toUpperCase()+k.slice(1)+' (cm)',k,'number','','min="1" max="400" step="0.1"')).join('')}</div>`,async v=>{await save('measurement',{...v,weight:v.weight===''?'':kg(v.weight)});toast('Measurement added')})}
  async function act(action){const [key,...parts]=action.split(':'),id=parts.join(':');try{
   if(key==='change'){variant++;suggestion=R.suggest(p(),variant);render()}
   else if(key==='start')await start(suggestion||R.suggest(p(),variant),+id||0);
   else if(key==='save-suggestion'){await save('workout',suggestion||R.suggest(p(),variant));toast('Program saved');render()}
   else if(key==='swap'){const x=suggestion.exercises[+id],pool=R.swaps(x.id,p()).filter(e=>!suggestion.exercises.some(z=>z.id===e.id));modal('Swap exercise',`<p>Same primary muscle, compatible equipment. Review technique before trying a new movement.</p>${pool.length?`<label>Alternative${select('exercise',pool.map(e=>[e.id,e.name]),pool[0].id)}</label>`:empty('No unused compatible alternatives for this workout.')}`,pool.length?async v=>{suggestion.exercises[+id]={...x,id:v.exercise,weight:null}}:null)}
   else if(key==='exercise'){const e=exercise(id);modal(E(e.name),`<span class="gym-pill">${E(e.muscle)}</span><p>Secondary: ${E(e.secondary.join(', ')||'None listed')}</p><p>Equipment: ${E(e.gear)} · ${['Beginner','Intermediate','Advanced'][e.difficulty]}</p><p class="gym-technique">${E(e.instructions)}</p><p class="gym-caution">Stop if you experience pain or unusual symptoms. These brief cues are not a substitute for hands-on coaching.</p>`)}
   else if(key==='cursor'){await save('cursor',{session_id:active().id,cursor:+id});render()}
   else if(key==='session-date'){modal('Workout log date',field('Date','date','date',active().date,'required max="'+date()+'"'),async v=>{await save('session_date',{session_id:active().id,date:v.date});toast('Workout date updated')})}
   else if(key==='finish'){if(!confirm('Finish this workout? Your logged sets will count towards progress.'))return;const before=R.records(data.sets,data.sessions),s=active();await save('finish',{session_id:s.id});const after=R.records(data.sets,data.sessions),pr=after.some(a=>a.session_id===s.id&&!before.some(b=>b.exercise_id===a.exercise_id&&b.weight>=a.weight&&b.reps>=a.reps));toast('Workout completed'+(pr?' · New personal best! 🎉':''));timerEnd=null;timerRemaining=90;render()}
   else if(key==='cancel-session'){if(confirm('Cancel this workout? Logged sets will be kept in cancelled history but excluded from progress.')){await save('cancel',{session_id:active().id});toast('Workout cancelled');render()}}
   else if(key==='timer'){modal('Rest timer',timerMarkup());tick()}
   else if(key==='timer-start'){if(!timerEnd){if(!timerRemaining)timerRemaining=timerOriginal;timerEnd=Date.now()+timerRemaining*1000}}
   else if(key==='timer-pause'){if(timerEnd)timerRemaining=Math.max(0,Math.ceil((timerEnd-Date.now())/1000));timerEnd=null;tick()}
   else if(key==='timer-reset'){timerEnd=null;timerRemaining=timerOriginal;tick()}
   else if(key==='timer-add'){if(timerEnd)timerEnd+=30000;else timerRemaining+=30;tick()}
   else if(key==='week-prev'||key==='week-next'){weekOffset+=key==='week-next'?1:-1;render()}else if(key==='review-prev'||key==='review-next'){reviewOffset=Math.min(0,reviewOffset+(key==='review-next'?1:-1));render()}
   else if(key==='schedule'){modal('Plan training · '+E(id),field('Session / Rest / Cardio','label','text',data.schedule.find(s=>s.date===id)?.label||'','maxlength="120"'),async v=>{await save('schedule',{date:id,label:v.label});toast('Training plan saved')})}
   else if(key==='calculator')calculator();
   else if(key==='food'){modal('Log food or a meal',`<div class="gym-form-grid">${field('Date','date','date',date(),'required')}${field('Food / meal name','name','text','','required maxlength="150"')}${['calories','protein','carbs','fat'].map(k=>field(k==='calories'?'Calories (kcal)':k+' (g)',k,'number','','required min="0" step="0.1"')).join('')}</div>`,async v=>{await save('food',v);toast('Intake saved')})}
   else if(key==='delete-food'){if(confirm('Delete this food entry?')){await save('delete_food',{},id);toast('Food entry deleted');render()}}
   else if(key==='measurement')measurement();
   else if(key==='tips')modal('How the estimates work',`<p>Calories: Mifflin–St Jeor resting estimate × activity factor (1.2–1.9). Gain/loss applies a modest ±10% adjustment.</p><p>Protein: 1.4 g/kg for maintenance, 1.6 g/kg for gain, 1.8 g/kg for loss. Fat uses 30% of calories; carbohydrate is the remainder. These are adjustable general estimates for exercising adults, not individual requirements.</p><p><a href="https://pubmed.ncbi.nlm.nih.gov/2305711/" target="_blank" rel="noopener">Mifflin–St Jeor research</a> · <a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC5477153/" target="_blank" rel="noopener">ISSN protein position stand</a></p><p>Choose a variety of foods, drink to meet your needs, and allow recovery between demanding sessions. No supplements are required by this app.</p><p class="gym-caution">If tracking causes distress, you can stop or disable Gym without losing your records. A qualified dietitian can offer individual support.</p>`);
   else if(key==='plates'){modal('Plate calculator',`<div class="gym-form-grid">${field('Target total ('+unit()+')','target','number','','min="0" step="0.1"')}${field('Bar weight ('+unit()+')','bar','number',unit()==='kg'?20:45,'min="0" step="0.1"')}</div><p data-plate-result role="status">Enter a target and the actual bar weight.</p><small>Assumes unlimited standard plates; does not include collars. Results are per side.</small>`);const compute=()=>{try{const f=dialog.querySelector('form');if(f.elements.target.value==='')return;const r=R.plates(+f.elements.target.value,+f.elements.bar.value,unit());dialog.querySelector('[data-plate-result]').textContent='Per side: '+(r.plates.map(p=>p.count+' × '+p.size+' '+unit()).join(' + ')||'No plates')+(r.remainder?' · Unloadable remainder: '+r.remainder+' '+unit()+' total.':' · Exact load.')}catch(err){dialog.querySelector('[data-plate-result]').textContent=err.message}};dialog.querySelectorAll('input').forEach(x=>x.oninput=compute)}
   else if(key==='custom')custom();
   else if(key==='edit'){const w=data.workouts.find(w=>w.id===id);if(w.data.exercises.some(e=>!R.byId(e.id)||e.unit==='seconds'||e.reps_max>e.reps))journey.own(w);else custom(w)}
   else if(key==='program')await start(data.workouts.find(w=>w.id===id).data);
   else if(key==='duplicate'){const w=data.workouts.find(w=>w.id===id).data;await save('workout',{...w,name:w.name+' (copy)'});toast('Workout duplicated');render()}
   else if(key==='delete'){if(confirm('Delete this saved program? Completed and active workout history will be kept.')){await save('delete_workout',{},id);toast('Program deleted');render()}}
   else await journey.act(key,id);
  }catch(err){toast(err.message);if(dialog.open)dialog.querySelector('.gym-error').textContent=err.message}}
  function bind(el){el.querySelectorAll('[data-gym]').forEach(b=>b.onclick=()=>act(b.dataset.gym))}
  function renderSettings(){const host=document.getElementById('portalSettings');if(!host)return;host.querySelector('.gym-settings')?.remove();const section=document.createElement('section');section.className='gym-card gym-settings';section.innerHTML=`<h3>Modules / Features</h3><div class="gym-module-row"><div><h4><svg class="gym-weight-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M6 12h12M3 8v8M6 5v14M18 5v14M21 8v8"/></svg> Gym Module</h4><p>Track workouts, nutrition and strength progress. Optional, stored locally.</p></div><label class="gym-switch"><input type="checkbox" id="gymEnabled" ${p().enabled?'checked':''} ${!data?'disabled':''}> <span>${p().enabled?'Enabled':'Enable Gym'}</span></label></div><p class="gym-caution">Your Gym data will be kept when disabled. Enable it again to restore access.</p>${p().enabled?`<form id="gymPreferences"><div class="gym-form-grid"><label>Preferred units${select('units',[['kg','Kilograms (kg)'],['lb','Pounds (lb)']],p().units)}</label><label>Training level${select('level',['beginner','intermediate','advanced'],p().level)}</label><label>Goal${select('goal',['muscle','strength','fitness','loss'],p().goal)}</label><label>Equipment${select('equipment',['gym','dumbbells','bodyweight'],p().equipment)}</label><label>Workout duration${select('duration',[30,45,60,75,90].map(x=>[x,x+' minutes']),p().duration)}</label></div><button class="gym-btn primary">Save Gym preferences</button></form>`:''}<p data-gym-settings-status role="status"></p>`;host.append(section);
   section.querySelector('#gymEnabled').onchange=async ev=>{const enabled=ev.target.checked;if(!enabled&&!confirm('Disable Gym? Your Gym data will be kept. You can enable the module again later.')){ev.target.checked=true;return}try{await save('profile',{enabled});renderSettings()}catch(err){ev.target.checked=!enabled;section.querySelector('[data-gym-settings-status]').textContent=err.message}};
   section.querySelector('#gymPreferences')?.addEventListener('submit',async ev=>{ev.preventDefault();const values=Object.fromEntries(new FormData(ev.target));try{await save('profile',{...values,duration:+values.duration});suggestion=null;section.querySelector('[data-gym-settings-status]').textContent='Gym preferences saved'}catch(err){section.querySelector('[data-gym-settings-status]').textContent=err.message}})
  }
  async function onShow(name){document.body.classList.toggle('gym-open',name.startsWith('gym-'));if(name==='settings')renderSettings();if(!name.startsWith('gym-'))return;page=name.slice(4);try{await refresh();if(!p().enabled){o.show('settings');return}render()}catch(err){root().innerHTML=card('Gym unavailable',empty(E(err.message)))}}
  async function init(){try{await refresh();renderSettings()}catch(err){notice=err.message;renderSettings();document.querySelector('[data-gym-settings-status]').textContent='Gym could not load. Restart the local server, then refresh.'}}
  window.addEventListener('beforeunload',ev=>{if(dialog.open&&dialogDirty){ev.preventDefault();ev.returnValue=''}});
  return {init,onShow,renderSettings,canLeave};
 }
 g.StudentGym={create};
})(window);
