const fetch=require('../support/authenticated_fetch.js');
// Run against tests/planner/calendar_browser_server.py and an isolated CDP browser on 9333.
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
  const fixture=await fetch('http://127.0.0.1:8794/api/portal').then(r=>r.json());
  for(const e of fixture.timetable_events)await fetch('http://127.0.0.1:8794/api/portal/delete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({table:'timetable_events',id:e.id})});
  const pages=await fetch('http://127.0.0.1:9333/json/list').then(r=>r.json());
  const ws=new WebSocket(pages.find(p=>p.type==='page').webSocketDebuggerUrl);
  await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject});
  let id=0;const pending=new Map(),errors=[];
  ws.onmessage=({data})=>{const m=JSON.parse(data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(m.error.message)):p.resolve(m.result)}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text)};
  const call=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}))});
  const js=async expression=>{const r=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};
  const wait=async expression=>{for(let i=0;i<70;i++){if(await js(expression))return;await new Promise(r=>setTimeout(r,100))}throw Error('Timed out: '+expression)};
  await call('Runtime.enable');await call('Page.enable');
  await call('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
  await fetch.browser('http://127.0.0.1:8794',call);await call('Page.navigate',{url:'http://127.0.0.1:8794'});
  await wait("document.querySelector('#calendarJump')!==null");
  await js("document.querySelector('[data-go=timetable]').click()");
  const initial=await js("document.querySelector('.calendar-navigation h3').textContent");
  await js("document.querySelector('#calendarNext').click()");
  assert.notEqual(await js("document.querySelector('.calendar-navigation h3').textContent"),initial);
  const jump=async d=>js(`document.querySelector('#calendarJump').value='${d}';document.querySelector('#calendarJump').dispatchEvent(new Event('change'))`);
  await jump('2027-01-10');
  await js("document.querySelector('[data-calendar-add=\"2027-01-10\"]').click()");
  await js("var f=document.querySelector('.calendar-form');f.elements.title.value='Future appointment';f.elements.start_time.value='14:30';f.elements.end_time.value='15:45';f.requestSubmit()");
  await wait("!document.querySelector('.calendar-form')");
  await wait("document.querySelector('#portalTimetable').textContent.includes('Future appointment')");
  const loaded=new Promise(resolve=>{const listener=({data})=>{if(JSON.parse(data).method==='Page.loadEventFired'){ws.removeEventListener('message',listener);resolve()}};ws.addEventListener('message',listener)});
  await call('Page.reload');await loaded;await wait("document.querySelector('#calendarJump')!==null");
  await js("document.querySelector('[data-go=timetable]').click()");await jump('2027-01-10');
  assert.equal(await js("document.querySelectorAll('[data-calendar-event]').length"),1);
  await jump('2027-02-01');
  await js("document.querySelector('#calendarNew').click();var f=document.querySelector('.calendar-form');f.elements.title.value='Semester class';f.elements.recurrence.value='weekly';f.elements.recurrence.dispatchEvent(new Event('change'));f.elements.repeat_until.value='2027-02-15';f.requestSubmit()");
  await wait("!document.querySelector('.calendar-form')");
  await wait("document.querySelectorAll('[data-calendar-event]').length===3");
  await js("document.querySelector('[data-calendar-event]').click();document.querySelector('.calendar-form').elements.title.value='Renamed class';document.querySelector('.calendar-form').requestSubmit()");
  await wait("!document.querySelector('.calendar-form')");
  await wait("document.querySelector('#portalTimetable').textContent.includes('Renamed class')");
  await jump('2027-03-01');assert.equal(await js("document.querySelectorAll('[data-calendar-event]').length"),0);
  await jump('2027-02-08');await js("document.querySelector('[data-calendar-view=week]').click()");
  assert.equal(await js("document.querySelectorAll('.calendar-week .calendar-day').length"),7);
  await js("document.querySelector('[data-calendar-view=day]').click()");
  assert.equal(await js("document.querySelectorAll('[data-calendar-event]').length"),1);
  await js("document.querySelector('[data-calendar-view=month]').click()");
  await call('Page.captureScreenshot',{format:'png'}).then(r=>fs.writeFileSync(process.env.TEMP+'/student-calendar-desktop.png',Buffer.from(r.data,'base64')));
  await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  assert(await js("document.querySelector('.calendar-scroll').scrollWidth>document.querySelector('.calendar-scroll').clientWidth"));
  await js("document.querySelector('[data-calendar-event]').click()");
  assert(await js("document.querySelector('.calendar-form').getBoundingClientRect().width<=390"));
  await call('Page.handleJavaScriptDialog',{accept:true}).catch(()=>{});
  const dialog=new Promise(resolve=>{const listener=({data})=>{const m=JSON.parse(data);if(m.method==='Page.javascriptDialogOpening'){ws.removeEventListener('message',listener);call('Page.handleJavaScriptDialog',{accept:true}).then(resolve)}};ws.addEventListener('message',listener)});
  const deletion=js("document.querySelector('[data-delete]').click()");await dialog;await deletion;
  await wait("!document.querySelector('.calendar-form')");
  await wait("document.querySelectorAll('[data-calendar-event]').length===0");
  assert.deepEqual(errors,[]);
  console.log('PASS browser: month navigation, future create/save/reload, bounded weekly repeat, edit, week/day views, mobile scrolling/form, delete series; no JavaScript errors.');
  ws.close();
})().catch(e=>{console.error(e);process.exit(1)});
