const assert=require('node:assert/strict');
module.exports=async function(js,call){
 const pause=()=>new Promise(r=>setTimeout(r,250));
 const wait=async expression=>{for(let i=0;i<60;i++){if(await js(expression))return;await pause()}throw Error('Timed out: '+expression)};
 await call('Emulation.setDeviceMetricsOverride',{width:1400,height:1000,deviceScaleFactor:1,mobile:false});
 await js("showView('dashboard')");await pause();
 const geometry="JSON.stringify(['.dash-timetable','.dash-reminders','.dash-deadlines','.dash-schedule','.dash-actions-column'].map(s=>{const r=document.querySelector(s).getBoundingClientRect();return [r.x,r.y,r.width,r.height]}))";
 const before=await js(geometry),original=await js("document.querySelector('.dash-actions-column').innerHTML");
 const academicBefore=await js("fetch('/api/portal').then(r=>r.json()).then(p=>JSON.stringify([p.reminders,p.timetable_events]))");
 await js("showView('settings');document.querySelector('#generalTodosEnabled').click()");
 await wait("document.querySelector('#generalTodosEnabled').checked&&!document.querySelector('#generalTodosEnabled').disabled");
 await js("showView('dashboard')");await wait("!!document.querySelector('.general-todo-card')");
 assert.equal(await js(geometry),before,'Surrounding card geometry must not change');
 const add=async(title,button=false)=>{await js(`(()=>{const f=document.querySelector('.general-todo-card .todo-quick');f.elements.title.value=${JSON.stringify(title)};${button?"f.querySelector('button').click()":"f.requestSubmit()"}})()`);await wait("!document.querySelector('.general-todo-card .todo-quick').dataset.busy")};
 await add('  ');assert.equal(await js("document.querySelectorAll('.general-todo-row').length"),0);
 await js("window.todoTestFetch=window.fetch;window.fetch=(url,...args)=>url==='/api/general-todos'?Promise.reject(Error('Test save failure')):window.todoTestFetch(url,...args)");
 await add('Keep draft on error');assert.equal(await js("document.querySelector('.general-todo-card .todo-quick input').value"),'Keep draft on error');
 assert(await js("document.querySelector('.general-todo-card [data-todo-message]').textContent.includes('Test save failure')"));
 await js("window.fetch=window.todoTestFetch;delete window.todoTestFetch");
 await add('Buy groceries');await add('Laundry',true);
 assert.equal(await js("document.querySelectorAll('.general-todo-row').length"),2);
 assert.equal(await js("document.querySelector('.general-todo-card .todo-quick input').value"),'');
 await js("document.querySelector('.general-todo-card [data-toggle]').click()");await wait("!!document.querySelector('.general-todo-card .todo-completed')");
 await js("document.querySelector('.general-todo-card .todo-completed [data-toggle]').click()");await wait("!document.querySelector('.todo-completed')");
 await js("(()=>{const s=document.querySelector('.general-todo-card select');s.value='in_progress';s.dispatchEvent(new Event('change'))})()");await wait("!!document.querySelector('.general-todo-card .status-in_progress')");
 await js("document.querySelector('.general-todo-card [data-edit]').click()");
 await js("(()=>{const f=document.querySelector('.todo-editor form');f.elements.due_date.value='2026-09-25';f.elements.due_time.value='12:00';f.elements.notes.value='Personal only';f.requestSubmit()})()");await wait("!document.querySelector('.todo-editor')");
 assert(await js("!!document.querySelector('.general-todo-row small')"));
 await js("document.querySelector('.general-todo-card [data-edit]').click();document.querySelector('[data-duplicate]').click()");await wait("!document.querySelector('.todo-editor')");
 assert.equal(await js("document.querySelectorAll('.general-todo-row').length"),3);
 await js("document.querySelector('[data-view-todos]').click()");
 await js("(()=>{const s=document.querySelector('[data-search]');s.value='Laundry';s.dispatchEvent(new Event('input'))})()");
 assert(await js("[...document.querySelectorAll('.todo-manager .reminder-detail')].every(e=>e.textContent.includes('Laundry'))"));
 await js("document.querySelector('.todo-manager').close()");
 await js("document.querySelector('.general-todo-card [data-edit]').click();window.todoTestConfirm=window.confirm;window.confirm=()=>false;document.querySelector('[data-delete]').click()");
 assert(await js("!!document.querySelector('.todo-editor')"));
 await js("window.confirm=()=>true;document.querySelector('[data-delete]').click();window.confirm=window.todoTestConfirm;delete window.todoTestConfirm");await wait("!document.querySelector('.todo-editor')");
 assert.equal(await js("document.querySelectorAll('.general-todo-row').length"),2);
 for(let i=0;i<9;i++)await add('Extra personal task '+i);
 assert(await js("(()=>{const c=document.querySelector('.general-todo-card'),l=c.querySelector('.todo-list'),f=c.querySelector('form');l.scrollTop=9999;return l.scrollHeight>l.clientHeight&&f.getBoundingClientRect().bottom<=c.getBoundingClientRect().bottom})()"));
 assert.equal(await js(geometry),before);
 const count=await js("document.querySelectorAll('.general-todo-row').length");
 await js("showView('settings');document.querySelector('#generalTodosEnabled').click()");await wait("!document.querySelector('#generalTodosEnabled').checked&&!document.querySelector('#generalTodosEnabled').disabled");
 await js("showView('dashboard')");assert.equal(await js("document.querySelector('.dash-actions-column').innerHTML"),original);
 await js("showView('settings');document.querySelector('#generalTodosEnabled').click()");await wait("document.querySelector('#generalTodosEnabled').checked&&!document.querySelector('#generalTodosEnabled').disabled");await js("showView('dashboard')");
 assert.equal(await js("document.querySelectorAll('.general-todo-row').length"),count);
 assert.equal(await js("fetch('/api/portal').then(r=>r.json()).then(p=>JSON.stringify([p.reminders,p.timetable_events]))"),academicBefore);
 await js('window.beforeTodoReload=true');await call('Page.reload');await wait("!window.beforeTodoReload && document.querySelectorAll('.general-todo-row').length==="+count);
 await js("document.body.classList.add('dark');document.querySelector('.general-todo-card').scrollIntoView({block:'center'})");
 const fs=require('node:fs'),path=require('node:path'),os=require('node:os');
 const screenshot=async name=>{const shot=await call('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(os.tmpdir(),name),Buffer.from(shot.data,'base64'))};
 await screenshot('general-todos-desktop-dark.png');
 for(const width of [320,390,744]){await call('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:true});await pause();for(const dark of [false,true]){await js(`document.body.classList.toggle('dark',${dark})`);assert(await js("document.documentElement.scrollWidth<=innerWidth"));assert(await js("(()=>{const c=document.querySelector('.general-todo-card'),f=c.querySelector('form');return f.getBoundingClientRect().bottom<=c.getBoundingClientRect().bottom&&f.getBoundingClientRect().width>100})()"))}}
 await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await pause();await js("document.body.classList.remove('dark');document.querySelector('.general-todo-card').scrollIntoView({block:'center'})");await screenshot('general-todos-mobile-light.png');
 console.log('PASS General To-Do: exact dashboard geometry, toggle restoration, quick add, status/circle, editor, duplicate, manager, scrolling and responsive themes.');
};
