const fetch=require('../support/authenticated_fetch.js');
const assert=require('node:assert/strict');
(async()=>{
 const fixture=await fetch('http://127.0.0.1:8794/api/portal').then(r=>r.json());
 for(const r of fixture.reminders)await fetch('http://127.0.0.1:8794/api/portal/delete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({table:'reminders',id:r.id})});
 const pages=await fetch('http://127.0.0.1:9333/json/list').then(r=>r.json());
 const ws=new WebSocket(pages.find(p=>p.type==='page').webSocketDebuggerUrl);
 await new Promise(r=>ws.onopen=r);let id=0;const pending=new Map();
 ws.onmessage=({data})=>{const m=JSON.parse(data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(m.error.message)):p.resolve(m.result)}};
 const call=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}))});
 const js=async expression=>{const r=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};
 const wait=async expression=>{for(let i=0;i<1200;i++){if(await js(expression))return;await new Promise(r=>setTimeout(r,250))}throw Error('Timed out: '+expression)};
 await fetch.browser('http://127.0.0.1:8794',call);await call('Page.navigate',{url:'http://127.0.0.1:8794'});
 await wait("document.querySelector('#calendarJump')!==null");
 await js(`document.querySelector('[data-view=tutor]').click();document.querySelector('#tutorInput').value='help me put a reminder for recurring comp1521 lab submission on every monday until 16 november (monday) 2026';document.querySelector('#tutorComposer').requestSubmit()`);
 await wait("document.querySelector('.reminders-form')!==null");
 assert.equal(await js("document.querySelector('[name=due_date]').value"),'2026-09-21');
 assert.equal(await js("document.querySelector('[name=repeat_until]').value"),'2026-11-16');
 assert.equal(await js("document.querySelector('[name=due_time]').value"),'');
 assert.match(await js("document.querySelector('.reminder-preview').textContent"),/9 reminders/);
 const state=()=>fetch('http://127.0.0.1:8794/api/portal').then(r=>r.json());
 assert.equal((await state()).reminders.length,0);
 await js("document.querySelector('[data-cancel]').click()");
 assert.equal((await state()).reminders.length,0);
 await js("[...document.querySelectorAll('#tutorChat button')].find(b=>b.textContent.includes('Review reminders')).click();document.querySelector('.reminders-form').requestSubmit()");
 await wait("document.querySelector('.reminders-form')===null");
 assert.equal((await state()).reminders.length,9);
 await js("document.querySelector('[data-go=timetable]').click();document.querySelector('#calendarJump').value='2026-11-16';document.querySelector('#calendarJump').dispatchEvent(new Event('change'));document.querySelector('[data-calendar-view=day]').click()");
 assert.equal(await js("document.querySelectorAll('[data-calendar-reminder]').length"),1);
 assert.equal(await js("document.querySelector('[data-calendar-reminder]').style.getPropertyValue('--event-color')"),'#e34859');
 await js("document.querySelector('[data-calendar-reminder]').click();document.querySelector('[data-complete]').click()");
 await wait("document.querySelector('.reminders-form')===null");
 assert.equal((await state()).reminders.filter(r=>r.completed).length,1);
 assert.equal(await js("document.querySelectorAll('.calendar-reminder.reminder-completed').length"),1);
 await js("document.querySelector('#calendarJump').value='2026-11-23';document.querySelector('#calendarJump').dispatchEvent(new Event('change'))");
 assert.equal(await js("document.querySelectorAll('[data-calendar-reminder]').length"),0);
 console.log('PASS live Ollama chat -> review -> cancel/reopen -> nine weekly reminders -> red calendar -> independent completion -> end boundary');
 ws.close();
})().catch(e=>{console.error(e);process.exit(1)});
