// Real login UI with temporary fixture accounts only; no production credentials.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
(async()=>{
 const base='http://127.0.0.1:'+process.argv[2],debug=process.argv[3],pages=await fetch('http://127.0.0.1:'+debug+'/json/list').then(r=>r.json()),ws=new WebSocket(pages.find(p=>p.type==='page').webSocketDebuggerUrl);
 await new Promise(r=>ws.onopen=r);let id=0;const pending=new Map(),errors=[];const call=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}))});
 ws.onmessage=({data})=>{const m=JSON.parse(data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(m.error.message)):p.resolve(m.result)}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text);else if(m.method==='Page.javascriptDialogOpening')call('Page.handleJavaScriptDialog',{accept:true})};
 const js=async expression=>{const r=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};
 const wait=async exp=>{for(let i=0;i<150;i++){if(await js(exp))return;await new Promise(r=>setTimeout(r,80))}throw Error('Timed out: '+exp)};
 const click=sel=>js(`document.querySelector(${JSON.stringify(sel)}).click()`);
 const submit=async(selector,values)=>js(`(()=>{const f=document.querySelector(${JSON.stringify(selector)});for(const [k,v] of Object.entries(${JSON.stringify(values)})){f.elements[k].value=v}f.requestSubmit()})()`);
 const shot=async name=>{const r=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});fs.writeFileSync(path.join(os.tmpdir(),name),Buffer.from(r.data,'base64'))};
 await call('Runtime.enable');await call('Page.enable');await call('Emulation.setDeviceMetricsOverride',{width:1440,height:950,deviceScaleFactor:1,mobile:false});await call('Page.navigate',{url:base});
 await wait("location.pathname==='/login'&&!!document.querySelector('#loginForm')");await shot('portal-login-desktop.png');
 await submit('#loginForm',{username:'admin',password:'Wrong-password-123'});await wait("document.querySelector('#loginError').textContent.includes('Incorrect')");
 await submit('#loginForm',{username:'admin',password:'Fixture-password-123!'});await wait("!!document.querySelector('.nav [data-view=settings]')&&!!document.querySelector('#gymEnabled')");assert.equal(await js("document.cookie.includes('portal_session')"),false);
 await click('.nav [data-view=settings]');await wait("!!document.querySelector('#accountProfile')");await click('[data-avatar-choice=fox]');await submit('#accountProfile',{display_name:'Test Profile',university:'University of Testing',course:'Computing',bio:'Learning one day at a time.'});await wait("document.querySelector('#accountFeedback').textContent.includes('Saved')");assert(await js("document.querySelector('[data-avatar]').textContent.includes('🦊')"));
 await js("(()=>{const canvas=document.createElement('canvas');canvas.width=canvas.height=32;canvas.getContext('2d').fillRect(0,0,32,32);return new Promise(resolve=>canvas.toBlob(blob=>{const transfer=new DataTransfer();transfer.items.add(new File([blob],'avatar.png',{type:'image/png'}));const input=document.querySelector('#profilePhoto');input.files=transfer.files;input.dispatchEvent(new Event('change'));resolve()},'image/png'))})()");await wait("!!document.querySelector('#profilePreview img')");await submit('#accountProfile',{});await wait("document.querySelector('#accountFeedback').textContent.includes('Saved')");assert(await js("!!document.querySelector('[data-avatar] img')"));
 await click('[data-account-tab=appearance]');await submit('#accountAppearance',{theme:'dark',accent:'teal',density:'compact'});await wait("document.querySelector('#accountFeedback').textContent.includes('Saved')");assert(await js("document.body.classList.contains('dark')&&document.body.dataset.accountAccent==='teal'"));
 await click('[data-account-tab=profile]');await shot('portal-settings-desktop.png');
 await click('[data-account-tab=admin]');await wait("!!document.querySelector('#adminCreate')");await js("document.querySelector('.create-account').open=true");await submit('#adminCreate',{username:'newstudent',display_name:'New Student',password:'New-student-password!',role:'student'});await wait("document.querySelector('#accountUsers').textContent.includes('newstudent')");
 await click('[data-account-tab=security]');await wait("document.querySelector('#accountSessions').textContent.includes('This device')");await click('[data-account=revoke]');await wait("document.querySelector('#accountFeedback').textContent.includes('Other devices')");await click('.account-hero [data-account=logout]');await wait("location.pathname==='/login'&&!!document.querySelector('#loginForm')");
 await submit('#loginForm',{username:'newstudent',password:'New-student-password!'});await wait("!!document.querySelector('#loginForm [name=new_password]')");await submit('#loginForm',{current_password:'New-student-password!',new_password:'Changed-student-password!',confirm_password:'Changed-student-password!'});await wait("!!document.querySelector('#loginForm [name=username]')");await submit('#loginForm',{username:'newstudent',password:'Changed-student-password!'});await wait("!!document.querySelector('#gymEnabled')");
 assert.equal(await js("Object.keys(state.subjects).length"),0);assert.equal(await js("document.querySelector('#gymEnabled').checked"),false);await click('.nav [data-view=settings]');await wait("!!document.querySelector('#accountProfile')");assert.equal(await js("!!document.querySelector('[data-account-tab=admin]')"),false);assert.equal(await js("document.body.classList.contains('dark')"),await js("matchMedia('(prefers-color-scheme: dark)').matches"));
 await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await shot('portal-settings-mobile.png');assert(await js("document.documentElement.scrollWidth<=innerWidth"));await click('.account-hero [data-account=logout]');await wait("location.pathname==='/login'&&!!document.querySelector('#loginForm')");await shot('portal-login-mobile.png');assert(await js("document.documentElement.scrollWidth<=innerWidth"));
 assert.deepEqual(errors,[]);console.log('PASS accounts browser: real sign-in, bad password, HttpOnly session, profile/avatar/photo, persistent appearance, admin creation, forced password change, isolated student workspace, logout, mobile login/settings');ws.close();
})().catch(e=>{console.error(e);process.exit(1)});
