const fetch=require('../../support/authenticated_fetch.js');
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
(async()=>{
 const base=`http://127.0.0.1:${process.argv[2]}`,debug=process.argv[3];
 assert(process.argv[2]&&debug,'Use run_tests.py --browser to start isolated services.');
 const pages=await fetch(`http://127.0.0.1:${debug}/json/list`).then(r=>r.json());
 const ws=new WebSocket(pages.find(p=>p.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);
 let id=0;const pending=new Map(),errors=[];
 const call=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}))});
 ws.onmessage=({data})=>{const m=JSON.parse(data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(m.error.message)):p.resolve(m.result)}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text);else if(m.method==='Page.javascriptDialogOpening')call('Page.handleJavaScriptDialog',{accept:true})};
 const js=async expression=>{const r=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};
 const wait=async exp=>{for(let i=0;i<100;i++){if(await js(exp))return;await new Promise(r=>setTimeout(r,100))}throw Error('Timed out: '+exp)};
 const state=()=>fetch(base+'/api/portal').then(r=>r.json());
 const send=async text=>{await js(`document.querySelector('#tutorInput').value=${JSON.stringify(text)};document.querySelector('#tutorInput').dispatchEvent(new Event('input'));document.querySelector('#tutorComposer').requestSubmit()`);await wait("document.querySelector('#tutorStop').hidden")};
 await fetch.browser(base,call);await call('Runtime.enable');await call('Page.enable');await call('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
 await call('Page.navigate',{url:base});await wait("!!document.querySelector('#tutorComposer')");
 await js("document.querySelector('[data-view=tutor]').click()");
 await wait("getComputedStyle(document.querySelector('.tutor-shell')).display==='flex'");
 assert(await js("document.querySelector('#tutorInput').getBoundingClientRect().width>750"));
 assert(await js("document.querySelector('#tutorInput').getBoundingClientRect().height>=80"));
 assert.equal(await js("document.querySelectorAll('.chat-starters button').length"),4);
 const screenshot=async name=>{const shot=await call('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(os.tmpdir(),name),Buffer.from(shot.data,'base64'))};
 await screenshot('portal-chat-desktop.png');
 await js("document.querySelector('[data-prompt=\"1\"]').click()");assert(await js("document.querySelector('#tutorInput').value.includes('tomorrow')"));
 // Browser-generated test image: no external downloads or real student images.
 const attach=`var png=Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII='),c=>c.charCodeAt(0));var dt=new DataTransfer();dt.items.add(new File([png],'test.png',{type:'image/png'}));document.querySelector('#tutorImage').files=dt.files;document.querySelector('#tutorImage').dispatchEvent(new Event('change'))`;
 await js(attach);await wait("!document.querySelector('#tutorImagePreview').hidden");assert(await js("!!document.querySelector('#tutorImagePreview img')"));
 await js("document.querySelector('#tutorImagePreview button').click()");assert(await js("document.querySelector('#tutorImagePreview').hidden"));
 await js("var pasted=new DataTransfer();pasted.items.add(new File([png],'pasted.png',{type:'image/png'}));document.querySelector('#tutorInput').dispatchEvent(new ClipboardEvent('paste',{clipboardData:pasted,bubbles:true}))");await wait("!document.querySelector('#tutorImagePreview').hidden");
 assert(await js("document.querySelector('#tutorImagePreview').textContent.includes('pasted.png')"));await js("document.querySelector('#tutorImagePreview button').click()");
 await js("document.querySelector('#view-tutor').dispatchEvent(new DragEvent('drop',{dataTransfer:pasted,bubbles:true,cancelable:true}))");await wait("!document.querySelector('#tutorImagePreview').hidden");await js("document.querySelector('#tutorImagePreview button').click()");
 await js("var bad=new DataTransfer();bad.items.add(new File(['bad'],'test.svg',{type:'image/svg+xml'}));document.querySelector('#tutorImage').files=bad.files;document.querySelector('#tutorImage').dispatchEvent(new Event('change'))");
 assert(await js("document.querySelector('#tutorComposerError').textContent.includes('PNG')"));
 await send('Add a reminder every Monday');await wait("!!document.querySelector('.reminders-form')");
 assert.equal((await state()).reminders.length,0);
 await js("document.querySelector('[data-cancel]').click()");assert.equal((await state()).reminders.length,0);
 await js("document.querySelector('.proposal-review').click();document.querySelector('.reminders-form').requestSubmit()");await wait("!document.querySelector('.reminders-form')");
 const reminders=(await state()).reminders;assert.equal(reminders.length,9);assert.equal(reminders.at(-1).due_at.slice(0,10),'2026-11-16');
 await send('Add a study session');assert.equal((await state()).timetable_events.length,0);
 await js("[...document.querySelectorAll('.proposal-review')].at(-1).click()");
 assert.equal(await js("document.querySelector('[data-field=event_date]').value"),'2026-10-05');
 assert.equal(await js("document.querySelector('#importRepeat').value"),'none');
 await js("document.querySelector('.calendar-form').requestSubmit()");await wait("!document.querySelector('.calendar-form')");
 assert.equal((await state()).timetable_events[0].start_time,'09:30');
 await send('Add mixed classes');await js("[...document.querySelectorAll('.proposal-review')].at(-1).click()");
 assert.deepEqual(await js("[...document.querySelectorAll('[data-field=recurrence]')].map(el=>el.value)"),['none','weekly']);
 await js("document.querySelector('.calendar-form').requestSubmit()");await wait("!document.querySelector('.calendar-form')");
 assert.equal((await state()).timetable_events.find(e=>e.title==='Mixed weekly').repeat_until,'2026-11-17');
 assert.equal((await state()).timetable_events.find(e=>e.title==='Mixed one-off').recurrence,'none');
 await send('Create study notes about TCP');assert.equal((await state()).notes.length,0);
 await js("[...document.querySelectorAll('.proposal-review')].at(-1).click();document.querySelector('[name=title]').value='Edited TCP note';document.querySelector('[name=week]').value='4';document.querySelector('.calendar-form').requestSubmit()");await wait("!document.querySelector('.calendar-form')");
 assert.equal((await state()).notes[0].title,'Edited TCP note');
 // API rejects invalid batches atomically, and retries never overwrite notes.
 const before=(await state()).notes.length;
 const invalid=await fetch(base+'/api/notes/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({notes:[{id:'rollback1',title:'Valid',content:'Text'},{id:'rollback2',title:'Foreign key',content:'Text',subject_id:'missing'}]})});assert(!invalid.ok);assert.equal((await state()).notes.length,before);
 const note=(await state()).notes[0];await fetch(base+'/api/notes/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({notes:[{...note,title:'Must not overwrite'}]})});assert.equal((await state()).notes[0].title,'Edited TCP note');
 await js(attach);await wait("!document.querySelector('#tutorImagePreview').hidden");await send('test failure');
 assert.equal(await js("document.querySelector('#tutorInput').value"),'test failure');assert.equal(await js("document.querySelector('#tutorImagePreview').hidden"),false);
 assert(await js("document.querySelectorAll('.message-image').length>0"));
 await js("document.querySelector('#tutorImagePreview button').click();document.querySelector('#tutorInput').value='test slow';document.querySelector('#tutorComposer').requestSubmit()");await wait("!document.querySelector('#tutorStop').hidden");
 await js("document.querySelector('#tutorStop').click()");await wait("document.querySelector('#tutorStop').hidden");assert.equal(await js("document.querySelector('#tutorInput').value"),'test slow');
 await js("document.querySelector('#tutorNew').click()");assert.equal(await js("document.querySelectorAll('.chat-proposal').length"),0);assert.equal((await state()).reminders.length,9);
 await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await new Promise(r=>setTimeout(r,250));
 assert(await js("document.documentElement.scrollWidth<=innerWidth"));assert(await js("document.querySelector('#tutorInput').getBoundingClientRect().width>300"));
 assert(await js("document.querySelector('#tutorSend').getBoundingClientRect().bottom<=innerHeight"));
 await send('Add work schedule: test missing drafts');
 assert(await js("document.querySelector('.chat-action-status[data-state=missing_actions]').textContent.includes('Nothing saved')"));
 assert.equal(await js("document.querySelector('#tutorInput').value"),'Add work schedule: test missing drafts');
 assert.equal(await js("document.querySelectorAll('.chat-proposal').length"),0);
 await js("document.querySelector('.chat-action-status button').click()");
 await wait("document.querySelectorAll('.chat-action-status[data-state=missing_actions]').length===2 && document.querySelector('#tutorStop').hidden");
 assert.equal((await state()).reminders.length,9);
 await screenshot('portal-chat-mobile.png');assert.deepEqual(errors,[]);
 console.log('PASS chatbot browser: desktop/mobile composer, starters, attachment preview/remove/type checks, reminder cancel/confirm, dated calendar event, edited note, atomic/idempotent note save, retry with image, stop, new chat, no JavaScript errors.');ws.close();
})().catch(e=>{console.error(e);process.exit(1)});
